### ISSUE TITLE
Invisible collision while shimmying

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#101]
In TR1 _Lara's Home_ go to the gym and try exercise 5. Lara get stuck while shimmying.

**Comment by vvs-** [comment]
After refactoring it's now prevalent everywhere. There is a workaround though. To overcome an invisible obstacle you need to release right/left key and then press it again. After several attempts Lara should be finally able to continue shimmying.

**Comment by stohrendorf** [comment]
Her belly collision object is too big, it gets stuck at the triangle edges.

**Comment by vvs-** [comment]
Seems to be much better now, just like it was before. From the other hand seems the workaround doesn't work anymore.

**Comment by Lwmte** [comment]
Either it's because shimmying trajectory is not calculated correctly, or as noted by @stohrendorf, body parts create false "fixing" event.

Whole "fixing" business has to be re-thought, we basically don't need to fix Lara position based on body parts in most of the cases.

**Comment by vvs-** [comment]
Shimmying now fixed, but Lara can't climb the wall in gym. You'd need to make a directional jump for that.

**Comment by vvs-** [comment]
Also, try to grab the ledge in sector `1,4` of room 1 in _City of Khamoon_. Lara is pushed away from it because of he hands collision with the ceiling.

**Comment by vvs-** [comment]
This looks very similar to #257. I wonder, could it be for the same reason?

**Comment by vvs-** [comment]
This makes it really hard to pick-up objects under water.
