### ISSUE TITLE
Missing collision on ladder sector in SHORE.TR2

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#11]
In TR3's Coastal Village, there is a collision missing on a sector with ladder (Smuggler's passage).

**Comment by TeslaRus** [comment]
I can't found missing collision. Only in TR3, map 6 I found room with missing collision, but it was fixed in 043378f1a453a63fe413da09a5e075d24fc812d7

**Comment by Lwmte** [comment]
Ok, here is video for it! http://youtu.be/rytd8mJv8DY

**Comment by TeslaRus** [comment]
I found the reason: ladder static mesh has a box collision flag, but these code in resource.cpp:
2104: vec3_copy(r_static->mesh->bb_min, r_static->cbb_min);
2105: vec3_copy(r_static->mesh->bb_max, r_static->cbb_max); 
overrides bb_settings to NULL collision (bb_min == bb_max); comment that code is not good: trees collision become pretty wrong! I see one correct solution: use two bbox flags in scripts: based on base_mesh and based on static_mesh; static_mesh is default, base_mesh flag blocks bbox replacing and next replaced to default box collision flag... I will fix it in some minutes...

**Comment by TeslaRus** [comment]
fixed, see commit d0bd4e7794da6d7c44aad9c221f6dde69fca3af8
but may be there are other maps with the same problems (and ladders collision must be based on boxes only!);

**Comment by vvs-** [comment]
Why is this still open? Hasn't it been fixed already?

**Comment by Lwmte** [comment]
No, it is not fixed, and it won't be fixed until collision model is changed. Current workaround is ineffective, as there may be more such cases in other levels. 

Honestly, I'm not a big fan of "workarounds" like, "let's write a script override for each problematic sector in TR games". If we need such workarounds, it means that collisional model is flawed.

Also, this is related to #223.

**Comment by Lwmte** [comment]
Closing this, as it's directly related to #223.
