### ISSUE TITLE
Crash after level loading

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#111]
`Assertion 'pa_atomic_load(&(b)->_ref) > 0' failed at pulsecore/memblock.c:486, function pa_memblock_acquire(). Aborting.`

**Comment by vvs-** [comment]
I can't reproduce this after the last merge. I'll watch this for some more time.

**Comment by stohrendorf** [comment]
I guess this is because it used the internal headers while linking to the external system openal lib. Happened with bullet to me all the time, so I'll close this.
