### ISSUE TITLE
Window resizing is not working properly

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#113]
It doesn't restore its size when maximizing window. Also, after loading level the console starts blinking (though I'm not sure if these are related).

**Comment by vvs-** [comment]
In fact, it seems that this was already fixed at some point.

**Comment by vvs-** [comment]
Turned out it's an optimization bug. Turned off optimization and now it's back.

**Comment by Lwmte** [comment]
What exactly should I turn off to get rid of this bug?
I have same situation. SDL_WINDOWEVENT is just not happening when it should.

**Comment by vvs-** [comment]
I don't know. With "-O2" optimization I don't have this bug. It happens only with "-O0", i.e. in debug builds.

**Comment by stohrendorf** [comment]
I remember inserting an `#ifndef NDEBUG` somewhere to avoid the main window capturing the mouse cursor to allow me some debugging. I guess that's the cause why it happens only in debug mode.

**Comment by vvs-** [comment]
No, it's not the reason.

**Comment by stltomb** [comment]
When I remove the code from `Controls_PollSDLInput()` that checks if the game window has focus, resizing starts working again. The condition should probably go directly into the `SDL_MOUSEMOTION` case where `SDL_WarpMouseInWindow()` is. The mouse warping problem mentioned in #107 wasn't present when I tried it (both debug and release builds).

This also fixes another issue you may not have noticed - you can't quit the game if the window has no focus.

**Comment by Lwmte** [comment]
Yes, it is really annoying. Thank you!
I don't remember if focus check was there before refactoring, cause everything worked as it should back then...

**Comment by stltomb** [comment]
There was no focus check. As far as I can see, it was added to fix #107.

**Comment by vvs-** [comment]
I believe there is something wrong with events polling. Looks like some events get lost and never reach their destination. On certain optimization level compiler just removed some code and coincidentally restored correct processing.
