### ISSUE TITLE
Handling of platform-specific code

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#119]
Since we're already discussing, how about this one? We got a few cases where code needs to be specific to some platforms. Some platforms in this case almost always means Mac OS X (yes, I know, we're annoying special snowflakes), though other code to deal e.g. with Windows is also possibly in there or might be added in the future.

Here's how I've been handling this so far:
-   Where possible, the Mac-specific version of a function is in the same file in the same place as the normal one. It is guarded with `#ifdef`or `#if defined()`
-   The macro I check for is `__APPLE_CC__`, which technically only checks for an Apple compiler. I'm thinking about changing that to something Mac OS X-specific. For windows, I imagine some version of `WIN32` would be acceptable.
-   I only use separate files to access Mac OS X APIs that require Objective-C (so far there has been one such file). I put these in `src/mac`. Other versions would probably be `src/win` and `src/linux`, though I can't imagine any scenario where this would actually be necessary.

If nobody objects, I'll just keep doing that, but if you have better ideas that are maybe less annoying to all the non-Mac developers, let's hear it.

**Comment by stohrendorf** [comment]
I think it would be better to have this handled in the cmake script, something like
```
if(WIN32)
    add_definitions(-DOS_WINDOWS)
elseif(APPLE)
    add_definitions(-DOS_MAC)
elseif(LINUX)
   ...
```

**Comment by vvs-** [comment]
Provided that other platforms use cmake which isn't the case right now.

**Comment by cochrane** [comment]
They don't? Then what do they use!? I was under the assumption that cmake was what everything (but me so far) was using, and I wanted to move there as well for consistency. Cmake is very far from optimal in a Mac-only scenario, so my enthusiasm for it is very dampened if it were hair for me.

**Comment by vvs-** [comment]
AFAIK cmake is used only on Linux. Windows users prefer Code::Blocks project.

**Comment by stohrendorf** [comment]
CMake is a **Cross Platform Make Tool**; it works on the target platforms and can generator project and make files for every commonly used dev environment or build system. It can even generate Code::Blocks project files (which btw are used by Qt Creator if you open a cmake-based project).

**Comment by vvs-** [comment]
You underestimate their needs to adopt it to their own needs. They know how to work in Code::Blocks but they have no clue how to modify cmake projects.

**Comment by Gh0stblade** [comment]
I actually prefer guarding platform specific code under #ifdef #ifndef like how it originally was. I don't see any need to change it at this point.

**Comment by stohrendorf** [comment]
Well, cmake *is* for creating a synchronized build environment.

**Comment by cochrane** [comment]
No longer needed, references old version of the code.
