### ISSUE TITLE
Texture atlas is broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#124]
Right now texture atlas has a huge size (~680 MB for *Caves* level) while a previous version has only 16 MB. That's an indication of a bug. Unfortunately, there is nothing visible until #117 is fixed.

I guess I'll open a new issue for that because it's actually a separate bug.

**Comment by cochrane** [comment]
I'm currently helping my sister move, so I can't deal with it right now. Monday probably.

**Comment by stohrendorf** [comment]
I have finally managed to make my branch compile on windows and attached CodeXL on it; there are many huge textures which seem to be broken a bit, but with pretty similar content: http://earvillage.net/opentomb/texture-mem.png (also, only the very left column of them is filled).

**Comment by vvs-** [comment]
I compared textures that I exported from OpenGL traces of old and new versions. They are still broken: the old version have 16 MB and the new one - 32 MB of textures.

**Comment by stohrendorf** [comment]
The texture atlas creates only a single 4k x 2k texture here, yet it is only sparsely filled.
![tr-texture](https://cloud.githubusercontent.com/assets/7853507/8560166/9d570a30-2515-11e5-8993-40ce6e6767db.png)

**Comment by vvs-** [comment]
Yes, 4k x 2k x 4 bytes (ARGB) = 32 MB.

**Comment by stohrendorf** [comment]
I'll look into it to see if I can modify the algorithm a bit to *not* allocate such huge pages at first.

**Comment by stohrendorf** [comment]
OK, I reduced the memory usage to 8MB, although it uses 8 512x512 pages now. Here's the magic:
```
// Idea: sqrt(sum(areas)) * sqrt(2) >= needed width
{
    size_t areaSum = 0;
    for(size_t i=0; i<object_texture_count; ++i)
        areaSum += object_textures[i].x_size * object_textures[i].y_size;
    for(size_t i=0; i<sprite_texture_count; ++i)
        areaSum += (Spriteextures[i].x1-Spriteextures[i].x0) * (Spriteextures[i].y1-Spriteextures[i].y0);

    m_resultPageWidth = std::min( max_texture_edge_length, GLint(NextPowerOf2(std::sqrt(areaSum)*1.41)) );
}
```

**Comment by vvs-** [comment]
While you at it, could you fix that `Spriteextures` typo?

**Comment by stohrendorf** [comment]
I'm not focused on it, I'm still playing around. In fact I planned to have my holidays since monday, but now I'm hunting the bugs I created :grinning:

**Comment by vvs-** [comment]
That's the rule: never push big changes on Friday and go on holidays.

**Comment by stohrendorf** [comment]
Well, I didn't expect to get the pull request merged so soon. But now it happened, and I really want to solve the problems, although I really need a break now for a few days.

**Comment by vvs-** [comment]
Troubles are always happen when nobody expect them. That's why that rule was invented.

**Comment by stohrendorf** [comment]
Well, I do know these "Friday-near-home-time-tickets" very well from work... yet I did this on purpose here, so that I could spend my full time for any issues.

**Comment by vvs-** [comment]
That's what my former boss told us every time: "If we do it on Friday then we'll have all weekend to fix it". :smile:

**Comment by stohrendorf** [comment]
Well, it happened. But now I'm a few days off (meaning no coding, but I will still keep a look at the tickets). Feel free to hack around in the luastate branch.

**Comment by vvs-** [comment]
Good luck.

**Comment by Lwmte** [comment]
Perhaps, we got your pull request wrong, when you said that you need merge because difference between branches prevents you from making further changes. Anyway, I think that when all bugs are sorted out, we'll make a breakthrough! ;)

**Comment by vvs-** [comment]
Then I propose a rule that any *nontrivial* pull request should not be merged until it has been tested for at least few days.

**Comment by stohrendorf** [comment]
+100 for that!

**Comment by vvs-** [comment]
Why don't compare the old and the new implementation? They are not that different and code is of a modest size. It's so self-contained that I was even able to revert to it quite easily. I'd do it myself but it will take much more time because I'm not familiar with either version.

**Comment by stohrendorf** [comment]
I'm doing exactly that right now.

**Comment by stohrendorf** [comment]
... and I can't see anything, but maybe I'm too blind after hunting bugs 12 hours a day for a full week now.

**Comment by vvs-** [comment]
Right. We need a fresh eyes and those who are familiar with the old code.

**Comment by vvs-** [comment]
And please reopen this too.

**Comment by Lwmte** [comment]
I believe texture layout is done wrong. Which in turn possibly relates to broken bsp_tree_2d module.

**Comment by Lwmte** [comment]
Ok, seems I can't let it go that easily. Removing *See whether it already exists* condition in ` addObjectTexture ` makes it a little better. At least animated water textures are correct, as well as about 60% of all other textures. Which possibly indicates that problem with texture atlas is a combined problem of several bugs in different places.

**Comment by Lwmte** [comment]
Yes. I found it. Another faulty code part is in ` layOutTextures `. It's a for loop right under *Try to find space in an existing page* comment. I have removed this loop (which increased loading time to about 30 seconds and memory consumption), and received completely intact texture layout (except animated textures).

Have no idea how resulting texture atlas looks like, most likely it's still messed up anyway, as I forced each texture info to create unique atlas page.

**Comment by Lwmte** [comment]
Fixed. Check out atlas layout.

**Comment by vvs-** [comment]
Yes, the layout is still broken - it uses 32 MB of memory. But the texture coordinates are fixed.

**Comment by Lwmte** [comment]
I will leave this task to Cochrane or Steffen. Because it took me whole night to figure out even this little thingy.

**Comment by vvs-** [comment]
For me it would took even longer if I would try :disappointed:

**Comment by Lwmte** [comment]
I could actually try, but only if I find some kind of utility which allows to dump OpenGL textures. Steffen uses ATI debugger, but there's no such thing for Nvidia chipsets.

**Comment by vvs-** [comment]
I'm using [apitrace](https://github.com/apitrace/apitrace) but it's buggy as hell. I've tried Vogl but it doesn't even compile.

**Comment by stohrendorf** [comment]
On Windows, I'm using RenderDoc, which does a pretty good job.

**Comment by Lwmte** [comment]
Hmm, it crashes every time I try to launch OpenTomb through it or attach to existing process.

**Comment by Lwmte** [comment]
Oh, sorry, seems I was using old version. Now it works.

**Comment by vvs-** [comment]
Performance has dropped significantly. No doubt because of a faulty texture layout. It's very visible in TR4/5.

**Comment by Lwmte** [comment]
It seems that my fix was actually wrong, as texture coordinates were correct exactly because ` fits ` function returns wrong value. No idea how it can affect performance, though.

**Comment by vvs-** [comment]
I didn't check it, but from your own words there are now many pages in the atlas. I believe that's the reason.

**Comment by Lwmte** [comment]
No, it was when I told you that I forced something to always create new page for each new texture. For current "fix" it only modifies ` fits ` function incorrectly, which coincidentally fixes texture coordinates.

**Comment by Lwmte** [comment]
By the way, I can't revert texture atlas to your ` stability_fixes ` branch, cause constructor declaration don't match its implementation.

**Comment by vvs-** [comment]
Hm... Then I don't know. But reversing the texture atlas restores performance as well.

**Comment by vvs-** [comment]
I will push another branch in the moment.

**Comment by vvs-** [comment]
Try `reverts` branch. It has everything applied.

**Comment by Lwmte** [comment]
I found another possible bug. In ` findSpaceFor ` method, there is missing ` left->isFilled = true; ` line right before ` // height already fits, width fits too now, so this is the result ` comment. If I restore it and remove my previous "fix" with ` fits ` function, coordinates will be applied correctly too, but atlas is still not properly filled.

**Comment by Lwmte** [comment]
I just need reverted code to get an idea how atlas *should* be filled to understand current situation! :smile: And my old branch don't work cause it was non-OpenGL 3.2.

I hope Cochrane will be back soon, cause this BSP is kicking my ass... I can't understand whole principle! :smile:

**Comment by Lwmte** [comment]
WELL... I have found something else.
In Cochrane's comment for ` TextureSizeComparator ` function, he tells that ` qsort ` inverts sorting order. I guess he left this comment to point out a difference between ` qsort ` and ` std::sort ` functionality. So I just inverted all the conditions inside ` TextureSizeComparator `, and now texture atlas looks like this:

![atlas](https://cloud.githubusercontent.com/assets/3331699/8699064/62bbdb02-2b0b-11e5-99e7-2e724e7e17c9.png)

Coordinates are also applied correctly.
As you see, there is a lot of free space left at top, but I guess it's because atlas size must be power of 2?

**Comment by vvs-** [comment]
Yes, that's the reason why I'm using these reverts. Otherwise there is no way to see how it worked before.

BTW, my `reverts` branch is OpenGL 2 too, but that didn't change any functionality because OpenGL 3 isn't *actually* needed. It's not enough to change OpenGL context to another version. There should be actual *features* that need that.

**Comment by vvs-** [comment]
If you compare with reverted (old) atlas then you'll see that the top was empty.

**Comment by Lwmte** [comment]
Oh. Then I guess we nailed it! :smile: :smile: :smile: 

Another note. There is commented code from Steffen which presumably lowers space consumption by texture page (the one in the beginning of ` BorderedTextureAtlas ` constructor). I've uncommented it, but what it actually does is breaks it into 512x512 independent textures. This is not what we want to do, right?

Is it possible to make BSP algorithm to work within non-power-of-2 area size?

**Comment by vvs-** [comment]
I don't know. Ask cochrane about it.

**Comment by Lwmte** [comment]
Seems like removing code which follows ` // Fix up heights if necessary ` comment removes black border from the top. But I guess if Cochrane added it, there is a purpose. Possibly, something to do with mipmaps? I will open another issue for this instead of this one.

**Comment by vvs-** [comment]
I'd leave it alone until everything is fixed. Then let cochrane decide if it could be changed.

**Comment by Lwmte** [comment]
I think we should leave it as it is, according to this: https://www.opengl.org/wiki/NPOT_Texture

**Comment by cochrane** [comment]
Sorry for the delay. The black border is indeed to get a height that is a power of two, and created by the fix up heights portion. We only need this on cards that do _not_ support GL_ARB_texture_npot extension or, I think, OpenGL 2 or higher. I originally had code in there that checked for the presence of this exception and skipped this whole size fix up in that case, but someone deleted it somewhere along the way.

**Comment by cochrane** [comment]
(Presumably because of the issues mentioned in the wiki)

**Comment by vvs-** [comment]
It was removed in 926e972eb8a42276f125cbaff53ba4be02706d99.

**Comment by Lwmte** [comment]
I remember some talking about this NPOT situation, presumably TeslaRus thrown it out for compatibility purposes, or just to make things cleaner. Anyway, it's not a big deal, how much we're losing here? One megabyte or two? Give me a break! :smile:
