### ISSUE TITLE
SYSWARN_WRONG_SOUND_ID

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#127]
Happens in *Atlantis* and *The Great Pyramid*.

**Comment by stohrendorf** [comment]
can you test again please?

**Comment by vvs-** [comment]
Nothing has changed. Perhaps it depends on other bugs.

**Comment by vvs-** [comment]
Also, SYSWARN_AS_NOSAMPLE when `h` is pressed.

**Comment by vvs-** [comment]
Actually, WRONG_SOUND_ID is not fixed.

**Comment by vvs-** [comment]
Ah? Again :smile:

Please, reopen this.

**Comment by vvs-** [comment]
I don't have these anymore. I hope it's not because of reverts in my branch.
