### ISSUE TITLE
Binding console to F12 - why?

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#134]
I know that F12 is commonly used for console in many applications, however, historically almost any game with console functionality used tilde key for this purpose. I think this change should be reverted.

**Comment by stohrendorf** [comment]
This was because I wasn't able to open the console using the backtick, or the tilde. Maybe it was due to other bugs I introduced, but if it works on all target platforms, I personally don't have any objection.

**Comment by vvs-** [comment]
I heard that some people with weird keyboard layout has problems with tilde. Perhaps it was on french keyboards or something else which I don't remember.

**Comment by Lwmte** [comment]
I thought that keyboard layout problems were sorted out after console text input patch by Tonttu ( db40676), but it seems they were not... We've never fully sorted out whole SDL scancode vs. keycode business.

**Comment by Joey79100** [comment]
On French keyboards, the console opens with key "²", which is situated just between Esc and Tab. Maybe it was on another keyboard?
Is it possible to bind it in config.lua? It would make things easier.

**Comment by stohrendorf** [comment]
Is there any need to discuss this further, or can it be closed?
