### ISSUE TITLE
Ubuntu 14.04 LTS build failed

### ISSUE THREAD

**Issue by nhfl** [opentomb/OpenTomb#135]
Cloned OpenTomb Sun 5 July 21:54

CMake failed for Lua as unable to find cmake file. Have the following installed:
liblua5.1-0
liblua5.1-0-dev
liblua5.2-0
liblua5.2-dev
cmake-data 2.8.12.2-0ubuntu3 has FindLua50.cmake and FindLua51.cmake
FIX: use FindLua52.cmake from Kitware and change CMakeLists.txt
```
INCLUDE(cmake/FindLua52.cmake)
INCLUDE_DIRECTORIES(${LUA_INCLUDE_DIR})
```

CMakeLists.txt has add_subdirectory(3rdparty) where there is no CMakeLists.txt file
FIX: comment out the line

Failed to build audio.cpp
FIX: add efx.h to audio.h
```
#include <AL/al.h>
#include <AL/efx.h>
#include <AL/efx-presets.h>
#include <AL/efx-creative.h>
```
Order of AL includes makes a difference to build or fail. Removed any AL/ includes from audio.cpp as it includes audio.h

**Comment by stohrendorf** [comment]
If `find_package(Lua)` doesn't work for you, it's probably a problem on your system, because the standard bundled cmake scripts usually do their job just fine.

**Comment by nhfl** [comment]
Agree the find_package(Lua) is a system problem. Would it be worth documenting in the readme and giving the work around. As you probably already know, Ubuntu is a very popular distribution and the 14.04 LTS version will be around until 2019 so this could keep presenting as a problem.

**Comment by stohrendorf** [comment]
I'm still convinced it isn't a general problem on Ubuntu 14.04, otherwise there would be many packages requiring that workaround if they use Lua. I'd say that this only needs to be documented if others can approve your problem.

**Comment by stohrendorf** [comment]
If nobody can confirm this, I'd like to close this one.
