### ISSUE TITLE
Frustum::isPolyVisible is broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#137]
It looks like it always return false in noclip mode. That's why there are no rooms in render list.

**Comment by Lwmte** [comment]
And what about non-noclip mode? Seems that I always can view only current room.

**Comment by vvs-** [comment]
That's not the only bug, unfortunately. There is something else broken in frustum.

**Comment by Lwmte** [comment]
Seems that ` currentPlane->distance(prevVertex->position) ` always returns ridiculous number (-108989478998724164782393795805184), while it should return normalized vector length. That's the reason why test fails.

**Comment by vvs-** [comment]
That's again might be related to planes/projections/matrices.

**Comment by Lwmte** [comment]
I think that whole ` Plane ` class currently is faulty. Because its methods sometimes return *nan*, or mostly non-realistic numbers.

**Comment by vvs-** [comment]
If I'd only know geometry better :disappointed: Because debugging it blindly, without knowing what to look for, could take ages.

**Comment by Lwmte** [comment]
Same thing... I barely passed math exams in my school. Now I suffer because I haven't tried a bit harder back then... :smile:

**Comment by vvs-** [comment]
I love algebra but geometry always was my weak spot. I'm planning to upgrade my math level but it will take months if not years.

**Comment by Lwmte** [comment]
For another offtopic, do you know what's happening right now? We have currently 150 visitors online in our forum thread, and star count almost doubled in less than one hour! :astonished:

**Comment by cdietschrun** [comment]
https://www.reddit.com/r/Games/comments/3dd3mp/opentomb_an_open_source_engine_for_classic_tomb/

that happened

**Comment by Lwmte** [comment]
Well... This is stunning, I remember I posted a video on reddit, and it went viral in one week. Must visit it more frequently! :smile:

**Comment by Lwmte** [comment]
Frustums between normal and water rooms are still broken though... I wonder if it's related to this bug or shader transparency bug.

**Comment by vvs-** [comment]
No, it's a transparency issue. I can tell it because I reverted to OpenGL 2 and transparency is working for me :smile:

**Comment by vvs-** [comment]
Is it working for you after 152c08dc25d33cc89eccfb0b71a86552521bbce8?

**Comment by Lwmte** [comment]
Yes, it's all good!
