### ISSUE TITLE
Need list of external libraries

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#141]
Until #115 is closed, and possibly even after that, we need a list of all the third-party libraries that are required to compile OpenTomb. This list should be kept up to date, so it's easier to get started even if you missed a few days of development.

I have started such a list here: https://github.com/opentomb/OpenTomb/wiki/Required-third-party-libraries

It may include things that are no longer required and lack others; among other things, I have no idea where the file LuaState.h is supposed to come from. Please update the list needed and then close this issue.

**Comment by stohrendorf** [comment]
Actually, `LuaState.h` comes from a git submodule. More specifically, from my own fork that generates much less warnings and also spits out compiler errors instead of late linker errors.

**Comment by cochrane** [comment]
Ah, that's where it was! I see you already updated the list, so as far as I'm concerned, we can close this one, unless there's anything else that needs changing here.

**Comment by stohrendorf** [comment]
No updates for nearly 4 weeks, closing this.
