### ISSUE TITLE
Integrate huboard.com

### ISSUE THREAD

**Issue by stohrendorf** [opentomb/OpenTomb#146]
It's free for open source projects and allows a much better overview and control over tickets on github. See https://huboard.com/.

**Comment by Lwmte** [comment]
I'm sorry that I didn't made attention to this ticket, but how do I integrate it to our repository? I tried to authorize huboard app for repository, but seemingly nothing happened.

**Comment by stohrendorf** [comment]
It is integrated, all you (and everyone else who wants to use it) need to do is to allow this third-party application access. Try to log out and in again.

**Comment by Lwmte** [comment]
Ok, now it works, but I'm a bit lost... It created 4 additional labels, what should I do now?

**Comment by stohrendorf** [comment]
Currently, all tickets are in the "backlog". This is the area reserved for tickets that should be worked on when there's nothing else to do. You may then grab tickets (drag+drop) and move them over to the "ready" column to say: "Hey, this should be worked on.". When it is being worked on (i.e., someone starts working on it), he can move it over to the "working" column. And once that's done, it should be moved to the "done" column. This way you can easily see if someone already works on a ticket, and a leader (@Lwmte :smile:) can priorize tickets by grabbing them out from the backlog. So I guess the first thing to do is to move all the WIP tickets to the "working" column.

**Comment by stohrendorf** [comment]
And you may also order tickets vertically. This is especially useful for priorizing tickets in the "backlog" and "ready" columns.
