### ISSUE TITLE
Something nasty happened with my latest two commits.

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#148]
Now that's really funny, I just updated my scripts, which resulted in conflict (because of that change which converted all 0s and 1s to true and false). Ok, fixed that (only two files were modified), and now, when I tried to merge changes, I had this warning:

**Could not commit submodules:
3rdparty/LuaState
Add them as submodules from Git Shell or remove their .git folders to add them as a regular directories instead.**

Funny thing that this LuaState thingy was marked as changed file, while freetype2 and bullet were not marked. Now I go to changes window in GitHub and look what's with LuaState. It's like this:

**+ Subproject commit 0000000000000000000000000000000000000000**

What is this?

Ok, tried to merge everything but LuaState (unmarked it in changes list), GitHub hangs for about a minute, then I get **Commit failed** error.

Hell with that, now I wanted to roll back everything and just replace the scripts (which were actually two files with resolved conflicts), but GitHub blocks me from doing that as well, saying that roll back failed.

Now I notice that 3rdparty/LuaState disappears from changes list, and in hope that Git magically ruled out this issue, I try to commit again. GitHub hangs for another minute and successfully commits changes.

But now I notice that *there's no more link to LuaState* in 3rdparty. So most likely it won't compile anymore (I haven't even tried to compile the code, cause I get lots and lots of compiler errors, and I still need to understand how to get rid of them).

**Comment by vvs-** [comment]
That's because you need to checkout git modules first. If you don't have any uncommited changes I'd suggest to reset everything to `master` and try again. But if something was changed in your repository and you afraid that you can lose your work then push everything into your **own** repository under Lwmte user and then deal with it.

**Comment by Lwmte** [comment]
So far, I don't have any more changes in my code, as it was pushed to master. But now link to 3rdparty/LuaState is missing in master as well. This is the problem...

**Comment by vvs-** [comment]
That's not a problem at all. Just ask stohrendorf or someone else with commit rights to fix it.

**Comment by stohrendorf** [comment]
I'll do it. For the future, try this:
```
git stash
git pull --rebase
git stash pop
git push
```

**Comment by vvs-** [comment]
I guess he is using Windows shell, not cli.

**Comment by stohrendorf** [comment]
Event windows has a CLI in the github client. I just checked it. Alternatively, TortoiseGit does a pretty good job, too.

**Comment by vvs-** [comment]
There is a type in a directory name - it's `--forced` now.

**Comment by stohrendorf** [comment]
It's fixed, but I found a thousand ways how to **not** delete such a name from bash-compatible shells...

**Comment by vvs-** [comment]
Thanks stohrendorf!

The funny thing is that that typo wasn't visible through web interface. I guess we just found a bug in GitHub :smile:

**Comment by stohrendorf** [comment]
It *was* visible: https://github.com/opentomb/OpenTomb/tree/4a6fd092fe7f15718e6af5571a46954b9ab44175/3rdparty

**Comment by vvs-** [comment]
Yes, now it's visible. But I can swear that when I looked to it from the main page it wasn't there. Perhaps it's going through different code paths in that case.

**Comment by vvs-** [comment]
Another problem is that the typo is still present in `.gitmodules`.
