### ISSUE TITLE
CMakeLists.txt is broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#149]
Because of `add_subdirectory(3rdparty)` without corresponding project file.

**Comment by vvs-** [comment]
BTW, system freetype and bullet now can't be used because local instance is always assumed.

**Comment by stohrendorf** [comment]
These are the Friday evening bugs... sorry to say, but I'm away for a week from tomorrow on, and only want a needed break from fixing bugs, but I think I will take a look at the tickets from time to time.

For your issue, please `rm -rf *` your build directory (hopefully you have an external one) and do a clean cmake config.

**Comment by vvs-** [comment]
That's what I always do. But there is no `find_package` so unless I add it that won't build.

**Comment by stohrendorf** [comment]
It is: https://github.com/opentomb/OpenTomb/blob/master/3rdparty/CMakeLists.txt

**Comment by vvs-** [comment]
Sorry, I missed that it was in the `94c55f31f7fe859d434626e3e718658fcd06480c`.
