### ISSUE TITLE
Black fonts

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#151]
The fix is [here](https://github.com/opentomb/OpenTomb/issues/145#issuecomment-120607806)

**Comment by Lwmte** [comment]
I assume only shadow was rendered, that's why fonts are black. Why this line was commented in the first place?

**Comment by vvs-** [comment]
That's Steffens' hack for debugging which he forgot to remove.

**Comment by stohrendorf** [comment]
Why don't you fix it then if you know where the error comes from?

**Comment by vvs-** [comment]
It's a small bug not worth a PR. I'm still hoping that someone will fix it along other stuff.

**Comment by Lwmte** [comment]
I will fix it right away! ;)

**Comment by vvs-** [comment]
Fixed in d36177d28f693fb53440af5e6e3349f5cac8984a.
