### ISSUE TITLE
Redundant graphics/legal.png

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#154]
This file was introduced by 94c55f31f7fe859d434626e3e718658fcd06480c by mistake. There already is `resource/graphics/legal.png` which is the only one needed by the engine.

**Comment by stohrendorf** [comment]
Then why don't you delete it?

**Comment by vvs-** [comment]
Of course, creating a PR to delete a file or make a one line change is a bit... excessive.

**Comment by Lwmte** [comment]
I thought I already added you as a collaborator! Sorry, I got to check it up...

**Comment by vvs-** [comment]
Fixed
