### ISSUE TITLE
Transparency is broken

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#158]
If you look at partially transparent sprites from one side, you can't see other sprites through transparent zones, while looking from other side, you can. I believe something is wrong with alpha test here.

**Comment by vvs-** [comment]
Alpha test was broken by cochrane in ab1154897eb6e3547fe1d9fc5f582d4e842b62c1. I reverted it as well. It doesn't make any sense to remove working functionality before replacing it with something else. Steffen tried to fix it in 8b4cb532572285ae0e3bdaf6341ca37839501fe6 and 71087529210c0e7d562b5abc5855a348eefda7d8, but I can't say if it was successful because I can't use OpenGL 3.

**Comment by ablepharus** [comment]
May I ask what kind of graphics card you have?

**Comment by vvs-** [comment]
Intel GMA3000 integrated graphics. I got it with a free upgrade of my old computer.

**Comment by Lwmte** [comment]
Ah, OK then, I consider it unfinished! :smile: 

There is more funny stuff. Looks like error in some shader: 

![screen_00000](https://cloud.githubusercontent.com/assets/3331699/8683110/79deb512-2a79-11e5-86fe-937c5ae3340f.jpg)

**Comment by vvs-** [comment]
Yes, Lara can be seen even through broken frustums.

**Comment by Lwmte** [comment]
I also believe this is related to this bug:

![screen_00000](https://cloud.githubusercontent.com/assets/3331699/8765297/64718a72-2e0e-11e5-98e4-d22f95963b98.jpg)

**Comment by stohrendorf** [comment]
Is it still broken?

**Comment by Lwmte** [comment]
No, seems fixed as well! :smile: 
Strange, I don't get notifications with updates in certain tickets... Perhaps, some kind of overflow happened with my mailbox! :smile:

**Comment by Lwmte** [comment]
I am reopening this because of this:

![screen_00000](https://cloud.githubusercontent.com/assets/3331699/8862059/90737b5e-3196-11e5-98c6-2e2f91e21672.jpg)

**Comment by vvs-** [comment]
Do you mean that red color? I can't reproduce this. Seems to be driver dependent again.

**Comment by Lwmte** [comment]
I mean that skybox can be seen through "border" pixels, where transparent texels are blending with opaque texels. This is an indication of incorrect drawing order or incorrect alpha testing behaviour. I don't know how alpha testing is currently done, so I can't give more precise reasons why it is happening.

This is how it should look like:

![normal](https://cloud.githubusercontent.com/assets/3331699/8988014/95ee60ac-36ec-11e5-977b-fdef77c5a68e.jpg)

**Comment by stltomb** [comment]
The solution for me is to disable blending:
```
diff --git a/src/render.cpp b/src/render.cpp
index 688db3b..8eed2f8 100644
--- a/src/render.cpp
+++ b/src/render.cpp
@@ -857,8 +857,7 @@ void Render::drawList()
     }
 
     glEnable(GL_CULL_FACE);
-    glEnable(GL_BLEND);
-    glBlendFunc(GL_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
+    glDisable(GL_BLEND);
 
     renderSkyBox(m_cam->m_glViewProjMat);
```
It was disabled like that before the refactoring.
By the way, that argument to `glBlendFunc` is wrong, it should probably be `GL_SRC_ALPHA` instead of `GL_ALPHA`. Otherwise, the function is returning a GL error on every frame.

**Comment by vvs-** [comment]
And I can only say that I don't see any skybox through that grating.

**Comment by vvs-** [comment]
Ok. Found the reason. I can reproduce it only with mipmaps on. And I usually turn it off to remove that blur on textures.

**Comment by vvs-** [comment]
Pre GL 3 version indeed worked differently and used GL_ALPHA_TEST. Actually I reverted that changes until recent 6417e6a1ac2589922dda79966d4590c3cc103877. After that it became too hard to maintain a separate branch and now I'm forced to switch to that buggy version too :disappointed:

**Comment by Lwmte** [comment]
What can I say except thank you for the second time today! :smile:

**Comment by vvs-** [comment]
I don't think it's fixed. I just looked at the original where blurred pixels become more and more transparent, so I can see through them. In OpenTomb right now they just become more and more dark.

**Comment by stohrendorf** [comment]
Alpha blending works a bit different with GLSL, i.e. transparency is generally replaced with black. As far as I know, TR uses only a "true/false" transparency, which gets a gradient when mipmapping, so the more transparent a texel is, the darker it gets. I have found a way to implement alpha overlays in GLSL, but I didn't get it to work (basic idea is to use `gl_FragColor = (1-texColor.a)*gl_FragColor + texColor.a*texColor`).

**Comment by Lwmte** [comment]
@vvs- If you're talking about this, then it was like this long before refactoring:

![water](https://cloud.githubusercontent.com/assets/3331699/8994193/88782a4a-3712-11e5-94d7-b3c10b174bc6.jpg)

**Comment by vvs-** [comment]
May be. The transparency is still broken IMHO and it doesn't really matter who did it in particular.
