### ISSUE TITLE
Audible artifacts when playing sounds and music

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#162]
I just create this issue not to forget to fix it some day.

There is now *awful* sound distortion with certain effects and soundtracks, which sounds like bad dithering/resampling. Funny thing is that artifacts are heard even with 44.1 kHz ogg/wav files, while OpenAL itself works at 44.1 kHz too, so no resampling should be done.

Problem may be related to libsndfile converter, or OpenAL itself.

**Comment by Lwmte** [comment]
Seems it's not an issue with libsndfile, but with my audio output pipeline. I tested this on Winamp with two different output plugins - *DirectSound* and *WaveOut* - and TR1 ambience track (005.ogg). While DirectSound plugin made no distortion to audio, WaveOut resulted in exactly same artifacts as in OpenTomb.

Similar distortion occurs when I play it in either SoundForge or Audition with MME audio interface. When I switch to WASAPI interface, distortion goes away. I need to check what backend OpenAL uses to output. While it's clearly an issue with difference between two device interfaces, it's interesting if OpenAL produces it, or glitching occurs earlier - then I have to address either to OpenAL author or libsndfile author.

**Comment by Lwmte** [comment]
Seems I have found a reason.
It was difference between audio output format in Windows settings and file's own sample rate. While I had 48 kHz by default in settings, file itself was 44.1 kHz. DirectSound obviously produced no bug there, since it has its own rules for setting audio quality.

Now it's clear that bad guy here is OpenAL. I need to get backend info now.

**Comment by Lwmte** [comment]
This is MUCH deeper than I thought! :smile: 

The OpenAL libs which I built on my machine (with only MinGW installed) only included support for deprecated **winmm** backend! Obviously, because I have ancient MinGW. CMake script for OpenAL surely couldn't find DirectX SDK or MinGW-64 (which contain DirectSound and mmdevapi libs respectively), so it only enabled winmm, which is ancient as hell.

Pre-compiled OpenAL dlls also have no support for DirectSound / mmdevapi. Only dll which works normally is, surprisingly, Creative version from 2006! :smile: Of course, because this one was proprietary, and presumably used DirectSound for software output.

So, what should we do? There are two options. Either we must compile OpenAL Soft for Windows under VS (which has includes for DirectSound/mmdevapi), or use MinGW64. Because in other case we'll recieve library version which only works with outdated backend. It's no problem for testing purposes, but for nightly builds we must deploy proper version. So it's more question to *vobject*, is it possible to compile engine at least with MinGW64, which has headers for both DirectSound and mmdevapi?

**Comment by vvs-** [comment]
If it's so complicated, I'd question the sanity of the decision to compile OpenAL as a submodule. Shouldn't it be pre-built instead?

**Comment by Lwmte** [comment]
The problem is, *any* pre-built libs that I find on the Internet were seemingly also compiled with bare MinGW, so they all use winmm backend. Ironically, only one which uses DirectSound is outdated Creative one. 

Submodule should be used *only* on Mac machines, and exactly for opposite reasons - curent Mac OpenAL implementation lacks several key features of OpenAL Soft. But I suppose there are no such "backend hell" problems on Mac.

We just must use MinGW-64 for building all the libs on Windows. It looks promising, as it contains all the fancy Windows APIs that bare MinGW lacks. I will try to do it today. If it will work, I think this method should also be eventually used for nightly builds.

**Comment by Lwmte** [comment]
P.S.: Now I understand why TeslaRus had gone with creating his own SDL2 backend for OpenAL, it's exactly to avoid "backend hell" situation. Audio driver management is way better in SDL2.

**Comment by vvs-** [comment]
That's what I meant, we should use our *own* pre-built libraries on Windows. But do not expect users to build them from the sources.

**Comment by Lwmte** [comment]
I bet nobody will build OpenAL themselves, except us! :smile: 

So I have successfully rebuilt all my libs using MinGW-64+MSYS2. Also installed DirectX SDK to make sure CMake finds DirectSound headers. And finally, I have OpenAL32.dll which contains all three backends - mmdevapi, DirectSound and winmm. By default it uses mmdevapi on Win7. Sound quality is great! :+1:

**Comment by Lwmte** [comment]
By the way, if someone is interested, here is my freshly compiled OpenAL32.dll: http://trep.trlevel.de/temp/openal32.dll

It is based on latest OpenAL Soft git snapshot. Also I've used -O2 and -march-core2 flags.
