### ISSUE TITLE
[Info] How to extract game assets from Steam/GOG version under Linux

### ISSUE THREAD

**Issue by Ancurio** [opentomb/OpenTomb#165]
Hey guys, after a long evening of googling and trying stuff out yesterday, I finally found out how to get at the assets under Linux (if you don't have Windows at hand), so I thought I'd share it here in case anyone else runs into the same wall.

The problem is that even though the Readme states that you can just rename GAME.GOG to .iso and mount it, that doesn't work under Linux, because GAME.GOG is actually the .bin file of a cue/bin combination (if you ever dealt with ripping audio CDs, you should know what this is). Actually, the GAME.DAT file is a cue file (it is the file that is mounted under dosbox), but I think it's a faulty cue.

So we need a good cue file. Save this as "game.cue":
~~~
FILE "GAME.GOG" BINARY
TRACK 01 MODE1/2352
INDEX 01 00:00:00
~~~

Then use `bchunk` to write out the iso file:
~~~
$ bchunk GAME.GOG game.cue cdrom
~~~

This will create `cdrom01.iso` which you can finally mount:
~~~
$ mkdir cdrom_contents
$ sudo mount cdrom01.iso cdrom_contents
~~~

`bchunk` is available in the Fedora and Debian repositories.

As reward, Lara performed this beautiful dance for me:

![lara](https://cloud.githubusercontent.com/assets/1173822/8721104/d74f0e88-2bb7-11e5-8f96-0dfc6475ec2f.png)

**Comment by Lwmte** [comment]
Ha, she performs this dance for everyone right now! :smile: 
I guess, it's her ritual dance dedicated to C++ refactoring.

Back on topic - this whole GOG stuff is driving me nuts, why they decided to crypt CD image at all?

**Comment by Ancurio** [comment]
The CD image is not encrypted, it's just in a format that's easy to mount. All dosbox has to do is

    imgmount d ".\game.dat" -t iso -fs iso

**Comment by Lwmte** [comment]
I mean, they could just leave it game.iso/game.cue, without renaming to game.gog/game.dat.
