### ISSUE TITLE
Wrong find-and-replace entries

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#168]
Seems that odd *Spriteexture* thing is still not fixed.
Probably you have noticed other ridiculous find-and-replace cases?

Proposal: **DO NOT DO ANYTHING** with VT loader. Please. It will possibly be made into separate loader library. No more fancy name rearranging and renaming here, PLEASE. If you ever consider find-and-replace something else, IGNORE /vt folder.

**Comment by stohrendorf** [comment]
I'm sorry. I guess I accidentally disabled the "whole words" checkbox when searching for "sprite_t".

**Comment by Lwmte** [comment]
Ok then, I hope there are no more such errors in other parts of the code! :smile:
