### ISSUE TITLE
Broken animated textures in TR4+

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#17]
Possibly, something was broken either with changing UVRotate algorithm, with implementing room shader or with recent renderer/BTA optimizations.

**Comment by Lwmte** [comment]
Partially fixed by now, at least first frames of anim textures are visible instead of garbage.

**Comment by vvs-** [comment]
Textures were broken in d0cdae1cf72904de2f5ae43deecbb7c74ac9288a, but I suspect that animation could be broken later and just not visible.

Similarly, fountains were broken recently in 3a1ee0097bd80ae696743fa337469cafb5520106.

**Comment by Lwmte** [comment]
Fountains are now repaired, but strange thing is room textures with UVRotate applied to them are still broken. Also, classic animated textures are activated randomly in TR4-5, as I have working water animations in TR4 Angkor Wat, but no animations in TR5 Streets of Rome.

**Comment by vvs-** [comment]
Seems like the lighting that applied to these textures is incorrect and it was broken during #20, possibly matrix cleanup.

**Comment by Lwmte** [comment]
You mean "dark" doors in Qualopec? Yes, I noticed that; I don't actually remember if they were "normal" at some point, cause whole lighting system was never finished by Saracen. Or they were normal before merging with that Cochrane fork?

**Comment by vvs-** [comment]
Doors were dark, but not that black. And raptors, levers, falling ceiling, crumbled floor, boulder were normal colors in *Tomb of Qualopec*. It all was broken in #20. You can checkout just before that point. Also, though some water textures were already broken in d0cdae1cf72904de2f5ae43deecbb7c74ac9288a, you can still see some color animation sometimes in *Streets of Rome* and *Angkor Wat*.

**Comment by vvs-** [comment]
After last merge 7c2f01fc0cd8b707f45bf646954488b91ee1bcbd TR1-2 looks fine: lighting, progressbars - everything seems to be working. But TR3-5 seems broken: waterfalls, fountains, water, sunlight effects are missing. Also, there is no cursor in console.

**Comment by cochrane** [comment]
vvs, could you please open separate tickets for every issue you find? That makes it much easier to track. Also, if you find something new, please leave a new comment instead of editing the old one. That way I get an email telling me about it; otherwise I'll never know unless I randomly hop into an old bug again. Thank you, and keep finding bugs! :)

**Comment by vvs-** [comment]
Ok. It's just not obvious if that a new bug or a different manifestation of the old one. Also, some people prefer one big comment instead of a bunch of a tiny ones. But I agree that I created a mess here, sorry :smile:

**Comment by cochrane** [comment]
It's a matter of preference, of course. I prefer many small bugs, even if they overlap or have the same underlying cause (as long as that's not perfectly obvious). The reason for that is that I can easily close lots of issues with just one commit if they really are the same thing, but I cannot ever close half an issue.

**Comment by vvs-** [comment]
Animated textures are fixed. But the texture lighting problem is back. Shaders are old and need back porting.
