### ISSUE TITLE
Triggers are broken

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#175]
Seems that trigger scripts are either broken or parsed incorrectly, as Lara can't pick up items and trigger activation isn't working.

**Comment by Lwmte** [comment]
Ok, now it's better, but seems that `deactivateEntity` function is broken, as when I step onto antitrigger, door cyclically opens and closes (I can tell it even with faulty animations).

**Comment by Lwmte** [comment]
Now it works as it should, thanks! ;)

**Comment by vvs-** [comment]
Actually, it's not fixed: e.g. crumbled floor is not working.

**Comment by vvs-** [comment]
Pick-ups were broken by #179.

**Comment by Lwmte** [comment]
Crumbled floor probably not working for another reason - no proper callback is done on standing event. Falling floor even have no activation function defined.

**Comment by vvs-** [comment]
Aren't callbacks related to trigger processing?

**Comment by Lwmte** [comment]
Well... In originals - yes (an example is "locked" falling ceiling in Temple of Puna, until you trigger giant boulder), but in OpenTomb we currently have only rough implementation of it, and triggers are not involved for ENTITY_CALLBACK_STAND case. You can learn it in *character_controller.cpp* in `Character::moveOnFloor` function.

**Comment by vvs-** [comment]
Ok, we can open a separate issue, but I think this is so closely related that we can use this one too.

**Comment by vvs-** [comment]
Floor is working in *City of Vilcabamba* but not in *Caves*. What's the difference?

**Comment by vvs-** [comment]
Switches work in *Caves* and *City of Vilcabamba* but not in *St. Francis' Folly* and *The Cistern*.

**Comment by vvs-** [comment]
Looks like all the problems were collision related. I'll close this in this case.
