### ISSUE TITLE
Pick-ups in TR1/2 shouldn't be animated

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#176]
Once the pickups in TR1/2 had a code (or script) which disabled their default animations (from inventory). Now it seems this code is broken, and items are cyclically performing their "opening" animations (like medipacks).

Moreover, it seems that some animation code is broken as well, and animations are performed with errors.

**Comment by vvs-** [comment]
I've seen this even before refactoring.

**Comment by vvs-** [comment]
At least it's now as it was before.

**Comment by Lwmte** [comment]
Where you've seen it before refactoring? I thought I've nailed it long ago...

**Comment by vvs-** [comment]
Unfortunately, I've seen it from time to time but never found a reproducible test.

**Comment by Lwmte** [comment]
Only one reason why it may be not fixed is certain items are not registered in base item script (scripts\inventory\items.lua).
