### ISSUE TITLE
Ghost objects are not created

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#177]
There are no ghost objects for Lara (white boxes which wrap around meshes).

Ghost objects are needed for proper collision calculations and checks. So because they're missing, now Lara can freely jump through the walls (for example).

**Comment by Lwmte** [comment]
Found the reason. Steffen wrongly moved ` CreateGhosts() ` method into ` Character ` constructor. This is **completely** wrong. Because when character is created, there is *no model defined for it yet.*

So I moved ` CreateGhosts() ` out of constructor, right back into *resource.cpp* after `lara->genEntityRigidBody();` It belongs here, really.

**Comment by vvs-** [comment]
Seems that collision bugs are not just because of a missing ghost objects. The camera can go through walls and floors too.

**Comment by Lwmte** [comment]
You mean freelook camera, or classic one?

**Comment by vvs-** [comment]
A classic one. It can "punch" trough the walls and floors now.

**Comment by vvs-** [comment]
Here's a screenshot:
![screenshot from 2015-07-19 16 05 21](https://cloud.githubusercontent.com/assets/5171934/8765994/6a70bdc2-2e30-11e5-92ad-3921b2470631.png)

**Comment by Lwmte** [comment]
We must ask Gh0stBlade then what may be broken.
