### ISSUE TITLE
Animations for entities (not Lara) are broken

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#178]
All other animations seemingly broken, as there are "wrong" frames interlacing with normal ones.

**Comment by vvs-** [comment]
Laras' rolling animation is broken as well.

**Comment by Lwmte** [comment]
I believe it's trashed because of another reason - rotation override script command is broken. However, I can be wrong.

**Comment by Lwmte** [comment]
Also, **animcommands** are not parsed or parsed incorrectly - so there are no sounds for non-Lara animations.

**Comment by vvs-** [comment]
There are sounds for some animations: e.g. tall block in *Tomb of Qualopec* and door in *Colosseum*.

**Comment by vvs-** [comment]
There is now issue #101 in *Colosseum* while it wasn't there in the old version.

**Comment by vvs-** [comment]
In *Atlantis* rolling animation often doesn't even change orientation. Lara is still looking in the same direction as before rolling move.

**Comment by Lwmte** [comment]
Fixed in 929c1c2
