### ISSUE TITLE
Collision bugs

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#182]
Now we have highly penetrative collisions again, from underwater to roll near wall.

**Comment by vvs-** [comment]
After pulling a block, Lara now ends up inside.

**Comment by vvs-** [comment]
Also, pushing blocks doesn't work.

**Comment by vvs-** [comment]
Also, pulling blocks on a slope doesn't work either.

**Comment by Lwmte** [comment]
Should it work in the first place? There was never such feature in vanilla TRs.

**Comment by vvs-** [comment]
My mistake. It was just an optical illusion. After checking the heights I was convinced that there is no slant at all. There is some other reason that prevents it from being pulled.

**Comment by vvs-** [comment]
Also, in *City of Khamoon* running forward from `27351,14679,512,279,0,0` completely bypasses collision checks.

**Comment by vvs-** [comment]
Boulders fall through geometry. And there is such message: `Can't apply force to entity 146 - no entity, body, or entity is not kinematic!`. That's in *Temple of the Cat*.

**Comment by vvs-** [comment]
The same thing in *Jungle* just the entity is 14.

**Comment by vvs-** [comment]
Please, tell me what's the difference? When trying to do that in *Caves*:
```
setEntityPos(player,65975,61331,-2733,339,0,0)
setEntityAnim(player,88)
```
Or tapping `down` key instead of `setEntityAnim`? In the second case Lara falls through geometry.

**Comment by vvs-** [comment]
I see that when `down` key is tapped she is moved right in any case. But in `timescale` she stays on the floor while in normal case she is moved underneath.

**Comment by vvs-** [comment]
Ok, found that it depends on the camera position. Lara can stay on the floor or fall through depending on the camera angle.

**Comment by stohrendorf** [comment]
Are you saying that Lara moves to the right when you press the `down` key? And could you be more precise about the camera angle, i.e. in which circumstances does the bug appear/not appear?

**Comment by vvs-** [comment]
In this position Lara falls through:
![screenshot from 2015-07-22 17 01 23](https://cloud.githubusercontent.com/assets/5171934/8827144/805de820-3093-11e5-9330-2d28899fe5ae.png)
And in this one she stays above:
![screenshot from 2015-07-22 17 01 53](https://cloud.githubusercontent.com/assets/5171934/8827154/948d34d6-3093-11e5-8319-4c844fef66bc.png)
Yes, when I press `down` key she is *slided* to the right pretty fast.

**Comment by vvs-** [comment]
I mean, when using `setEntityAnimation` command. When I press `down` she always fall through.

**Comment by vvs-** [comment]
On the second thought, it looks like it depends not on the angle itself, but on the distance to the camera. I get inconsistent results because camera is always moving back and forth.

**Comment by vvs-** [comment]
Another possibility is that it depends on the animation frame. It's changing rapidly and affects camera movement too.

**Comment by vvs-** [comment]
It looks quite non-deterministic actually.

**Comment by vvs-** [comment]
Looking at the old version in slow motion, I see that at one point Laras' left foot is partially buried in the floor. In the new version that moment correspond to sliding Lara to the right. Looks like there was no penetration fixing during an animation in the old version or it worked differently.

**Comment by vvs-** [comment]
Could it be the reason: `FIXME: Code has been removed due to missing API feature: bt.ghostObjects[i]->setIgnoreCollisionC
heck(bt.bt_body[i], true)`?

**Comment by vvs-** [comment]
Ok. Removing Laras' ghost objects fixed the case. I believe it proves that ghost objects are broken.

**Comment by vvs-** [comment]
It requires Bullet 2.83, really.

**Comment by Lwmte** [comment]
There *is* setIgnoreCollisionCheck function in Bullet 2.83, but for some reason I can't enable it. Compiler message:

  C:\DEV\projects\OpenTomb\src\entity.cpp|49|error: no matching function for call to 'btPairCachingGhostObject::setIgnoreCollisionCheck(__gnu_cxx::__alloc_traits<std::allocator<std::unique_ptr<btPairCachingGhostObject> > >::value_type&, bool)'|

**Comment by Lwmte** [comment]
Please check if something changed!

**Comment by vvs-** [comment]
CMake project is broken now. Requires fixing it as well, so I can't build OpenTomb at the moment.

**Comment by vvs-** [comment]
Current physics is still not immune to penetration bugs. I've seen this for climb, reach (especially when jumping to columns from above) and roll states, but it's just quite rare.
