### ISSUE TITLE
Midas gold touch is broken

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#183]
It means that either item is not working or some script functions used in `midastouch_init` (entitiy_functions.lua) may be broken.

**Comment by vvs-** [comment]
But Midas touch didn't work even before the refactoring. I always was tempted to open such issue but decided against it. I thought that it was implemented incorrectly and you are planning to rewrite it anyway.

**Comment by Lwmte** [comment]
Hmmm... It always worked on my side. Only issue I had is Lara couldn't be reset after she performs turn to gold animation, but it is related to animation code.

**Comment by vvs-** [comment]
It never worked for me and also I remember that Ado Croft from TRF has the same issue.

**Comment by Lwmte** [comment]
Ok, it works, but for some reason only if Lara is in far-right corner of Midas hand sector (if you count from cave entrance).

**Comment by vvs-** [comment]
Yes, that corner works for me.

**Comment by Lwmte** [comment]
Seems the problem is midas touch entity for some reason now lacks its owner sector pointer. The condition just never met.

**Comment by vvs-** [comment]
This issue seems to be fixed sometime ago.

**Comment by Lwmte** [comment]
Ok, so it's working? (both for Lara and lead bars) If so, we can close it :)

**Comment by vvs-** [comment]
It works. But there is no gold reflection and sparks. Also, the implementation is somewhat hardcoded. But I think this issue is no more valid.

**Comment by TeslaRus** [comment]
all hardcode are inside Midas script =)

**Comment by vvs-** [comment]
Yes, I mean checking the distance and animation frame inside `onLoop`, it should be no different than any activation. But that's not important at this point.

**Comment by TeslaRus** [comment]
aha - it is hacky solution...
