### ISSUE TITLE
Use XNALara meshes

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#187]
This is a (very) long-term plan of mine that I will probably not implement this year; I just thought I'd announce it here in case anyone has comments on it.

XNALara is well established in the TR community, as well as tools for working with it. The file format is almost reasonable and allows doing a lot of things that classic TR can't, for example better shaders, better skinning and so on. A lot of custom levels are using back-ported versions of XNALara meshes already. It would be nice if there was a way to load these directly.

XNALara's file format is not without its problems; for example it has both an ASCII and a binary serialization, and the ASCII one doesn't include all values. Also, a lot of information about how to render meshes is actually hard-coded based on filenames, with hacks for custom models. Weird stuff.

I've already dealt with that for GLLara, a Mac app that does the same thing as XNALara and is compatible with it (not a rewrite, this is all custom). My plan right now:

-   Port the core file loading/writing part of GLLara to cross-platform C++
-   The configuration data is currently stored in OS X-specific PLIST files (extracted from the XNALara source code). I'd probably convert them to JSON.
-   Put it in a new library that will be an external dependency of GLLara
-   Include that library in OpenTomb as well, implement the loading. Probably just copy the shaders directly; I see no useful way of putting them into an external library.
-   Add lua functions to replace an animated model with an XNALara one while loading a map, with special mapping of the bones to each other.

I've also considered putting the configuration data into a lua script, which would work as well, but that would make it impossible for me to use the same model loading library here and in GLLara.

XNALara also allows loading OBJ files as meshes. I don't see this as a big use case, but if I go with the shared library, that would probably work, too.

Again: I'm not going to do this now, except some experimental preparation perhaps. I just want to know whether anyone has any opinions on it.

**Comment by Lwmte** [comment]
I think it's a great idea! But important thing is to do it right, so loading external meshes wouldn't be necessary. Like now, you can load a level without music and external samples, but if they do exist, engine makes use of them.

Looking even more forward, we need to think if we can use XNALara format for possible OpenTomb own level file format. Like with newGRFs in OpenTTD. In the beginning, it used pre-compiled original level files from Transport Tycoon, but eventually switched to community-developed newGRF format to keep all the new models, entity types, textures, sprites, etc.

Later we can also think about integrating hi-res textures (Tomb Raider Xtra, iOS version textures, etc.).

**Comment by cochrane** [comment]
I've decided against pursuing this further; in particular, I don't want to do the necessary changes to GLLara. If someone else wants to pick this up, they're welcome to, and I will give any assistance I can. I especially suggest looking at the machine-readable configuration data in GLLara; if there is interest I can export it to another format very easily.

But if there's nobody interested in pursuing this, then I think we could also close this issue.
