### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#188]
Right now, absolutely everything is in the main OpenTomb folder. In particular, we have:

-   folders that contain only data provided by us (e.g. shaders)
-   folders that contain only data provided by users (levels)
-   folders that can, eventually, contain both (scripts, when users install new levels)

This requires users to edit the program folder to get the app running. This is discouraged on Windows and highly discouraged on OS X. Is there a better way?

My suggestion would be to have one folder for stuff we supply, which shouldn't be visible to the user, and one folder for things the user supplies, which should be somewhere the user can and will edit (e.g. "My Documents" on Windows or similar). I'm not sure how to handle scripts, though, given that we supply them for all official levels, but we have no idea how custom levels will be handled.

Not a major issue, just something that bugs me.

**Comment by Lwmte** [comment]
I always thought that it's better to keep everything in one place, as this way you have better control on application. Contemporary software bugs me for doing the opposite - leaving its traces in system registry, Users folder, AppData folder, and whereever else. Moreover, I hate to use so-called "user folders" in system and never keep my files in them. And it's so painful to find in a such folder some leftovers of some program you've removed eons ago!

So I think it is better to use single folder for everything, at least at this stage, when we still struggling to make everything work as in classics. Later, on a pre-release or release stage, we can think of separating user data and system data.

Another problem that may come up is we have relative paths in gameflow scripts. And I can't think of any idea to make some universal rule to make OpenTomb searching for levels/scripts/etc in some generic system's user data folder. For example, on Windows it's in Users/{username}, on Mac it's in Macintosh HD/whatever (actually never learned it, although I have Mac at my workplace), and on Linux it's somewhere else.

**Comment by stohrendorf** [comment]
I can only speak for windows and linux here, but that's what I would do:
* store every *core* component in the installation dir (`%PROGRAMFILES%` on windows, `/usr/bin` and `/usr/share` on linux)
* game data path (our `data` folder) should be configurable via `config.lua`, with some sort of GUI to edit it
* and the `config.lua` should reside in `$HOME`, so that on a multi-user system all users can use the same core data, but have different configurations

**Comment by cochrane** [comment]
An approach similar to that would work well for OS X, too. Specifically:

-   The installation dir is the app bundle in OS X; literally just a folder with an extension in the filename, which is presented as one file to the user.
-   Game data path can be chosen freely.
-   config.lua would reside in ~/Library/Preferences (possibly a sub-folder), and the app would copy the default one there if it weren't present on launch.

Finding the right path for everything would be easy, we'd just need a few utility functions that would return the right paths based on the system they were compiled on.

**Comment by Yamakaky** [comment]
I approve too. I'm working on making a package for archlinux. For now, should I put all in /opt/OpenTomb ? which user should own which file ?

**Comment by cochrane** [comment]
No longer needed, references old version of the code.
