### ISSUE TITLE
Teleportation issue

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#190]
After pulling block 125 in *Palace Midas* Laras' y-coordinate was multiplied by 1k times.

**Comment by vvs-** [comment]
Also, Lara got teleported every time she tries to climb ladders or walls.

**Comment by vvs-** [comment]
Also, there are too many such cases in *Streets of Rome* when trying to use godfaces (unimplemented).

**Comment by vvs-** [comment]
Got teleported after coming up to the surface.

**Comment by vvs-** [comment]
Got teleported just going up stairs.

**Comment by stltomb** [comment]
I can now teleport just by jumping while going forward. This behavior was introduced by 584379d2b8376152f67d98d551ef12c190b2ccf5 (reverting it fixes it).

**Comment by vvs-** [comment]
It's not fixed.

**Comment by Lwmte** [comment]
In some cases, probably related to #204, as when Lara approaches switches or other objects which require position fixing, moveEntityLocal is used.

**Comment by stohrendorf** [comment]
Interestingly, it's reproducable: Stand before a wall where Lara needs to jump up to grab the edge of a floor. If you use Jump+Up+Action, it seems to work well, but if you only use Up+Action, so that she decides herself to jump up, the she gets teleported upwards.

**Comment by vvs-** [comment]
Yes, that always happens when you try to climb walls and ladders, because jump is not working there.

**Comment by vvs-** [comment]
Seems to be fixed now.

**Comment by stohrendorf** [comment]
Hopefully. I don't believe it fully yet.

**Comment by vvs-** [comment]
There already was such issue in old engine. But not on the same scale like after refactoring. Now it seems to return to the old behavior.
