### ISSUE TITLE
WAD doesn't work

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#192]
I'm getting errors like "Load_Wad: can't seek at offset 732FB58".

**Comment by Lwmte** [comment]
Very strange, I have everything working... Maybe it's again related to uppercase/lowercase issue?

**Comment by vvs-** [comment]
It's a librarary problem. I extracted exactly the same data from `cdaudio.wav` and they were played just fine in ffmpeg. But sndfile refused to play it for some reason.

**Comment by Lwmte** [comment]
Probably seek is done wrong. What's the number of track you're trying to play?

**Comment by vvs-** [comment]
Yes, the seek is wrong. My experiments show that the current position is different for buffered streams and unbuffered files. I have 1192 bytes difference. So, when you convert stream to file descriptor you automatically get wrong offset.

**Comment by vvs-** [comment]
Adding `setbuf(wad_file, NULL)` fixed the problem.

**Comment by Lwmte** [comment]
This is strange, pointer should reset to zero, as I rewind the wad before extracting wave header.

**Comment by vvs-** [comment]
Just after `open`.

**Comment by vvs-** [comment]
> This is strange, pointer should reset to zero, as I rewind the wad before extracting wave header.

No, because you put `fseek(wad_file, offset, 0)` there.

**Comment by Lwmte** [comment]
Ugh, I thought it will restart from the beginning! :smile: Perhaps I got argument meaning wrong.
I will add a patch, however, I don't understand what `setbuf` function actually does.

**Comment by vvs-** [comment]
It just turns off buffering for that stream. Looks like on Windows it's by default.
