### ISSUE TITLE
Missing block

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#194]
Entity 27 is missing in *Streets of Rome*. Broken by 6e71131361b3867a51bedbc3b0ffcf27d1bfd196.

**Comment by Lwmte** [comment]
Are you sure it's missing? If there is a texture on the floor in place of block, then everything is normal. By default raising block is not active, it's only raised when activated.

**Comment by vvs-** [comment]
Ok, I don't have Windows to test it. So, I didn't remember that it wasn't implemented before.

**Comment by Lwmte** [comment]
I've implemented it when we already had ongoing hell with refactoring, so possibly that's why you didn't notice it! :smile:

**Comment by vvs-** [comment]
Yea, unfortunately you are right :disappointed:
