### ISSUE TITLE
Climbing down is broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#196]
That happened while trying to fall back holding the action key. Here's a screenshot:
![screenshot from 2015-07-21 19 30 50](https://cloud.githubusercontent.com/assets/5171934/8806406/3f7f1c8e-2fdf-11e5-9fdb-16953a8f3775.png)

**Comment by vvs-** [comment]
I believe it's related to #73 and maybe #90, but with a new twist caused by the code refactoring.

**Comment by Lwmte** [comment]
I also encountered something similar in Caves. When I was testing jumps and Lara was nearby the 2-click block, she suddenly moved inside the block "smoothly", and stayed there. Reminds me of classics corner bugs (however, the nature should be completely different, as it's not floordata collision).

I wasn't able to reproduce this bug afterwards.

**Comment by vvs-** [comment]
Some bugs depend on exact position and angle and are very hard to reproduce. But this one is perfectly reproducible.

**Comment by vvs-** [comment]
This particular position is special because it has several parallel planes which engine considers grabbable. Some of them are false crevices which are probably created by bugs in Bullet. It makes it very hard to climb down or up. In the old engine Lara couldn't grab the ledge and fell down instead.

**Comment by vvs-** [comment]
Probably related to #73.

**Comment by stltomb** [comment]
After 840e83331bc4c3c0574ae8f78f2dc0846bda8476 I can no longer reproduce this. Lara reverted to the old behavior (as described by @vvs-, see above).

**Comment by Lwmte** [comment]
Confirmed, now Lara just falls down. Again, great job on fixing this! Thanks.
Now we'll leave it open just to fix old behaviour too! :smile:

**Comment by vvs-** [comment]
It happens again.

**Comment by Lwmte** [comment]
Hmmm... Not for me. I still get Lara falling down through the crevice.

To fix this, I suppose we must modify "climb sensor" behaviour, because it seems it falsely identifies double-edge as unclimbable.
