### ISSUE TITLE
Climbing animation bug

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#211]
In *Caves* at position `67873,50086,673,0,0,0` press `action` and `up` and immediately release `up`. After Lara grabs the ledge release `action`. You should see a wrong animation.

**Comment by stltomb** [comment]
After a quick look to see what touched _anim_state_control.cpp_ last, I found out that if you revert 56f16d702cb7b43d480d063fb5670a4482467d59, the bug disappears.

**Comment by vvs-** [comment]
Yes, that commit fixed one climbing bug and introduced another.

**Comment by Lwmte** [comment]
Ok, this "after climb fix" business is too tricky for me, I'll leave it to TeslaRus!

**Comment by vvs-** [comment]
I'd say that all the current penetration fix business is too tricky and doesn't work properly. Of course, the refactoring didn't make it any better.

**Comment by stltomb** [comment]
Can any of you still reproduce the issue? I can't see the wrong animation anymore.

**Comment by Lwmte** [comment]
I have removed that "fix" I introduced some time ago, so I guess it may be considered "fixed" (although we get nasty "tear" in Lara position after climbing up).

**Comment by vvs-** [comment]
The original problem is solved.
