### ISSUE TITLE
Multiple triggering of a locked entity

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#215]
In *St. Francis' Folly* door 1 is triggered multiple times despite being locked.

**Comment by Lwmte** [comment]
I wonder if it is related to my "fix" of one-shot triggers... :disappointed:

**Comment by vvs-** [comment]
Then we'll need to fix a "fix".

**Comment by vvs-** [comment]
Yes, it was broken in b4ed1112c200197f5ab299b4cbbe1913adc066e5. My solution in #33 still works flawlessly.

**Comment by Lwmte** [comment]
Have you tested TR2+ one-shot entities with this patch?

**Comment by Lwmte** [comment]
Please test current revision.

I have specified completely different workflow for TR1 one-shot triggers, ignoring this flag for switches (and, generally, triggers), and left it only for sole purpose of blocking ANTI-triggers. Also I've modified antitrigger routine a bit, allowing it to copy its own one-shot flag into entity, which is the normal TR2+ behaviour.

Believe me, original triggering code is SO MESSED UP, even in initial (TR1) version... These horrible people who did that, they only did it to conserve few bytes? And I don't even want to mention how much more messed up is our trigger script generator because of this...

**Comment by vvs-** [comment]
I've just tested the original TR2. There is no difference in behavior with TR1 whatsoever in regard to one-shot switches. The locked switches can be pulled indefinitely, only entities are locked.

**Comment by Lwmte** [comment]
Indeed, the setup is the same! Moreover... I have checked TR3. And *they also changed one-shot behaviour there!* I hate these people. The setup in TR3 is the same as it was when I programmed first version of one-shot functionality - it locks even unactivated entity with uncomplete mask, if one-shot flag is set. In the name of god... Now what? I need to make *three versions* of trigger pipeline?

Oh well. I guess I will just leave it as it is, until more bugs are surfaced. Because I can't imagine sane level designer who makes complementary trigger setup with possibility of accidental deadlock. However, Phil Campbell can very well do this in the same manner he did those one-way portals. Freak. :smile:

**Comment by vvs-** [comment]
Present version works incorrectly in both TR1 and TR2. It locks TR2 switches, so it's impossible to use it twice, and it doesn't lock entities in TR1, so it's possible to change the state of a locked entities multiple times.

**Comment by Lwmte** [comment]
Look, but how can I *unlock* the door in St. Francis Folly, if previously I have *locked* it with the same switch? What does it mean? I will fix it for TR2, no worries.

Perhaps some other geek should decompile all *TestTriggers* function variations for all games and make it work as it should. I'm seriously bored and this is the last time I'm fixing it.

**Comment by Lwmte** [comment]
I mean, why the hell I shouldn't be able to change state of locked entities, if this is exactly what happens in that Folly room with deadlock switch?

**Comment by Lwmte** [comment]
I have one idea, though. Maybe the only bad guy here is trigger's own one-shot flag? I mean, it can override entity's own one-shot flag and change its state?

**Comment by vvs-** [comment]
> this is exactly what happens in that Folly room with deadlock switch

No, it's not. The door is locked and can't be closed after opening it. And my patch does exactly that and works correctly in both TR1 and TR2.

**Comment by Lwmte** [comment]
But I can open and close the door with that switch, is it right?

**Comment by vvs-** [comment]
This is so in OpenTomb, but you can't close the door second time after opening it with the switch in original TR1.

**Comment by Lwmte** [comment]
Ok then, looks like I got it... Just one condition to be removed.

**Comment by Lwmte** [comment]
Another problem is, most likely your patch won't work for pre-activated doors with "inverted" state. Like if I set entity mask to 11111 in editor, and it will be active by default, but engine treats it as *deactivated* in this case.

**Comment by vvs-** [comment]
If you tell me where to look for such a setup then I'll be able to test it and report my findings. Right now I've tested it in the whole TR1/UB and just one level in TR2.

**Comment by Lwmte** [comment]
Most easy way is to make test level in Dxtre3d. Problem is, I can't launch TR1 on my PC, except ATI win32 version, which is not cracked and requires a CD. I will create a level and upload it for you, so you can test it.

But I guess if TR2 setup is the same, it should work in similar manner.

**Comment by Lwmte** [comment]
Ok. Seems to be working! Although I'm sure something may still be wrong.

**Comment by vvs-** [comment]
There is no need to crack it. The original BIN/CUE image works perfectly in dosbox. That's how I test it, because it doesn't even work in Windows unless you use a Glide emulator which is buggy.

**Comment by Lwmte** [comment]
Yeah, that's the point, so to replace some level file, I need to inject it into ISO.

**Comment by vvs-** [comment]
That's doable too. I vaguely remember that the copy protection is based on ISO label or something like that. That information should be on Internet somewhere. Also, there's a cracked dos version of the executable, albeit without 3D acceleration. But I always test it that way. Not very nice but, oh well...

**Comment by Lwmte** [comment]
I actually tried to crack that ATI version, but it always throws an error if I point it to my TR1 folder instead of CD.

**Comment by vvs-** [comment]
Forget about 3D accelerated TR1. Why do you need that for a test? Also, you could use a Glide emulator if you insist.

**Comment by Lwmte** [comment]
Just because ATI version is Win32 binary which can be loaded into OllyDbg! :stuck_out_tongue_winking_eye:

**Comment by vvs-** [comment]
And do you need that to just test a level in the original engine? You will see how it works by your eyes. And you can always dissect the level using other means. I always use OpenTomb for that because I have full sources and even can patch it :smile:

**Comment by vvs-** [comment]
BTW, I can just patch entity dumping so it could dump the mask with it. Good idea, I'll try it tomorrow.

**Comment by Lwmte** [comment]
Ok then, also please test latest commit. That doomed Folly door now activates just twice and then locks itself.
In the meantime, I will write some basic flipeffect script support (as you probably noticed...)

**Comment by vvs-** [comment]
Ok.

**Comment by vvs-** [comment]
So far so good. I'll close this and will look for preactivated entities to test tomorrow.

**Comment by Lwmte** [comment]
Great! And here is the test level for you: http://trep.trlevel.de/temp/level1.7z

First (blue) tile is antitrigger. Second (dark yellow) tile is ordinary trigger. Third (beige) tile is switch trigger with only once flag set. Fourth (black) tile is switch trigger with only once flag AND timer set to 3.

**Comment by vvs-** [comment]
I don't want to contradict myself but I should say that we need an editor :stuck_out_tongue: Or at least some export plugin for Blender.

**Comment by vvs-** [comment]
Integrating it into the disc image was a no-brainer. I already found two bugs in OpenTomb and one in the original engine using that cute test level.
