### ISSUE TITLE
Missing cogs in Lost Valley

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#216]
![screenshot from 2015-07-24 15 53 44](https://cloud.githubusercontent.com/assets/5171934/8874783/d89dbb66-321c-11e5-8f76-553e7114f287.png)

**Comment by stltomb** [comment]
While this is a valid bug, I don't believe it was introduced during refactoring - the same bug is present in the version before it took place (I'm using cf50613b62876446c2fde1381fba9d00ba9c5b52).
If you pull the lever, you can see the first three wheels on the left turning.

**Comment by vvs-** [comment]
You are right. I didn't test the last version before refactoring and was assuming that it worked just like in the last version I've tested. Apparently this bug was introduced somewhere in between.

**Comment by vvs-** [comment]
The reason is that all animations are disabled until activated. If I remove the line which disables them they appeared again:
![screenshot from 2015-07-26 15 57 13](https://cloud.githubusercontent.com/assets/5171934/8893991/034ac910-33af-11e5-8c1c-f061ced36570.png)

**Comment by Lwmte** [comment]
Sorry, I have introduced enabling/disabling of animatings purely for TR3/4 compatibility purposes, but it seems it broke lots of other animatings. I will revert it now, and think about more decent approach.

**Comment by vvs-** [comment]
The scripts are too old and need back porting from backup.
