### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#218]
There is no more BGM in *St. Francis' Folly*. At least no music after activating door 1.

**Comment by Lwmte** [comment]
Was there any BGM? I don, t clearly remember. this bug may be introduced by recent patch, where I forced all triggered BGMs to be ignored. This is the way it originally worked in PC version.

**Comment by vvs-** [comment]
Yes, there was *Danger* theme played after entering door 1.

**Comment by vvs-** [comment]
And yes, there was no music played in PC version. But I find the PSX music much more appealing.

**Comment by vvs-** [comment]
Fixed in 742460d2870611ca91f2e72cc55a7fa075be2c16.
