### ISSUE TITLE
Crashing when loading some levels.

### ISSUE THREAD

**Issue by Gh0stblade** [opentomb/OpenTomb#22]
I have noticed frequent crashes when loading certain levels. Not sure what is causing it, seems to be isolated.

**Comment by Lwmte** [comment]
I had some crashes with some TR4 levels, but don't remember exact names or level numbers... Do you have any examples?

**Comment by Gh0stblade** [comment]
I'm not so sure... I've had it happen when jumping to levels from any game randomly. It's not a specific level it just seems to happen and I cannot pinpoint why since it's very random.

**Comment by Lwmte** [comment]
Please check if you still have crashes, I have fixed two bugs which led to crash (see commits 7f78ef1 and  03ac1c7).

**Comment by Gh0stblade** [comment]
No more crashes here. I'm guessing it's fixed. Thank you, closing this!
