### ISSUE TITLE
Collisions with spikes aren't ghost

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#221]
Lara supposed to walk through spikes.

**Comment by Lwmte** [comment]
She did that. Some time ago.

**Comment by vvs-** [comment]
I noticed that some features introduced lately in the old engine were reverted after refactoring. My guess is that Steffen forgot to merge them or even missed them completely. That means that some recent features should be added again.

**Comment by stohrendorf** [comment]
I tried my best at keeping the master features when merging, yet it became very difficult in the end as I said. If I accidentally reverted some features when resolving merge conflicts, I'm sorry.

**Comment by vvs-** [comment]
There are no new critical bugs left. If some features were accidentally reverted there remained only one or two of them. I think we have all of them documented and the old code base is still there for comparison. The engine is already better than the old one in several aspects.

**Comment by Lwmte** [comment]
Actually, it seems like my mistake. Lara indeed runs through the spikes perfectly, but she stops when walking around them, This is exactly what happened in pre-refactored version. So this is an old bug, mostly related to collision detection.

Only one critical bug which is left is occasional crashes, so currently we're cool! :sunglasses:

**Comment by vvs-** [comment]
> Only one critical bug which is left is occasional crashes

That single bug was always here from the beginning of time :stuck_out_tongue:

**Comment by vvs-** [comment]
> Lara indeed runs through the spikes perfectly, but she stops when walking around them

I definitely remember that she was able to walk. If that was broken in some commits just before the refactoring then we need to find and fix or revert them. What makes it more difficult then necessary is the habit to put unrelated things into a single commit without even mentioning it. Since the refactoring things are changing and breaking so fast that I need different workarounds for every old commit, not saying that many of them don't even compile or work. That makes bisecting almost impossible.

**Comment by vvs-** [comment]
I tested it with the old engine and indeed she walks through spikes. That bug was introduced after refactoring but it could be caused by the new changes in scripts or engine. There is actually little point in separating the development by these milestones. I think we should consider to close the C++ refactoring and declare the transition as complete.

**Comment by Lwmte** [comment]
I am completely sure that Lara can't walk through spikes in my old project directory. Perhaps, I have much more older version there, before ghost entity collision was introduced.

**Comment by stltomb** [comment]
I'm using cf50613b62876446c2fde1381fba9d00ba9c5b52 - this is the revision just before the refactoring. You can definitely walk through spikes in this one.
