### ISSUE TITLE
Tap backwards goes a bit too far

### ISSUE THREAD

**Issue by nhfl** [opentomb/OpenTomb#222]
If Lara stands on a block and you do make her do one step back she moves a little to far and falls off the block. Example: TR1 gym jump number three.

**Comment by vvs-** [comment]
Yes, that's a known incompatibility.

**Comment by stohrendorf** [comment]
Maybe found the issue: In `read_mixfloat`, maybe `sign_int` must be *signed*. For the "short jump back" animation, `accel` is (unsigned) 10*4.66667, and then on the final frame it's set to 42 from the `speed`, down from the accumulated speed 46.6667 (or exactly 42 on the 9th step). If I make the `sign_int` signed, it becomes 3.66665, with a final accumulated speed of 36.6665 (or 32.9999 on the 9th frame). In the signed case, Lara doesn't fall down when jumping backwards on a block, and keeps calmly staying on the edge.

**Comment by stohrendorf** [comment]
Setting `DEFAULT_CHARACTER_SPEED_MULT` to 30 instead of 31.5 seems to fix this problem, as well as #38.

**Comment by stohrendorf** [comment]
Actually part of #38.
