### ISSUE TITLE
LEVEL1.lua not working anymore

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#23]
Something happened after #20. Lara now collides with plants all over the place.

**Comment by Lwmte** [comment]
Seems that it has something to do with recent Lua error handles, I'll check it up soon. Thanks!

**Comment by Lwmte** [comment]
I have repaired a function which loaded static mesh flags, but as long as original static mesh structure already contained a flag for static mesh "solid" or "ghost" state, I will soon make it work like in original, and remove this redundant level script functionality.
