### ISSUE TITLE
Bullet doesn't support zero collision margin.

### ISSUE THREAD

**Issue by stohrendorf** [opentomb/OpenTomb#230]
See subject, found in the bullet forums. I haven't seen any `setMargin` calls in the code, and I assume that this is the cause for nearly every collision bug.

**Comment by Lwmte** [comment]
Well, I did quick search on Google and first result was this: http://www.youtube.com/watch?v=BGAwRKPlpCw&hd=1

What is exactly collision margins? You mean it's a "border" around actual collision mesh that is being checked? But for this purpose, we can just do SetLocalScaling on target body. But it will break much more things than it will fix (IMO). 

However, I'm completely dumb in physics engines, so I'm going to see that video right now! :smile:

**Comment by stohrendorf** [comment]
The point is, bullet doesn't support zero margins. And I don't understand what would break if there is a margin that's relatively small.

**Comment by Lwmte** [comment]
You can actually set even larger margin. We didn't normalize metering for Bullet, i.e. 1024.0 Bullet units is roughly 1 meter, so I guess you may set a margin around 16-32.

**Comment by Lwmte** [comment]
I tried to set larger margin (not even 32 or 16, but 8), and got funny ragdoll bugs - now Lara body behaves too stiff! So I guess we should indeed use *very low* margin values, or at least specify different margins for different types of bodies.

For actual rigid bodies (rooms, entity bodies, static meshes), I think margin should be really low, while we can surely use larger values for test spheres and ghosts.

**Comment by stohrendorf** [comment]
All margins are set by using a configurable central constant now, I consider this closed.
