### ISSUE TITLE
Switches are causing crashes

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#249]
Load TR3 Jungle level and try to walkthrough it as usual, sliding down the dirt mountain and going right to the first switch which opens grated door to spiky wall trap. Engine will crash when Lara will approach a switch.

Not sure if I introduced it with my latest snake script, cause I didn't do anything with anything else.

**Comment by Lwmte** [comment]
Also got crash at switch in Tomb of Qualopec.

**Comment by vvs-** [comment]
I can't reproduce it.

**Comment by Lwmte** [comment]
It crashes right after you've pressed action nearby the switch.

**Comment by vvs-** [comment]
Nope. No crashes for me.

**Comment by Gh0stblade** [comment]
Is this on the latest build? I've not checked it out yet, but on my current build there are no crashes.

**Comment by Lwmte** [comment]
You mean latest release? No, it's only on recent source code revisions (it happened for me after recent huge merges).
Seems that ` OBB_OBB_Test ` is now failing.

**Comment by Gh0stblade** [comment]
Hmm I haven't built the latest changes, that were added the past 1/2 days. So if it's crashing it has to be something recent.

**Comment by Lwmte** [comment]
Seems that after full engine rebuild it's now gone. However, my old "Lara can't turn" bug is now worsened! :laughing:
