### ISSUE TITLE
Reverb is gone

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#250]
I don't hear any effects except underwater filter.

**Comment by Lwmte** [comment]
P.S.: It seems that reverb is only working in the first room where camera is placed at level start-up. Then it just won't update.

**Comment by Lwmte** [comment]
Global reverb is not working in TR1, while in TR2 it works.

**Comment by Lwmte** [comment]
Testing it a bit more... Some rooms in TR4 do have a reverb, but some are not.

**Comment by vvs-** [comment]
I have a reverberation in *Lara's House* (TR3).

**Comment by Lwmte** [comment]
Ok, seems it is false alarm! :sleeping:
