### ISSUE TITLE
CXXify and decoupling of VT loader

### ISSUE THREAD

**Issue by stohrendorf** [opentomb/OpenTomb#256]
I remember that someone said that the VT loader shouldn't be changed, as it is planned to be made a library of its own. I'd really like to refactor this library to get rid of plain C memory management (memalloc, memcpy, etc.) and to make it behave as a library, so that it can be easily moved out of OpenTomb to an own repository. The question is, may I do that? If not, I'm fine.

**Comment by vvs-** [comment]
If I understand it correctly it should be completely rewritten not just refactored. So, you are going to waste your time working on an obsolete stuff.

**Comment by stohrendorf** [comment]
Then I'm fine with keeping it untouched. By the way, who will rewrite it then? The VT sources I found on icculus.org are back from 2002, and I haven't found other sources, so I presume someone in OpenTomb would be responsible for that.

**Comment by Lwmte** [comment]
VT was originally written by @fschulze, and while being very flawed in its original form, it provided us lots of useful info which is now also integrated to TRosettaStone 3. I don't think he'll want to rewrite it, as whole thing is indeed back from 2002! :smile: 

It was me who said that VT loader must be made as separate library. The whole idea comes from conversation with @xythobuz (https://github.com/xythobuz/), author of recent OpenRaider fork. The thing is, VT is only one reasonable resource loader for *all* PC TR resources, so it can be used for other projects as well (that was the whole point of our conversation, as Thomas didn't want to participate in OpenTomb development, but favored VT rewriting).

Another point of making VT separate library is there is pending multi-platform resource loading support. @Gh0stblade already wrote support for Dreamcast levels, I suppose someone will come up with PSX loading as well. Also, eventually @godmodder will program his level editor which will support original file format... So here we come to a dilemma where we should make each level loader as a "plugin" or "library". That's what I meant when I told that VT must be made self-contained.

Jack from TRF showed some interest in modifying VT, but it seems he primarily uses it for his own purposes, so I wouldn't wait news from him soon. 

I don't see a point in rewriting something that already works just in sake of rewriting, and VT works pretty well (except that issue with heap corruption which I never encountered - at least everything that's crashing the engine happens on the stage of VT->OpenTomb resource converting). Unless you can make it more efficient, fast and simple within a reasonable timespan, of course - if you sure you can do that, then I'm fine with rewriting it.

**Comment by vvs-** [comment]
It was @Gh0stblade who said that he wants to rewrite it.

**Comment by stohrendorf** [comment]
OK, as I said, I'm fine, although I'd like to at least convert manual memory management in `TR_Vector` to some more CXX-like style.

**Comment by Lwmte** [comment]
Yes, check out @Gh0stBlade fork with Dreamcast level support as well. It was done before refactoring, so it may be incompatible with current version: https://github.com/Gh0stblade/OpenTomb/tree/Platform_Tests_1

Let's wait for @Gh0stblade reply, would he still want to make some additions or changes to VT. If he has no plans on it anymore, I think @stohrendorf may take this task.

**Comment by Gh0stblade** [comment]
I hate VTLoader, the code is simply not organised. So much stuff could have been simplified imo and there's too much unorganised and messy code slapped about. A new loader should be written specifically for OpenTomb that's not in it's own folder, from scratch that consists of proper version management and multi-platform asset management. I wanted to do this, but as the style of the code is based around usage of vectors and all kinds of std:: things which I'm unfamiliar with perhaps it's best @stohrendorf writes a new one?  :+1: I'm super interested at adding support for loading from the other games, I just hate VTLoader so I refuse to add anything at this point. 

What do you think? I hope VTLoader is gone forever.

**Comment by stohrendorf** [comment]
I'm against writing that thing from scratch, because it works and it may contain *undocumented* things. As I have some experience with "modernizing" (or porting something to another framework), I'd suggest two steps:
1. Modernize the core language usage, i.e. make it look like it has been recently written as a working prototype.
2. Then do the macro-refactoring, i.e. move code around, split up classes, do an interface abstraction, etc.

All in all, I suggest some sort of step-by-step rewrite, consisting of multiple refactorings, where each step can be tested. Otherwise I fear there would be a new loader that doesn't work at all.

**Comment by Lwmte** [comment]
Old VT loader was based on first TRosettaStone revision. Even class and variable names, and order of structure appearance resemble that of TRosettaStone 1.0. But since TR4 and TR5 weren't mentioned in it, there were big unknowns in VT related to them. Especially TR5 loader, which was uncomplete and broken - TeslaRus fixed it after lots of headache.

In current state, VT is a practical representation of TRS3, so only thing you should be careful with is correct parsing of all fields and structures. You may also pay attention to "fillers" and "separators" used primarily in TR4 and TR5.

**Comment by Gh0stblade** [comment]
There is a small mistake in VTLoader which I'll be fixing shortly, just reading some ASM @_@

**Comment by stohrendorf** [comment]
There are still a few questions open:
1. Should the original loader be refactored, or should a new one be created?
2. Who should do that?

**Comment by Lwmte** [comment]
1. I still opt for decoupling it and not tying it with OpenTomb. There is no point in merging loader into OpenTomb, because majority of native TR structures still have to be re-parsed to suit our needs. Hence, I also opt for macro-refactoring, not for rewriting - because in latter case we'll most likely create some kind of monstrous hybrid of resource.cpp and VT. It's not right.
2. As @Gh0stblade said he won't do anything with it at current state, I think it's you! :yum:

**Comment by stohrendorf** [comment]
I think if I fail with this, the last remnants of my reputation will be lost forever in some forgotten tomb...

@Gh0stblade Can you tell which parts you are touching, so that I can delay work on that parts until you have done your changes?

**Comment by Gh0stblade** [comment]
I am going to be modifying tr_types.h, l_common.cpp, l_tr1.cpp. They're only small alterations though nothing that should affect refactoring.

**Comment by stohrendorf** [comment]
Then I'll start. I have coffee, cigarettes, and food for tonight ;)

**Comment by Lwmte** [comment]
Good luck to you then! Take care with that beast! :skull:

**Comment by fschulze** [comment]
Hi!

On 8 Aug 2015, at 20:19, Anatoly Grishin wrote:

> VT was originally written by @fschulze, and while being very flawed in 
> its original form, it provided us lots of useful info which is now 
> also integrated to TRosettaStone 3. I don't think he'll want to 
> rewrite it, as whole thing is indeed back from 2002! :smile:

Just wanted to say, that it's cool someone is working on this stuff. 
It's very likely my stuff from back then is horrible. It was my first 
step into C++ and mostly my last :) All info in there is from 
TRosettaStone and other documents available in that timeframe (I still 
have it all somewhere). Very little if anything at all was added or 
fixed by me, I can't remember to be honest.

I most likely won't have time to work on anything, but I'm curious where 
this is gonna lead.

All the best,
Florian Schulze

**Comment by stohrendorf** [comment]
The branch is up: https://github.com/opentomb/OpenTomb/tree/vt-loader-refactoring

**Comment by Lwmte** [comment]
Hi, Florian!
Nice that you're following the development of our project! :+1: 
Original VT loader was indeed a good basis for resource loading into our engine, as it served its purpose for almost 3 years now. But I guess time has come to modernize it! :wink: 

Anyway, thank you very much for your work!
