### ISSUE TITLE
Excessive fuse

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#259]
There is an excessive fuse in _Natla's Mines_ before a conveyor belt. It shouldn't be there until a conveyor is turned on.

**Comment by Lwmte** [comment]
I believe the reason is we don't currently have functionality for *invisible* item flag. This flag, along with *clear body* flag, was kept in originals along with activation mask and only once flag in same 8-bit bitfield.

**Comment by vvs-** [comment]
Perhaps, it is related to #93 then?

**Comment by Lwmte** [comment]
Oh yes, you are perfectly right! Boat has *invisible* flag set, as I checked it with FexInspect.

Have you just guessed it, or analyzed flag structure for yourself? I'm asking because I still confuse "clear body" and "invisible" flag placement.

**Comment by vvs-** [comment]
I never used any unofficial tools. First of all I don't use Windows. There is everything I need in OpenTomb, except editor :disappointed:

**Comment by Lwmte** [comment]
You can always use Wine! ;)
FexInspect is really cool utility. You can easily analyze level structure with it, including triggers, FloorDara layout, entity positions, light positions, etc. I'd highly recommend it to anyone who's trying to debug original levels.

FexInspect and Wadmerger are two main utilities which I use to analyze original TR data. Without them, the progress on engine development would be MUCH slower.

**Comment by vvs-** [comment]
> You can always use Wine! ;)

Well, it's fat and buggy.

Nevertheless, I think you are right. I'll eventually try to setup Wine for this utilities and most important for editor.

**Comment by vvs-** [comment]
Also, pistols in room 94 have invisible flag set.

**Comment by vvs-** [comment]
There are many invisible entities in TR1, e.g. falling ceiling or movable blocks over Thor room. After implementing invisible flag parsing these movable blocks are not activated in Lua script and remain invisible.
