### ISSUE TITLE
Compilation fails on Debian Jessie 64 bits

### ISSUE THREAD

**Issue by ABelliqueux** [opentomb/OpenTomb#271]
Hi there,  

Trying to compile master on GNU/Linux Debian 8 Jessie 64bits here.

When following step 8 instructions in README.md, the build process ends with an error : 

[  2%] Building CXX object CMakeFiles/OpenTomb.dir/src/gameflow.cpp.o
In file included from /usr/include/bullet/btBulletDynamicsCommon.h:36:0,
                 from /home/ABelliqueux/build/OpenTomb/src/engine.h:5,
                 from /home/ABelliqueux/build/OpenTomb/src/character_controller.h:13,
                 from /home/ABelliqueux/build/OpenTomb/src/gui.h:3,
                 from /home/ABelliqueux/build/OpenTomb/src/console.h:7,
                 from /home/ABelliqueux/build/OpenTomb/src/gameflow.cpp:11:
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:28: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                            ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:42: warning: unused parameter ‘value’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                          ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:61: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                                             ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:32: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:49: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                                 ^
In file included from /home/ABelliqueux/build/OpenTomb/src/character_controller.h:7:0,
                 from /home/ABelliqueux/build/OpenTomb/src/gui.h:3,
                 from /home/ABelliqueux/build/OpenTomb/src/console.h:7,
                 from /home/ABelliqueux/build/OpenTomb/src/gameflow.cpp:11:
/usr/include/bullet/LinearMath/btScalar.h:337:14: warning: ‘btInfinityMask’ defined but not used [-Wunused-variable]
  static  int btInfinityMask = 0x7F800000;
              ^
[  4%] Building CXX object CMakeFiles/OpenTomb.dir/src/main_SDL.cpp.o
In file included from /usr/include/bullet/btBulletDynamicsCommon.h:36:0,
                 from /home/ABelliqueux/build/OpenTomb/src/engine.h:5,
                 from /home/ABelliqueux/build/OpenTomb/src/main_SDL.cpp:4:
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:28: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                            ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:42: warning: unused parameter ‘value’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                          ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:61: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                                             ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:32: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:49: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                                 ^
In file included from /usr/include/bullet/LinearMath/btVector3.h:21:0,
                 from /usr/include/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h:80,
                 from /usr/include/bullet/btBulletCollisionCommon.h:22,
                 from /usr/include/bullet/btBulletDynamicsCommon.h:20,
                 from /home/ABelliqueux/build/OpenTomb/src/engine.h:5,
                 from /home/ABelliqueux/build/OpenTomb/src/main_SDL.cpp:4:
/usr/include/bullet/LinearMath/btScalar.h:337:14: warning: ‘btInfinityMask’ defined but not used [-Wunused-variable]
  static  int btInfinityMask = 0x7F800000;
              ^
[  6%] Building CXX object CMakeFiles/OpenTomb.dir/src/hair.cpp.o
In file included from /usr/include/bullet/btBulletDynamicsCommon.h:36:0,
                 from /home/ABelliqueux/build/OpenTomb/src/engine.h:5,
                 from /home/ABelliqueux/build/OpenTomb/src/character_controller.h:13,
                 from /home/ABelliqueux/build/OpenTomb/src/hair.h:9,
                 from /home/ABelliqueux/build/OpenTomb/src/hair.cpp:1:
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:28: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                            ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:42: warning: unused parameter ‘value’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                          ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:61: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                                             ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:32: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:49: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                                 ^
In file included from /home/ABelliqueux/build/OpenTomb/src/hair.h:5:0,
                 from /home/ABelliqueux/build/OpenTomb/src/hair.cpp:1:
/usr/include/bullet/LinearMath/btScalar.h:337:14: warning: ‘btInfinityMask’ defined but not used [-Wunused-variable]
  static  int btInfinityMask = 0x7F800000;
              ^
[  8%] Building CXX object CMakeFiles/OpenTomb.dir/src/bsp_tree.cpp.o
In file included from /home/ABelliqueux/build/OpenTomb/src/vmath.h:5:0,
                 from /home/ABelliqueux/build/OpenTomb/src/bsp_tree.h:6,
                 from /home/ABelliqueux/build/OpenTomb/src/bsp_tree.cpp:1:
/usr/include/bullet/LinearMath/btScalar.h:337:14: warning: ‘btInfinityMask’ defined but not used [-Wunused-variable]
  static  int btInfinityMask = 0x7F800000;
              ^
[ 11%] Building CXX object CMakeFiles/OpenTomb.dir/src/entity.cpp.o
In file included from /usr/include/bullet/btBulletDynamicsCommon.h:36:0,
                 from /home/ABelliqueux/build/OpenTomb/src/entity.cpp:7:
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:28: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                            ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:42: warning: unused parameter ‘value’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                          ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:61: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                                             ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:32: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:49: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                                 ^
/home/ABelliqueux/build/OpenTomb/src/entity.cpp: In member function ‘void Entity::createGhosts()’:
/home/ABelliqueux/build/OpenTomb/src/entity.cpp:44:35: error: ‘class btPairCachingGhostObject’ has no member named ‘setIgnoreCollisionCheck’
         m_bt.ghostObjects.back()->setIgnoreCollisionCheck(m_bt.bt_body[i].get(), true);
                                   ^
In file included from /usr/include/bullet/LinearMath/btVector3.h:21:0,
                 from /home/ABelliqueux/build/OpenTomb/src/entity.h:6,
                 from /home/ABelliqueux/build/OpenTomb/src/entity.cpp:1:
/usr/include/bullet/LinearMath/btScalar.h: At global scope:
/usr/include/bullet/LinearMath/btScalar.h:337:14: warning: ‘btInfinityMask’ defined but not used [-Wunused-variable]
  static  int btInfinityMask = 0x7F800000;
              ^
CMakeFiles/OpenTomb.dir/build.make:146: recipe for target 'CMakeFiles/OpenTomb.dir/src/entity.cpp.o' failed
make[2]: *** [CMakeFiles/OpenTomb.dir/src/entity.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/OpenTomb.dir/all' failed
make[1]: *** [CMakeFiles/OpenTomb.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

Any idea what's wrong ?

I saw the NB about "-std=gnu++11" but don't know where to put this flag.

**Comment by ablepharus** [comment]
My guess is, you have bullet 2.82 but OpenTomb depends on 2.83

Am 13.08.2015 um 17:11 schrieb Arthus Belliqueux:

**Comment by vvs-** [comment]
> error: ‘class btPairCachingGhostObject’ has no member named ‘setIgnoreCollisionCheck’

Yes, that's obvious. The requirement for Bullet version is hard.

**Comment by ABelliqueux** [comment]
Hi, 

Thanks for this information. I successfully installed a newer version from stretch, but realised to my dismay that some libraries are not bleeding edge enough on Debian in order to tun OpenTomb.

Here are the libraries you have to install from Stretch :

libvorbis 1.3.5 
Bullet 2.83
Lua 5.3.1
OpenAL Soft 1.16.0 
SDL 2.0.3

Unfortunately, GLEW 1.12.0 is only available from experimental, which means you have to update a critical libraries (libc6 2.20) to an unstable/rc-buggy version and potentially ruin your system.

I'm closing this issue as this is resolved.
