### ISSUE TITLE
Lua print function prints just the first item

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#277]
It wasn't that way before refactoring. The print function used to print all items.

**Comment by stohrendorf** [comment]
I can't see any error in `ScriptEngine::print`.

**Comment by vvs-** [comment]
Try `print` with any Lua function which returns more than one item.

**Comment by stohrendorf** [comment]
Did it by putting this snippet into `autoexec.lua`:
```lua
function fff()
return "a", "b", "c"
end

print(fff())
```

All items were printed.

**Comment by vvs-** [comment]
Try it with `getEntityTriggerLayout`. It doesn't work properly.
