### ISSUE TITLE
Tomb Raider 4  - Lost Library Crash

### ISSUE THREAD

**Issue by Gh0stblade** [opentomb/OpenTomb#283]
This level crashes  `setlevel(20)` walk forward and first trigger crashes the game.

**Comment by vvs-** [comment]
Could you be more specific? I can't reproduce this.

**Comment by Gh0stblade** [comment]
If it's not crashing for you now, it's probably the same bug that caused Tomb of Seth to crash and thus is probably fixed in the latest master. Thanks!
