### ISSUE TITLE
Non-deterministic animation freezes

### ISSUE THREAD

**Issue by stohrendorf** [opentomb/OpenTomb#292]
I was trying to get rid of "constant frame rate variables", i.e. variables that depend on the 30 FPS frame rate and never change. What happens is that mostly when the end of an animation is reached, it switches to the the new animation, but keeps stuck at frame 0. The thing is that this does not *always* happen, but *most of the time*. Can you please have a look at 7aa40326b56a21b0835328fbd370482e5894aeb7 in the `anim-framerate-test` branch, where this occurs? I can't see any obvious changes that would explain this.

**Comment by vvs-** [comment]
It's much more subtle than that. Animation doesn't work in isolation. There are state change and animation dispatch as well which are hardcoded for 30 Hz and happen in different code and game frames. But they are entangled with animation code. The whole simulation framework should be rewritten and disentangled before that will actually work. This is all related to #261.

**Comment by stohrendorf** [comment]
I'm aware of that ticket, but I didn't expect it to manifest that permanently by reorganizing the code.

**Comment by stohrendorf** [comment]
Seems to not happen anymore.
