### ISSUE TITLE
Inventory Bugs

### ISSUE THREAD

**Issue by Gh0stBlade** [opentomb/OpenTomb#297]
There are two inventory bugs I have noticed a while.

Bug 1: Opening the inventory, for a split second you can see the inventory items misplaced then pop into their initial opening sequence.

Bug 2: If you open the inventory, skip to another level then the inventory fonts are still on-screen when the next level loads.

**Comment by Banderi** [comment]
Bug 1 is due to mismatch in 3D matrices in the first frame. I'll get to fix it ASAP

**Comment by RICCIARDI-Adrien** [comment]
Hi, I checked with latest version (942167c) and it seems to me that bug 1 is solved (no more misplaced items).

To check bug 2 I started playing TR1 first level, opened inventory, opened console, executed command "setgamef(1,2)" and TR1 second level successfully loaded without inventory fonts trace on screen.

I think both bugs are solved and this issue can be closed.
