### ISSUE TITLE
recipe for target 'src/CMakeFiles/OpenTomb.dir/all' failed

### ISSUE THREAD

**Issue by hd1de** [opentomb/OpenTomb#303]
Hi,

at first, thank you all for doing such project. I tried to run that on my machine and found out that the build process fails because of the receipe for entity.cpp. Any idea how to solve this?

I have done the installation via you suggested "sudo apt-get install..." before cmake & make. So these libraries should be avail

Thank you in advance and Best Regards

Kay

$ cmake .
-- Found libsndfile: /usr/lib/x86_64-linux-gnu/libsndfile.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kay/Games/OpenTomb

$ make
[  2%] Building CXX object src/CMakeFiles/OpenTomb.dir/entity.cpp.o
In file included from /usr/include/bullet/btBulletDynamicsCommon.h:36:0,
                 from /home/kay/Games/OpenTomb/src/entity.cpp:7:
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:28: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                            ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:42: warning: unused parameter ‘value’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                          ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:37:61: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual void setParam(int num, btScalar value, int axis = -1)
                                                             ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:32: warning: unused parameter ‘num’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                ^
/usr/include/bullet/BulletDynamics/ConstraintSolver/btFixedConstraint.h:41:49: warning: unused parameter ‘axis’ [-Wunused-parameter]
  virtual btScalar getParam(int num, int axis = -1) const
                                                 ^
/home/kay/Games/OpenTomb/src/entity.cpp: In member function ‘void Entity::createGhosts()’:
/home/kay/Games/OpenTomb/src/entity.cpp:44:35: error: ‘class btPairCachingGhostObject’ has no member named ‘setIgnoreCollisionCheck’
         m_bt.ghostObjects.back()->setIgnoreCollisionCheck(m_bt.bt_body[i].get(), true);
                                   ^
In file included from /usr/include/bullet/LinearMath/btVector3.h:21:0,
                 from /home/kay/Games/OpenTomb/src/entity.h:6,
                 from /home/kay/Games/OpenTomb/src/entity.cpp:1:
/usr/include/bullet/LinearMath/btScalar.h: At global scope:
/usr/include/bullet/LinearMath/btScalar.h:337:14: warning: ‘btInfinityMask’ defined but not used [-Wunused-variable]
  static  int btInfinityMask = 0x7F800000;
              ^
src/CMakeFiles/OpenTomb.dir/build.make:146: recipe for target 'src/CMakeFiles/OpenTomb.dir/entity.cpp.o' failed
make[2]: *** [src/CMakeFiles/OpenTomb.dir/entity.cpp.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'src/CMakeFiles/OpenTomb.dir/all' failed
make[1]: *** [src/CMakeFiles/OpenTomb.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stohrendorf** [comment]
You need at least Bullet 2.83.5 for this. Install it into `/usr/local` (which should be the default, as it's cmake-based), and then remove `CMakeCache.txt` in your OpenTomb folder and reconfigure.

**Comment by stohrendorf** [comment]
Any news on this?

**Comment by orbea** [comment]
I have bullet-2.83.5 and I am getting this too on Slackware64-current,  what can be done to solve this?

Here is the list of dependencies installed on my system:
bullet-2.83.5-x86_64-1_SBo
FreeImage-3.17.0-x86_64-1_SBo
glew-1.13.0-x86_64-1
libsndfile-1.0.25-x86_64-1
libogg-1.3.2-x86_64-1
libvorbis-1.3.5-x86_6
lua-5.1.5-x86_64-1_SBo4-1
OpenAL-1.17.1-x86_64-1_SBo
SDL2-2.0.4-x86_64-1_SBo
SDL2_image-2.0.1-x86_64-1_SBo
zlib-1.2.8-x86_64-1
```
$ git clone --recursive https://github.com/opentomb/OpenTomb.git
```
```
$ cmake . && make
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenAL: /usr/lib64/libopenal.so  
-- Found Bullet: /usr/lib64/libBulletDynamics.so  
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.6.2") 
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found GLEW: /usr/include  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Found Lua: /usr/lib64/liblua.so;/usr/lib64/libm.so (found version "5.1.5") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib64/libSDL2main.a;/usr/lib64/libSDL2.so;-lpthread  
-- Found SDL2_image: /usr/lib64/libSDL2_image.so;/usr/lib64/libSDL2_image.so;-lpthread  
-- Found OGG: optimized;/usr/lib64/libogg.so;debug;/usr/lib64/libogg.so  
-- Found VORBIS: optimized;/usr/lib64/libvorbis.so;debug;/usr/lib64/libvorbis.so  
-- Found VORBISFILE: optimized;/usr/lib64/libvorbisfile.so;debug;/usr/lib64/libvorbisfile.so  
-- Found libsndfile: /usr/lib64/libsndfile.so
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/OpenTomb
Scanning dependencies of target OpenTomb
[  2%] Building CXX object src/CMakeFiles/OpenTomb.dir/world.cpp.o
In file included from /tmp/OpenTomb/src/../3rdparty/LuaState/include/LuaState.h:39:0,
                 from /tmp/OpenTomb/src/engine.h:10,
                 from /tmp/OpenTomb/src/character_controller.h:13,
                 from /tmp/OpenTomb/src/gui.h:3,
                 from /tmp/OpenTomb/src/console.h:7,
                 from /tmp/OpenTomb/src/world.cpp:12:
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h: In function ‘T lua::stack::read(lua_State*, int) [with T = short unsigned int; lua_State = lua_State]’:
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h:337:74: error: ‘lua_tounsigned’ was not declared in this scope
         return static_cast<unsigned short>(lua_tounsigned(luaState, index));
                                                                          ^
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h: In function ‘T lua::stack::read(lua_State*, int) [with T = unsigned int; lua_State = lua_State]’:
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h:342:74: error: ‘lua_tounsigned’ was not declared in this scope
         return static_cast<unsigned short>(lua_tounsigned(luaState, index));
                                                                          ^
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h: In function ‘T lua::stack::read(lua_State*, int) [with T = long unsigned int; lua_State = lua_State]’:
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h:347:73: error: ‘lua_tounsigned’ was not declared in this scope
         return static_cast<unsigned long>(lua_tounsigned(luaState, index));
                                                                         ^
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h: In function ‘T lua::stack::read(lua_State*, int) [with T = long long unsigned int; lua_State = lua_State]’:
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaStack.h:352:78: error: ‘lua_tounsigned’ was not declared in this scope
         return static_cast<unsigned long long>(lua_tounsigned(luaState, index));
                                                                              ^
In file included from /tmp/OpenTomb/src/../3rdparty/LuaState/include/LuaState.h:42:0,
                 from /tmp/OpenTomb/src/engine.h:10,
                 from /tmp/OpenTomb/src/character_controller.h:13,
                 from /tmp/OpenTomb/src/gui.h:3,
                 from /tmp/OpenTomb/src/console.h:7,
                 from /tmp/OpenTomb/src/world.cpp:12:
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaValue.h: In member function ‘size_t lua::Value::length() const’:
/tmp/OpenTomb/src/../3rdparty/LuaState/include/./LuaValue.h:349:92: error: ‘lua_rawlen’ was not declared in this scope
             return lua_rawlen(_stack->state, _stack->top + _stack->pushed - _stack->grouped);
                                                                                            ^
src/CMakeFiles/OpenTomb.dir/build.make:62: recipe for target 'src/CMakeFiles/OpenTomb.dir/world.cpp.o' failed
make[2]: *** [src/CMakeFiles/OpenTomb.dir/world.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'src/CMakeFiles/OpenTomb.dir/all' failed
make[1]: *** [src/CMakeFiles/OpenTomb.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

real	0m3.177s
user	0m2.915s
sys	0m0.236s
```

**Comment by stohrendorf** [comment]
@orbea Although it's a very different issue, the solution for you is to update Lua to at least 5.2.

**Comment by stohrendorf** [comment]
@hd1de I'm going to close this now, as I suspect it works for you now.

@orbea If the update doesn't help, please open a new issue.

**Comment by orbea** [comment]
Thanks, upgrading to lua-5.2.3 works.
