### ISSUE TITLE
Compiling Lua

### ISSUE THREAD

**Issue by garrett85** [opentomb/OpenTomb#304]
Linux Mint 17 64-bit Cinnamon.

I copied the git files from the git command shown on the site and used the same cmake command but with disappointment. Any ideas?

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found Bullet: /usr/lib/x86_64-linux-gnu/libBulletDynamics.so  
-- checking for module 'freetype2'
--   found freetype2, version 17.1.11
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "17.1.11") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/include  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
CMake Error at CMakeLists.txt:75 (find_package):
  By not providing "FindLua.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Lua", but
  CMake did not find one.

  Could not find a package configuration file provided by "Lua" with any of
  the following names:

    LuaConfig.cmake
    lua-config.cmake

  Add the installation prefix of "Lua" to CMAKE_PREFIX_PATH or set "Lua_DIR"
  to a directory containing one of the above files.  If "Lua" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/garrett/Games/openTomb/OpenTomb/CMakeFiles/CMakeOutput.log".

**Comment by stohrendorf** [comment]
Do you have the lua dev package installed?

**Comment by garrett85** [comment]
I don't know what that is or the package name to install it. I did run the sudo apt-get install command to get all dependencies given in the install instructions.

**Comment by garrett85** [comment]
I used the Synaptic Package Manager to get the following packages.

libluabind0.9.1
libluabind-dev
liblua5.1-0-dev

But I got same error message ->

CMake Error at CMakeLists.txt:75 (find_package):
  By not providing "FindLua.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Lua", but
  CMake did not find one.

  Could not find a package configuration file provided by "Lua" with any of
  the following names:

    LuaConfig.cmake
    lua-config.cmake

  Add the installation prefix of "Lua" to CMAKE_PREFIX_PATH or set "Lua_DIR"
  to a directory containing one of the above files.  If "Lua" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/garrett/Games/OpenTomb/CMakeFiles/CMakeOutput.log".
garrett@mint-desktop ~/Games/OpenTomb $

**Comment by stohrendorf** [comment]
Do you have a more recent version of liblua5.1-0-dev, like liblua5.3-0-dev, which you can install?

**Comment by garrett85** [comment]
Yep I went to the lua website and downloaded and built the latest package (5.3-0-dev) but I'm still getting the same thing.

**Comment by stohrendorf** [comment]
Does /usr/share/cmake/modules/FindLua.cmake exist?

**Comment by garrett85** [comment]
No
garrett@mint-desktop ~ $ ls /usr/share/cmake
SharedDesktopOntologies

**Comment by stohrendorf** [comment]
Sorry, I should have thought of it earlier: Either your cmake installation is incomplete, or broken. If you can find a package like `cmake-modules` or `cmake-extra-modules` or similar, then install it, and try again to configure OpenTomb; otherwise, try to re-install cmake. If neither doesn't work, I'm out of ideas, sorry.

**Comment by garrett85** [comment]
garrett@mint-desktop ~ $ sudo apt-get install cmake
[sudo] password for garrett: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 140 not upgraded.
garrett@mint-desktop ~ $ sudo apt-get install cmake-modules
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cmake-modules
garrett@mint-desktop ~ $ sudo apt-get install cmake-extra-modules
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cmake-extra-modules


:(

**Comment by stohrendorf** [comment]
After some minutes of googling, I found that the packages `build-essential` and `cmake-data` need to be installed (maybe only the latter, though).

**Comment by vloup** [comment]
Isn't `FindLua.cmake` provided by the project itself?
`FindLua.cmake` is in https://github.com/LuaDist/Tools/tree/master/cmake/.

The best solution to get a copy of it is to use `git clone --recursive https://github.com/opentomb/OpenTomb.git` instead of the classic `git clone https://github.com/opentomb/OpenTomb.git`.
Adding `--recursive` will clone submodules recursively (LuaDist is a submodule of LuaState, which is again a submodule in this codebase).

**Comment by stohrendorf** [comment]
That module isn't used by OpenTomb. In fact, cmake should provide its own FindLua, so I'm not sure what happens here.

**Comment by garrett85** [comment]
garrett@mint-desktop ~/Games/OpenTomb $ sudo apt-get install build-essential cmake-data
[sudo] password for garrett: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
cmake-data is already the newest version.
cmake-data set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 95 not upgraded.

------------------------------------------------------------------------------------------
garrett@mint-desktop ~/Games $ git clone --recursive https://github.com/opentomb/OpenTomb.git
CMake Error at CMakeLists.txt:75 (find_package):
  By not providing "FindLua.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Lua", but
  CMake did not find one.

  Could not find a package configuration file provided by "Lua" with any of
  the following names:

    LuaConfig.cmake
    lua-config.cmake

  Add the installation prefix of "Lua" to CMAKE_PREFIX_PATH or set "Lua_DIR"
  to a directory containing one of the above files.  If "Lua" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/garrett/Games/OpenTomb/CMakeFiles/CMakeOutput.log".
-------------------------------------------------------------------------------------------------------

What am I missing. If you all are running it what does your system have that mine doesn't?

**Comment by stohrendorf** [comment]
Invalid due to revert to old code.

**Comment by aedrax** [comment]
Did anyone find a solution to this error?

**Comment by aedrax** [comment]
Actually I discovered the problem, I didn't have the latest version of cmake, updating from 2.8 to 3.2.2 fixes it for future reference
