### ISSUE TITLE
Wrong return order

### ISSUE THREAD

**Issue by zdimension** [opentomb/OpenTomb#311]
At https://github.com/opentomb/OpenTomb/blob/master/scripts/audio/sample_override.lua#L202

``` lua
return -1, -1, "NONE";
```

It should be

``` lua
return "NONE", -1, -1;
```

**Comment by Gh0stblade** [comment]
`bool script::MainEngine::getOverridedSamplesInfo(int *num_samples, int *num_sounds, char *sample_name_mask)`

Looks fine to me.

**Comment by zdimension** [comment]
Oh, I inverted the lines. at line 200,
```lua
return tr_sound_info[ver].sample_name_mask, tr_sound_info[ver].num_samples, tr_sound_info[ver].num_sounds;
```
should be
```lua
return tr_sound_info[ver].num_samples, tr_sound_info[ver].num_sounds, tr_sound_info[ver].sample_name_mask;
```

**Comment by Gh0stblade** [comment]
Yeah, that doesn't look right. You should make a pull request to fix that if possible.

**Comment by zdimension** [comment]
PR: https://github.com/opentomb/OpenTomb/pull/312
