### ISSUE TITLE
OpenAL Assertion Failed.

### ISSUE THREAD

**Issue by Gh0stBlade** [opentomb/OpenTomb#317]
So ENGINE.md confirms that OpenAL lib included in the repository is an altered version. I do not know what has been changed but perhaps these changes are related to the issue I'm experiencing?

`Assertion failed: lockret == althrd_success, file opentomb\extern\al\Alc\ALc.c, line 747`

Horrible work around:

Comment out lines 747/752 @extern\al\alc\alc.c

**Comment by TeslaRus** [comment]
Changed only backend: used SDL as an output device; al uses pthread for working... maybe additional phread initialization was missed or duplicated; I test that Al build on my build of OpenMW with multi threading: works fine;

**Comment by vvs-** [comment]
I have no music, playStream produce nothing. But sound effects are working except that there is a nasty crash if samples are overriden in TR1.

**Comment by TeslaRus** [comment]
playStream was disabled by some reasons; It will be enabled after audio module working in own thread;

**Comment by vvs-** [comment]
I think that the new WAD player should be back ported too.

**Comment by Gh0stblade** [comment]
Test

**Comment by Gh0stblade** [comment]
Test

**Comment by Gh0stBlade** [comment]
Tested against bd56a0e88b821ea546a486d7c911b7f96055ab5c

This no longer happens.
