### ISSUE TITLE
Lara can't climb back up

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#332]
In _Lost Valley_ at `37841,21063,-253,90,0,0` and _City of Khamoon_ at `27146,15322,512,180,0,0` push action+down to climb down, then push up to climb up. Alternatively, you can try to shimmy from that position.

**Comment by TeslaRus** [comment]
ok, found it, and know the reason... debug becomes;

**Comment by TeslaRus** [comment]
fixed in commit 49fa1aef74794b822e815c030072ed6a1f93946f

**Comment by vvs-** [comment]
_Lost Valley_ is fixed, but no changes in _City of Khamoon_.

**Comment by TeslaRus** [comment]
in progress

**Comment by vvs-** [comment]
This is related to #196.

**Comment by TeslaRus** [comment]
fixed in physics_bullet - extended near room list checking; please check overlapped rooms (Natla mines if I correct).
