### ISSUE TITLE
[TR3] Bridge above Quicksand

### ISSUE THREAD

**Issue by Gh0stblade** [opentomb/OpenTomb#333]
There seems to be a rare glitch whilst running across a bridge which is above Quick Sand. This occurs on the Coastal Village level.

Lara begins to wade as if she's in Quicksand, except this shouldn't be happening since she's in an entirely different room and on a bridge.

**Comment by vvs-** [comment]
This looks very similar to #9. I should check that out as well.

**Comment by Gh0stblade** [comment]
Thanks @vvs- I'll close this one, definitely the same issue.
