### ISSUE TITLE
Inventory Items Textureless Bug

### ISSUE THREAD

**Issue by Gh0stblade** [opentomb/OpenTomb#338]
There's a bug with the gui/renderer somwhere that results in no texture being binded to inventory items.

This occurs when picking up an item. When the item is shown on-screen at the bottom right. Opening the inventory results in this:

[Click](http://i.imgur.com/YPMchzP.png)

**Comment by TeslaRus** [comment]
Found reason and locally fixed, see fix soon

**Comment by TeslaRus** [comment]
Fixed in commit 71c367360e571f2ba0a2bf479aa431a038c0a70e
