### ISSUE TITLE
Crash in Angkor Wat

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#34]
Broken by db18b55fc324bfc9c69ba633b69aafbd8295b8d5.

**Comment by Lwmte** [comment]
I believe it was broken even before this commit, as I got all my TR4 levels crashing while testing Lara's hair recently. Figuring it out now...

**Comment by vvs-** [comment]
Mine was working before that.

**Comment by Lwmte** [comment]
Actually, problem was introduced because for some strange reason, some TR4 meshes are degenerate (e.g., 3 vertices with zero coordinates), in case of Angkor Wat, it crashed because Von Croy contained three such meshes.

Shouldn't crash anymore.
