### ISSUE TITLE
Lara clip through walls when pulling Underwater Switches.

### ISSUE THREAD

**Issue by Gh0stBlade** [opentomb/OpenTomb#342]
I have tested this on both the underwater switches in the City of Vilcabamba level. When pulled,Lara is teleported through the wall mesh.Most likely related to Lara position correction.

**Comment by vvs-** [comment]
Yes, that's a very old bug. Also, there is related bug with pushing/pulling movables in a narrow spaces.

**Comment by vvs-** [comment]
Seems like pulling blocks is fixed now. But not the underwater switches.

**Comment by vvs-** [comment]
I'm not able to reproduce this after recent changes.

**Comment by TeslaRus** [comment]
fixed after introducing moving to trigger activation point

**Comment by vvs-** [comment]
I think we should close this.
