### ISSUE TITLE
Camera is stuck

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#344]
Camera is stuck on some levels, like room with a movable block in _City of Vilcabamba_ or _The Great Wall_.

**Comment by vvs-** [comment]
According to @TeslaRus this is related to #275.

**Comment by vvs-** [comment]
The actual cause is a non-working SET_TARGET command timer.

**Comment by vvs-** [comment]
The wonders of triggers :open_mouth:
The timer is ignored. Lara looks at the object until the camera target is changed for whatever reason. Every object can be targeted only once, after that it's ignored. So, as long as Lara activates consecutive PADs with the same target she looks at it. But if the target is changed even by the player no trigger command targeting the same object will work again. So, each individual target must be locked by some special flag.

**Comment by TeslaRus** [comment]
I add lock (once) flag to the camera sequence, but lock to the target... interesting what flag are used, or original logic...

**Comment by vvs-** [comment]
My guess is that every object in game has a special one-shot camera flag. After this object was targeted by a trigger it's locked. I never actually decompiled the binary though.

**Comment by vvs-** [comment]
The only missing thing remained is look key, which breaks camera targeting at any point. Without that key it's very difficult to move out of trigger area. Besides, some triggers doesn't even have once flag and use distinct camera.

**Comment by TeslaRus** [comment]
yep, I will implement it in next commit (task state = current)

**Comment by TeslaRus** [comment]
added to TeslaRus/OpenTomb repo
