### ISSUE TITLE
Something's wrong with single/double-sided polygon flags

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#352]
Here's an example from Lara's House:

![screenshot from 2016-06-30 18-29-59](https://cloud.githubusercontent.com/assets/5171934/16494366/c18862fe-3ef1-11e6-968e-0f584f1c76b1.png)

**Comment by TeslaRus** [comment]
It is not frustum shaders, it is single / double sided polygons flags.

**Comment by vvs-** [comment]
Yes, I'm just reading #16.

**Comment by vvs-** [comment]
BTW, did you notice that you can look behind the wolves through their eyes?

**Comment by TeslaRus** [comment]
fixed flags parsing in https://github.com/opentomb/OpenTomb/commit/b08f27339a8f93edfb1e4dfb9b47090edd801a58

**Comment by vvs-** [comment]
The original issue is fixed now. Wolves have transparent eyes in original TR1 as well.
