### ISSUE TITLE
Switching from full-screen is broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#354]
OpenTomb becomes unresponsive after switching to another window from full-screen. This affects screenshots as well, i.e. if this hotkey is assigned to desktop.

**Comment by TeslaRus** [comment]
I can't reproduce (no crashes, Alt + Tab works correct), but if bug is stable then it should be fixed...

**Comment by vvs-** [comment]
I'm not sure. It could be a driver issue. Someone working on Linux (or maybe even OS X) should confirm this.

**Comment by vvs-** [comment]
BTW, switching from windowed mode works fine. Only full-screen is affected.

**Comment by TeslaRus** [comment]
I have trying full screen and windowed modes... maybe driver, or I need to reinit OpenGL context, or something bug in SDL... I use SDL 2.0.4...

**Comment by vvs-** [comment]
This is a system specific bug related to sound. I found that even running OT under debugger caused it to deadlock sometimes on an audio thread when PulseAudio is enabled. After configuring everything to run using just ALSA the deadlock is gone.
