### ISSUE TITLE
Incorrect walking animation

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#37]
When the walk button is tapped once, Lara makes two steps most of the time. But in TR1 she makes just one.

**Comment by Lwmte** [comment]
Can't reproduce this, she steps once in all game versions. Maybe it's SDL-specific bug... Are you on keyboard or gamepad?

**Comment by vvs-** [comment]
Did you hold shift when pressing forward? I mean, she should walk, not run. Sometimes she makes one step, but most of the time she makes two.

**Comment by Lwmte** [comment]
We have accidentally discovered this bug while testing builds on my laptop, looks like it happens only if framerate is lower than 60. In such situation, state change sometimes skips desired frame range, which results in one more state loop.

**Comment by vvs-** [comment]
The reason for this difference is just a rounding error. If the frame rate is higher than 59.99995 then the animation frame in `Entity::getNextFrame` will be 15.9999 and after converting floating into integer it becomes 15. If the frame rate is slower then it remains as 16. That means that animation dispatching doesn't take place in the second case because the dispatching frame to the next state is 15.

I don't understand why the condition there is `if((disp->frame_high >= disp->frame_low) && (*frame >= disp->frame_low) && (*frame <= disp->frame_hig
h))`. That means dispatching at the precise frame which won't work at the variable frame rate.

**Comment by vvs-** [comment]
There are certainly two different things in this issue. The entity state is actually changed only on the second animation frame which should be considered the real cause. And the same animation frame can be repeated many times depending on the actual frame rate. But when the frame rate is low the rounding errors make certain frames appear less often than the other. That means that some state changes may be skipped when the frame rate is low enough, i.e. about 60 Hz.

**Comment by vvs-** [comment]
The current logic is very weird. Because it used different variables for frame number and depending on the frame rate and rounding you either get the same animation frame several times (including entity state change) or you might get two animation frames changing back and forth skipping the state change completely.

**Comment by vvs-** [comment]
It's really, really complicated. It depends on other animation code too. The state is changed in the first entity animation frame, then in the character commands and then in the second animation frame. And by that time the frame number already has changed.

**Comment by vvs-** [comment]
Regression caused by a missing workaround and no general solution.

**Comment by vvs-** [comment]
For the same reason Lara can't reach an opposite ledge after a running jump in _Obelisk of Khamoon_, room 30, sector `2,7`.

**Comment by vvs-** [comment]
Animation is now robust against frame dropping.

**Comment by Gh0stBlade** [comment]
@vvs- 

I checked this against 11bd405e769fc2c613794c1d1346cbcabdc37859

I used fraps to lock the framerate to 30 fps when recording. If I make Lara walk I still get 2 steps rather than 1. Stopping recording solves the issue but still there are issues with the animation system (possibly anim command parsing) at low framerates.

**Comment by vvs-** [comment]
I never tested it at such low framerates. The original bugs were reported against 59 something Hz. This is now works fine.

That's not to say that #261 isn't valid anymore.

**Comment by vvs-** [comment]
It's fixed for good, tested on 30 Hz. Note, that there still is #261.
