### ISSUE TITLE
[Win32] Missing DLL under prealfa binaries

### ISSUE THREAD

**Issue by S-h-0-X** [opentomb/OpenTomb#377]
After trying to execute under Windows 10 x64 Home, OpenTomb can't start because the library libwinpthread-1.dll is missing.

**Comment by TeslaRus** [comment]
github build with other params that I uses... try binaries from https://sourceforge.net/projects/opentomb/files/?source=navbar - not latest, but stable. Missing dll's may be taken from some mingw builds (temporary solution), but it is better to setup properly GitHub build.

**Comment by Gh0stBlade** [comment]
This is clearly because I have not included the correct DLLs, as a result, I will close this as future releases should include everything.
