### ISSUE TITLE
Overlapping/Bleeding room collision. (TR3)

### ISSUE THREAD

**Issue by Gh0stBlade** [opentomb/OpenTomb#386]
I'm not sure when this was introduced, but a commit has induced a bug which allows nearby rooms' collision to be enabled and overlap the current room Lara is in. I have only checked TR3, Lara's home.

Chair in room above Gym room. http://i.imgur.com/mcZdqNe.jpg
You can see the chair collision plus more from other rooms is present in the Gym room. http://i.imgur.com/HzEpee5.jpg

Edit: So far only seems to occur in TR3 Lara's Home.

**Comment by vvs-** [comment]
Do you mean [that](https://github.com/opentomb/OpenTomb/issues/308#issuecomment-230474127) one as well? Probably, I posted it in the the wrong issue then.

**Comment by Gh0stBlade** [comment]
Thanks. It is most likely the same bug. A few months back, when I tried TR3, I didn't have these problems (IIRC). Not sure why I'm seeing them now (I noticed this when Lara's position was lower than usual on the monkey bars in the Gym room) checking collision showed the mesh is wrong.

Closing this : )

**Comment by vvs-** [comment]
That example with chair is hard to reproduce. This one is much better:
![screen_00000](https://cloud.githubusercontent.com/assets/5171934/18889459/bfc4aac2-8505-11e6-86ef-03c8fcd39b54.png)

**Comment by Gh0stBlade** [comment]
@vvs- Strange, I can re-produce the Gym room collision bug every time.

**Comment by vvs-** [comment]
I use `alt_room_refactoring` branch, maybe that's the reason. I reproduced it once and now after last commit I can't.
