### ISSUE TITLE
Locks, pushables and pick-ups are extremely sensitive to the activator's angle

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#388]
Lara can't activate any object unless she is tuned to a certain angle. This makes it very difficult to operate some objects.

This is an ancient bug.

**Comment by TeslaRus** [comment]
not only angle, some times OBB check fails (pushable block)

**Comment by vvs-** [comment]
Yes, but turning Lara around vertical axis aligns and her OBB also.

**Comment by Lwmte** [comment]
I guess it's because of the regression of current master.
There's this patch missing: https://github.com/opentomb/OpenTomb/commit/fee6d073b34628dd431fc747312f1b4eb652f499

**Comment by TeslaRus** [comment]
I know about obb overlap parameter in old master, but not porting it because fix checking activations geometry is more complex task than only extents adding.

**Comment by vvs-** [comment]
It's near impossible to pick-up keys underwater.

**Comment by vvs-** [comment]
Looks like there is an improvement after cf5fb44f6a0f49a075b72e0c7e2e3960e0d4e8e9, but I'm not entirely sure.

**Comment by TeslaRus** [comment]
in cf5fb44 there is only one global change: script setEntityPosition rebuilds **OBB** (used in pick up condition) and physics body...
