### ISSUE TITLE
Wrong textures in Lara' home

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#39]
In TR2 Lara' home there are wrong textures in some of the windows. In particular, in the kitchen when you look at the windows from outside.

**Comment by Lwmte** [comment]
It happens because these windows are actually breakable objects, and there is no function written for them (yet). What you see as graphical glitches are actually meshswap glass shards, which should become active when window was shot.

**Comment by vvs-** [comment]
Ok. It just looks very different from other breakable windows, e.g. in *Bartoli's Hideout*.

**Comment by Gh0stBlade** [comment]
Closing this, unimplemented, not really an issue at this state.
