### ISSUE TITLE
Saturated colors

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#398]
Lara's model sometimes has saturated bright colors from the local lights. This was introduced recently.
![screen_00000](https://cloud.githubusercontent.com/assets/5171934/20319065/d0b91da6-ab7d-11e6-8e9c-26f2c3d89256.png)

**Comment by Lwmte** [comment]
Can you also check if there are green artifacts on Lara sometimes, especially when she enters that big cave with stairs and first switch in Caves?

I also had "saturated" colours from lights recently, but at first I thought it's because now I've completely switched to MSYS2-exclusive mingw-w64 64-bit setup.

**Comment by vvs-** [comment]
No, I don't see any green artifacts, but it could be driver specific.

Bisecting shows that this bug was introduced in 4565790dde479f9104b24862ac5bd5b54b7c0d44.

**Comment by Gh0stBlade** [comment]
I recall that light sources were changed so that rooms in the near by room lists' lights also affect Lara. I assume the alteration to the near by room list code has caused this bug.

**Comment by gabrielmtzcarrillo** [comment]
I've been working on the entity shader, and it's due to light directions no being normalised.

![screen_00000](https://user-images.githubusercontent.com/3135816/30035679-448bca14-9172-11e7-9fe9-726c03de9f46.png)

**Comment by vvs-** [comment]
BTW, this particular case was fixed in e9a9a8581ed29961fca1f18c3fde83d9e7504871, but not the root cause. Other manifestations of this bug still exist, e.g. too dark/bright doors/blocks.
