### ISSUE TITLE
Overlapping room confuse camera and frustum

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#40]
In TR3 Lara' house there is an overlapping between room 117 and room 132 below. This produces very weird transition effects when walking or jumping.

**Comment by Lwmte** [comment]
Hmm, I tested it, and it seems that everything works right (except that I can't push-pull the blocks because of faulty collision detection). When Bullet debug drawer is active (r_coll), indeed I get overlapped room geometry, but that should be filtered out considering current room.

**Comment by vvs-** [comment]
Ok, here's the test case. Type `setgamef(3,99)` then `setEntityPos(player,21903,33910,2560,188,0,0)`. When back to game play run forward. Lara should fall to room 132. Now walk left or forward a few steps then jump straight up. Lara should return to room 117.

**Comment by vvs-** [comment]
Another good example is *The Cistern* level. Move Lara in the room with a switch 11. Jump straight up and she'll be transferred into room 10. Now roll and she immediately moved into room 9. All this without changing coordinates. And it caused big trouble in the current frustum code.

**Comment by vvs-** [comment]
The camera current room and position are not coherent. It's visible in `room_info` where it used different room for camera sector. No matter which room it claims to show (9 or 10) it always dumps information about room 9 which is correct in the above case. Looking at the source it seems that `renderer.cam->current_room` is different from what sector->owner_room actually is.

**Comment by vvs-** [comment]
No more reproducible after #384.
