### ISSUE TITLE
Blocks can be pushed over thin air

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#400]
![screen_00000](https://cloud.githubusercontent.com/assets/5171934/20491690/389d3ea8-b023-11e6-849c-3364d12aeec8.png)

**Comment by Gh0stBlade** [comment]
What does the collision mesh look like?

**Comment by TeslaRus** [comment]
r_coll in console... collision mesh is correct here (test it) - it is missed floor type check (solid / portal down)

**Comment by vvs-** [comment]
Yes, collision mesh is correct, of course. I never claimed that it's not.

**Comment by Gh0stBlade** [comment]
Haha sorry, I was just wondering.
