### ISSUE TITLE
tr_soundtracks_for_opentomb.zip = 403 Forbidden

### ISSUE THREAD

**Issue by TheIndra55** [opentomb/OpenTomb#406]
When i try to download the soundtracks at http://trep.trlevel.de/opentomb/files/tr_soundtracks_for_opentomb.zip i get a 403 forbidden? Is your webserver blocking my ip address?

**Screenshot:** https://s.theindra.eu/?img=14-05-36.png

**Comment by stohrendorf** [comment]
As an alternative there is also http://opentomb.earvillage.net/

**Comment by TheIndra55** [comment]
Thanks @stohrendorf it worked <3

**Comment by Lwmte** [comment]
Hm, I didn't use trlevel hosting for a long time, maybe something is broken...

**Comment by strycore** [comment]
I can host files on https://lutris.net/ if needed, just ask and I'll make them available (I do have plans to host Linux binaries in the future)
