### ISSUE TITLE
[Question] Level editor for TR 5 ?

### ISSUE THREAD

**Issue by Nightshades1** [opentomb/OpenTomb#410]
Hello and sorry for opening an issue but it seem we can't comment on github or idk, By any way do you have a working Tomb Raider Chronicle level editor or similar application coded in c# maybe ? It's kinda retarded the lack of support from these developers that never released it as well as the game source code lol.

I'm trying to make a dumb map on TR5 with the software "DXTRE3D" I did a test level with the entity "Electric Wires" the one in the sub marine... Guess What it's super bugged the wire that hit the water (separated by portal) this just burn everything in the map even when i'm not on the floor lol, The Object code bits is set like what they did on the original level, i seen everything and still doesn't work lol.

Even the animated texture doesn't work, TurboPascal the developer of this editor has stopped working on this since a very long WHILE and sadly there isn't a single editor for TR5 :(

As i've seen you guys got a lot of documentation about file format, i can't believe no one made an editor Xd but i guess coding for an old game isn't very researched.

Well thanks for Open Tomb (i have subscribed to the YT channel since a LONG WHILE) You did an awesome job guys (everyone that contributed) I wish that this engine see the light a day :P

**Comment by Gh0stBlade** [comment]
TR5's editor was leaked for PS1. Only problem is there are no sample wad files thus there are no tools which can create WAD files compatible with TR5's editor. In addition there were no tools included to build the levels for PC, only PS1.

**Comment by Nightshades1** [comment]
Ah :+1:  didn't know about that it got leaked (i was childish when psx existed), Damn Eidos (now SquareEnix forum) these guys don't care about tomb raider fans anymore after the release of TR4 Editor :(

But OpenTomb is much better, just loaded the TR5 map Joby5.trc (sub marine sinking) and the water is awesome, needed to play with noclip, electric wire isn't coded yet ^^.

**Comment by Nightshades1** [comment]
Usage: DEL2FAB [options] <infile> <outfile>
[options]
  /a(d) weather type (1 = rain, 2 = snow, (default = 0))
  /d+   enable debugging messages
  /e+   disable version errors
  /f+   add mirror code
  /g(d) Lara draw type (1=Normal, 2=Young, 3=Bunhead, 4=Office, 5=Subsuit, 6=Artic. (Default = Normal))
  /h(f) enable young Lara
  /i(f) set underwater red subtractor (default = 0.0)
  /j(f) set underwater green subtractor (default = 0.0)
  /k(f) set underwater blue subtractor (default = 0.0)
  /l(s) set level name to 's'
  /m+   disable subdiv on small room polys
  /n+   enable Japanese WAD output
  /o-   disable texture optimisation
  /p+   enable starfield
  /q+   enable Neural-Network colour quantisaion
  /r(d) Room draw type (1=Normal, 2=No underwater, 3 = Title (default = Normal))
  /s-   disable sprite processing
  /t+   enable demo processing
  /u+   Include underwater particles code
  /v(d) set maximum vertices (default = 93)
  /w-   disable skinning
  /x+   create code wad
  /y(d) set font's y position (default = 256)
  /z+   write VRAM

With those "Lara Drawtype" you can update the documentation, was reading the level format on open tomb and it seem it's missing all lara draw types, cya !

**Comment by Gh0stBlade** [comment]
Closing this since the project at the moment is primarily aimed at cloning Tomb Raider. Though there may be plans to create editors, it's not something which is a priority right now.
