### ISSUE TITLE
error: ‘LUA_OK’ was not declared in this scope

### ISSUE THREAD

**Issue by PaddyMac** [opentomb/OpenTomb#411]
[ 85%] Building CXX object CMakeFiles/OpenTomb.dir/src/engine.cpp.o
/home/patrick/work/OpenTomb/src/engine.cpp: In function ‘int Engine_ExecCmd(char*)’:
/home/patrick/work/OpenTomb/src/engine.cpp:1429:55: error: ‘LUA_OK’ was not declared in this scope
                 if (luaL_dostring(engine_lua, pch) != LUA_OK)
                                                       ^~~~~~
CMakeFiles/OpenTomb.dir/build.make:158: recipe for target 'CMakeFiles/OpenTomb.dir/src/engine.cpp.o' failed
make[2]: *** [CMakeFiles/OpenTomb.dir/src/engine.cpp.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/OpenTomb.dir/all' failed
make[1]: *** [CMakeFiles/OpenTomb.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vvs-** [comment]
Which Lua version you are using? OpenTomb requires Lua 5.2 or later.

**Comment by PaddyMac** [comment]
I was using Lua 5.1.5. I upgraded to 5.2.3, and it compiled without any problem. Thanks for the help. Perhaps the cmake script should require a minimum version because cmake was happy with 5.1.5 during the configure phase.

**Comment by vvs-** [comment]
Yes, the `CMakeLists.txt` is very basic and could be improved. But it wouldn't prevent another sorts of breakage as we've seen in the days of old `master` branch. We need a more powerful cross-platform build system which nobody has the incentive to work on.
