### ISSUE TITLE
Underwater levers in TR2 are extremely sensitive to Lara's distance

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#419]
It happened recently. Perhaps a collision problem.

**Comment by TeslaRus** [comment]
for me TR2 map 3 UW switch works... maybe there are TR2 UW switches with model != 105...
current switches map:
tr1_switches[56]  = tr_anim_uwswitch;
tr2_switches[105] = tr_anim_uwswitch;
tr3_switches[130] = tr_anim_uwswitch;

**Comment by vvs-** [comment]
Nope. No TR2 switches work here. Recompiled everything from scratch. Only TR1 maps work.

**Comment by vvs-** [comment]
It doesn't work for me after 9e30ad2455d8c25c9b1b5dbd2332698bbee60b67.

**Comment by vvs-** [comment]
Ok. I found the reason. Before that commit Lara couldn't move further, but now I always push her too far. If I try to move by a small steps then it works at some point, but stops working if I move her some more. So, it's extremely sensitive to her distance to lever.
