### ISSUE TITLE
TR1 wolves' eyes are strangely rendered

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [opentomb/OpenTomb#425]
Hi, thank you for your great work !

While playing TR1 first level, I noticed than wolves eyes were not correctly displayed according to Lara's camera angle.

Here are some screenshots showing the problem.

I played on Xubuntu 16.10 64 bits, game version was commit f54d3d34b2aaaf2599b8d9ebde6cf622bc81061e.
![capture d ecran_2017-03-04_00-05-08](https://cloud.githubusercontent.com/assets/4292857/23572405/2c86f158-006f-11e7-921d-f16f41d06887.png)
![capture d ecran_2017-03-04_00-05-26](https://cloud.githubusercontent.com/assets/4292857/23572406/2c8c189a-006f-11e7-8c69-357280506c04.png)

**Comment by vvs-** [comment]
Yes, I already noted it [here](https://github.com/opentomb/OpenTomb/issues/352#issuecomment-269139951)

**Comment by RICCIARDI-Adrien** [comment]
Ok, I didn't notice this issue !

**Comment by CDrosos** [comment]
Is OpenLara http://xproger.info/projects/OpenLara/ always updated? if we find a bug there is it a good idea to post it here?

**Comment by Gh0stBlade** [comment]
@CDrosos 

OpenLara and OpenTomb are entirely separate projects with different goals, features and bugs.

You should only post OpenTomb issues here.
OpenLara bugs need to be posted here: https://github.com/XProger/OpenLara/issues

**Comment by CDrosos** [comment]
ok got it

**Comment by TeslaRus** [comment]
duplication
