### ISSUE TITLE
Confused on how to set this up so I can play??

### ISSUE THREAD

**Issue by gameslayer** [opentomb/OpenTomb#434]
Hey guys just asking for help on how to set this up so I can play, the instructions do explain it well enough and OpenTomb just opens to a black window obviously because I didn't set it up correctly.

**Comment by TeslaRus** [comment]
Hi! 
1) original TR1 maps should be placed to (in example) engine\data\tr1\data\LEVEL1.PHD
2) after engine starting open console by ~ and type **setgamef(1, 1)**
where first param - game version (1 - TR1, 1.5 - TR1 UB, 2 - TR2, ...), second param - level id (99 - training room)

**Comment by gameslayer** [comment]
I am using the Linux version not the Windows version, I got the GOG1 - 3 Tomb Raider pack off GOG and I don't have a LEVEL1.PHD file in Tomb Raider 1

**Comment by Gh0stBlade** [comment]
https://www.gog.com/forum/tomb_raider_series/tomb_raider_1_native_windows_and_resolution_patch

**Comment by gameslayer** [comment]
@Gh0stBlade This has nothing to do with this post or OpenTomb

**Comment by Gh0stBlade** [comment]
It does, The GOG versions of Tomb Raider have all assets packed into "GAME.GOG". The only way to retrieve the level files. i.e LEVEL*.PHD is to unpack it! The thread provides instructions how to do so.

**Comment by gameslayer** [comment]
@Gh0stBlade The link you shard is about a native resolution patch for the old version of the game from GOG not about how to set up OpenTomb to run the game in the new engine however it does show how to get the files I do need to get this working so thank you :)

**Comment by gameslayer** [comment]
I used gcdemu to mount the game.gog file and extracted all the files and it works, can you give me the controls so I know how to play?

**Comment by Gh0stBlade** [comment]
Hi, It's great to hear the link has been of use to you. I would like to clarify, I did not in any way suggest or imply the link in question shows how to setup OpenTomb. It was posted to help you, please do not be argumentative towards people trying to help you.

You can open config.lua in a text editor to view the current control/key bindings or customise them :)

Cheers.

**Comment by gameslayer** [comment]
I wasn't arguing I was just confused by the title and what it had to do with it but did help in another way 

Thank you for the help

**Comment by vvs-** [comment]
Possibly duplicate of #165.

**Comment by rsantellan** [comment]
Hi, I'm just got my old tomb rider CD and after:

- Cloning the repo
- Installing dependecies
- Running cmake . && make

There is no engine folder to put the data, what did I did wrong?
This are my created folder. 
![opentomb](https://user-images.githubusercontent.com/1820598/28654761-1fe89792-726d-11e7-8e71-60219cc37d50.png)


Regards

**Comment by TeslaRus** [comment]
autoexec.lua and config.lua - configuration files;
data structure example (base location from the screen above): 
data/tr1/data/LEVEL1.PHD

there is command line option to set base directory;
other MSW build example located on Sourceforge (engine.7z file)
