### ISSUE TITLE
TR1 enemies not moving

### ISSUE THREAD

**Issue by DoubleCouponDay** [opentomb/OpenTomb#437]
I can trigger death animations by filling them with enough bullets but other than that they stand still. I am using 2c056af386ad1c1ebc6f970298ea0cbe7d71ef53 and here is my autoexec.lua file. 

-- LUA autoexec config file
-- CVAR's section. here you can create and delete CVAR's

if(cvars == nil) then
    cvars = {};
end;

-- CVAR's section. here you can create and delete CVAR's
cvars.show_fps = 1;
cvars.free_look_speed = 2500;

-- AUTOEXEC LINES
setLanguage("english");

setGravity(0, 0, -5700.0);
mlook(1);
freelook(0);
cam_distance(1024.0);
noclip(0);
--loadMap(base_path .. "data/tr1/data/CUT1.PHD");
--loadMap(base_path .. "tests/altroom2/LEVEL1.PHD");
--loadMap(base_path .. "tests/heavy1/LEVEL1.PHD");
--loadMap(base_path .. "tests/TRIGGERS.PHD");
setgamef(1, 5);
dofile(base_path .. "save/qsave.lua");

**Comment by Lwmte** [comment]
Sorry, AI is not implemented at all at the moment. You can only control them yourself using setPlayer command :)

**Comment by TeslaRus** [comment]
Latest SF binaries: TR1 enemies moves to Lara, but they are stupid...
binaries: https://sourceforge.net/projects/opentomb/files/engine.7z/download
