### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#443]
Just to know,
Do you have an estimate of how long it will take to develop (final release) ?

**Comment by vvs-** [comment]
What do mean by _final_ release? If that means support for TR1-5, then it will take several years. Fully functional TR1 should be much more easier to do, but it heavily depends on available spare time. I'd estimate that a dedicated developer could finish TR1 support before end of the year, but a real people can't just dedicate all their time to that task.

**Comment by TokyoSU** [comment]
No just tr1 for now,
i want to develop the tr trilogy game but tr4 not have most enemie compatibility (like sas have only one slot), trng cant resolve this with last release (plugins).
Seeing your work makes me want to work on it, i want to make level, and I encourage you on that path, good work 👍
