### ISSUE TITLE
OpenTomb cannot play music files

### ISSUE THREAD

**Issue by GlacialTurtle** [opentomb/OpenTomb#447]
When trying to use OpenTomb, it complains that it cannot open the music files in the terminal output, though as far as I can tell, I have them in what appears to be the correct place and there doesn't seem to be other problems with the files.

I have a folder simply called TombRaider, and in that is the data, audio and fmv directories alongside the OpenTomb executable and other necessary files (scripts etc.). Each of these has tr1, tr2 etc. and then in those is data, audio or fmv where the relevant files are. The music files are all OGG Vorbis in OpenTomb/audio/tr1/audio and play fine in VLC or Totem.

With the in game console, the message "Streamplay: CANCEL, wrong track index or broken script"

The same is true for Tomb Raider 4 OGG.

In all games normal audio (enemies, lara grunting, foot steps) seem to play fine.

Tested on Ubuntu 16.04 64-bit with latest git.

**Comment by Gh0stBlade** [comment]
To confirm you are using the audio files from here? http://trep.trlevel.de/opentomb/files/tr_soundtracks_for_opentomb.zip

If not then likely the file name is not matching what OT wants.

**Comment by GlacialTurtle** [comment]
I can't download those files, it tells me 403 forbidden.

For Tomb Raider 1, I have the files extracted from the GOG release which they originally ship as mp3 but I convert to vorbis, files 02.ogg to 10.ogg.

Tomb Raider 4 is now working after renaming all files to lowercase, which is strange as I tried previously and it didn't work (I just re-exported with audacity).

**Comment by monreal** [comment]
I can confirm the download does not work ATM. I found the audio on https://opentomb.earvillage.net/, however I am not sure about the file names.

**Comment by GlacialTurtle** [comment]
This is what works for me, based on the GOG releases.

Tomb Raider 1 audio must be 3 numbers e.g. 001.ogg, so you'll need to add a leading 0 to all files after converting from mp3 to OGG Vorbis. OpenTomb still complains about missing music though.

Tomb Raider 2 ships as Vorbis already, except you'll need to replace "Track" in each filename with 0 e.g. 001.ogg instead of Track01.ogg.

Tomb Raider 3 requires extraction from the .wad file and then converted to Vorbis, haven't done it myself though yet.

Tomb Raider 4 needs all files converted to Vorbis and then renamed to lower case on Linux.

All files should be placed in OpenTomb > data > tr1/tr2/etc. > audio.

**Comment by vvs-** [comment]
> OpenTomb still complains about missing music though.

Actually, OT requires PSX audio tracks. PC tracks are not supported.

> Tomb Raider 3 requires extraction from the .wad file and then converted to Vorbis

No, it doesn't in general. Though it is in supplied audio scripts out of the box.

> Tomb Raider 4 needs all files converted to Vorbis

The same as above.

**Comment by vvs-** [comment]
To be more specific, OT expects the file numbers should correspond to tracks 2-10 from PC version and the following tracks should correspond to [PC audio remapping project](http://www.glidos.net/audio.html). The exact mapping is defined in scripts/audio/soundtrack.lua and can be customized.

**Comment by TeslaRus** [comment]
PC audio tracks supports correctly if path is correct.

**Comment by vvs-** [comment]
To clarify even more. OT plays PC tracks but actually expects more tracks than there are in PC version.

**Comment by Madc30** [comment]
dd
