### ISSUE TITLE
Doppelganger has broken AI

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#455]
Doppelganger can't fall into trapdoor apparently because it has no collisions:
![screen_00000](https://user-images.githubusercontent.com/5171934/30220592-a47a235e-94c8-11e7-8745-b912bf1f4b93.png)

**Comment by TeslaRus** [comment]
collision is OK here... AI system (box fixing) disallow Doppelganger to fall and broke one's position; fixed in RPL branch;

**Comment by TeslaRus** [comment]
fixed in https://github.com/opentomb/OpenTomb/commit/d65a4d44418d11b8472767891bd1e38107065098

**Comment by vvs-** [comment]
Now it works, indeed.
