### ISSUE TITLE
Lara climbs on door and walks in wall

### ISSUE THREAD

**Issue by TheIndra55** [opentomb/OpenTomb#462]
In TR1 at st francis folly lara can climb on the door and walk into the wall

![screen_00001](https://user-images.githubusercontent.com/15322107/30651414-ed76ff26-9e25-11e7-9cc4-913878cbaccd.png)
![screen_00003](https://user-images.githubusercontent.com/15322107/30651429-f6de6112-9e25-11e7-9132-a0bba2cd0dae.png)

**Comment by vvs-** [comment]
Might be related to #201. But really, there are so many collision bugs/incompatibilities that it's very hard to distinguish their sources with any reliability. IMHO, at this stage it's more important to fix subsystems as a whole (e.g. physics) than chase all the small bugs here and there throughout the code. It'd be rather an already lost battle.

**Comment by TeslaRus** [comment]
should be better after https://github.com/opentomb/OpenTomb/commit/e6b1d41d4c57c309c126927338b021921f44a091

**Comment by vvs-** [comment]
Actually, there are no visible changes.

**Comment by TeslaRus** [comment]
ok, I wrongly test it in Midas Palace

**Comment by vvs-** [comment]
Duplicate of #201.
