### ISSUE TITLE
Can't change to next level

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#466]
https://github.com/opentomb/OpenTomb/blob/ad435d0279b3d4607edd464b52ad739d536a0a24/src/gameflow.cpp#L193
This doesn't work if there is no more levels past this one, e.g. _The Hive_.

**Comment by TeslaRus** [comment]
Can't understand what is incorrect...
I need info: how to reproduce, expecting result, actual result...

**Comment by vvs-** [comment]
OT can't change to next level on _Lara's Home_ and _The Hive_ levels. Using `gameflowSend(GF_OP_LEVELCOMPLETE, 0)` or ENDLEVEL trigger failed at the above source line, because there is no next level.

**Comment by Gh0stBlade** [comment]
Gameflow worked at one point. Too many changes over complicated and polluted the class I initially wrote. I trimmed the code down a long while ago but I'm not sure why this doesn't work all of a sudden. Is there a recent change which might have caused this?

**Comment by vvs-** [comment]
Of course it is. There was refactoring on 29-30 of august.

**Comment by vvs-** [comment]
BTW, I was wrong about _Lara's Home_. I guess that's because I've tried old `setgamef(1,0)` to change level.

But I'm correct about _The Hive_, because there is no level 0 in _Unfinished business_.

**Comment by vvs-** [comment]
Hmm... I was to quick to decide. There is something fishy with _Lara's Home_ though. It works for the first time, but if you cycle through all the levels then it breaks.

**Comment by vvs-** [comment]
Actually, it fixed only _The Hive_. Try `setgamef(1,19)` and then `gameflowSend(GF_OP_LEVELCOMPLETE,0)` two times in a row. You can change to the next level after the first. It's the same problem that was previously with _Lara's Home_, so definitely by other reason.

**Comment by TeslaRus** [comment]
two times in a row... one enter press : two commands call? if current level id is out of range then gameflowSend(GF_OP_LEVELCOMPLETE,0) will not work. ok, I know where additional check is necessary

**Comment by vvs-** [comment]
> two times in a row... one enter press : two commands call?

No, this is just an idiom. That means that you should run the same command twice avoiding any other action in between. I mean that doing it the first time you will change to next level, but on the second time you won't.
