### ISSUE TITLE
Audio driver: (null)

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#477]
https://github.com/opentomb/OpenTomb/blob/c879a7814ef9e32e193c66152abbd1d65f4b35e8/src/audio/audio.cpp#L739
Is this the right place to query current driver? There is no SDL_Init(SDL_INIT_AUDIO) anywhere in the code. Despite of that, audio still works correctly.

**Comment by TeslaRus** [comment]
really - it should be deleted here... SDL audio initialized (my case) in SDL backend in AL library. In system AL case "Con_Printf("Audio driver: %s", SDL_GetCurrentAudioDriver()); " is wrong. Good idea, thanks =)

**Comment by TeslaRus** [comment]
fixed here https://github.com/opentomb/OpenTomb/commit/73e424ee4d3b131d4cc41e68b156272e649db8b3
