### ISSUE TITLE
Lara can swim while holding guns

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [opentomb/OpenTomb#478]
Hi,

I was playing Tomb Raider Unfinished Business on Xubuntu 17.10 64 bits. I equipped guns by pressing several times shotgun key / guns key / action key until guns appear. Then I jumped into water, but guns did not return to the holster. I was able to shoot too.

![capture d ecran_2017-11-04_13-15-50](https://user-images.githubusercontent.com/4292857/32405302-201ceb60-c163-11e7-80a6-09e9694e0e30.png)

**Comment by TokyoSU** [comment]
it's cool no ? xD

**Comment by RICCIARDI-Adrien** [comment]
Sure ! No need for harpoon and ammunitions are unlimited.
You're right, this is not a bug but a feature !

**Comment by TokyoSU** [comment]
TR1 affected in last src.
TR2, TR3 is possibility affected too.

**Comment by TeslaRus** [comment]
should be fixed after https://github.com/opentomb/OpenTomb/commit/74b7ca2b03d1f8c24881968132386cb97b56c6f1

**Comment by TeslaRus** [comment]
tested, fixed
