### ISSUE TITLE
Travis CI:Build Lua Error

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#479]
Just a detail but Travis have an error:

E: Unable to locate package liblua5.3-dev
E: Couldn't find any package by glob 'liblua5.3-dev'
E: Couldn't find any package by regex 'liblua5.3-dev'

liblua5.3 is unable to find !

**Comment by vvs-** [comment]
I guess that Travis just doesn't support this particular version.

**Comment by TeslaRus** [comment]
maybe use something like download tar.gz lua sources (I do not want to make LUA build in... but it is option) and build / install it under Travis scripts...

**Comment by TeslaRus** [comment]
fixed in https://github.com/opentomb/OpenTomb/tree/build_update
but I want to replace vorbis by stb_worbis first (simplify libs) and next integrate ogg support to fmv code part (remove stb)

**Comment by vvs-** [comment]
Well yes, it sorta fixed Travis build. But the common problem with in-tree libraries is that they miss any fixes and improvements applied by OS distribution, which might include security and compatibility fixes. The distribution maintainers won't be pleased and in fact the absence of in-tree libraries is usually a requirement. Though, I guess it's just an unavoidable evil at this state.

**Comment by TeslaRus** [comment]
yep + current scripts requires 5.3 features (bit**u**32 nasty usage was replaced by C-style operators)

**Comment by TeslaRus** [comment]
Merged
