### ISSUE TITLE
TR1 Object Refactoring for Engine (Structure)

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#483]
Hello all,
___
Object define is in script folder: 3 files (src possible).

why here ? and possibility to rewrite id for all TR (with 5 enum (6 for unkwown) (like TRLE editor)) ?
possibility to move it in engine and in 2 files (cpp/h) (objects.h xD) ?
___
object id (rewrite no emty slot):
ID / NAME
0#LARA
1#LARA_PISTOL
2#LARA_SHOTGUN
3#LARA_MAGNUM
4#LARA_UZI
5#LARA_MUTANT
6#WOLF
7#BEAR
8#BAT
9#CROCODILE_LAND
10#CROCODILE_WATER
11#LION_MALE
12#LION_FEMALE
13#PANTHER
14#GORILLA
15#RAT_LAND
16#RAT_WATER
17#T-REX
18#RAPTOR
19#WINGED_MUTANT 
20#CENTAUR_MUTANT
21#MUMMY 
22#LARSON
23#PIERRE
24#SKATEBOARD
25#SKATEBOARD_KID
26#COWBOY
27#MR_T
28#NATLA_MUTANT
29#GIANT_MUTANT
30#BREAKABLE_FLOOR
31#SWINGING_BLADE
32#SPIKE
33#BOULDER
34#DART
35#DART_EMITTER
36#SLAMMING_DOOR
37#SWORD_OF_DAMOCLES           -- Animated with StateControl ?
38#THOR_HAMMER_HANDLE
39#THOR_HAMMER_BLOCK+
40#ELECTRICITY                              -- Dance Floor but mortal xD (define random electricity with mesh ?)
41#DOOR_LOCK
42#PUSHABLE_OBJECT1
43#PUSHABLE_OBJECT2
44#PUSHABLE_OBJECT3
45#PUSHABLE_OBJECT4
46#PUSHABLE_OBJECT5
47#FALLING_BLOCK
48#SWORD_OF_DAMOCLES_DONE      -- Ended (no anim / no statecontrol / less ram use)
49#SWITCH_TYPE
50#UNDERWATER_SWITCH
51#DOOR_TYPE1
52#DOOR_TYPE2
53#DOOR_TYPE3
54#DOOR_TYPE4
55#DOOR_TYPE5
56#DOOR_TYPE6
57#DOOR_TYPE7
58#DOOR_TYPE8
59#TRAPDOOR1
60#TRAPDOOR2
61#BRIDGE_FLAT
62#BRIDGE_TILT1
63#BRIDGE_TILT2
64#SYSTEM_PASSPORT_OPEN
65#COMPASS
66#ROUAGE1
67#ROUAGE2
68#ROUAGE3
69#SYSTEM_PASSPORT
70#MEMCARD_INV             -- console
71#CRYSTAL                        -- console
72#CRYSTAL_INV                -- console save ?
73#SYSTEM_VIDEO
74#SYSTEM_SOUND
75#SYSTEM_CONTROL
76#PISTOL_INV
77#SHOTGUN_INV
78#MAGNUM_INV
79#UZI_INV
80#PISTOL_AMMO_INV
81#SHOTGUN_AMMO_INV
82#MAGNUM_AMMO_INV
83#UZI_AMMO_INV
84#MEDIKIT_SMALL
85#MEDIKIT_LARGE
86#PUZZLE_ITEM1_INV
87#PUZZLE_ITEM2_INV
88#PUZZLE_ITEM3_INV
89#PUZZLE_ITEM4_INV
90#PUZZLE_HOLE1
91#PUZZLE_HOLE2
92#PUZZLE_HOLE3
93#PUZZLE_HOLE4
94#PUZZLE_DONE1
95#PUZZLE_DONE2
96#PUZZLE_DONE3
97#PUZZLE_DONE4
98#PUZZLE_ITEM_COMBINE_INV           -- Midas Puzzle (ingot) Iron -> Gold
99#KEY1_INV
100#KEY2_INV
101#KEY3_INV
102#KEY4_INV
103#KEY1_HOLE
104#KEY2_HOLE
105#KEY3_HOLE
106#KEY4_HOLE
107#ALTAR_SCION
108#ALTAR
109#SCION
110#CENTAUR_MUTANT_STONE
111#GUN_FLASH
112#CENTAUR_DART_MESH                 -- In CENTAUR_DART object to define move ?
113#CENTAUR_DART                            -- Explosion in Impact
114#COULING_OF_LAVA
115#MUTANT_EGG
116#BOAT                                             -- Natla Mine (can move if trigger)
___
2D Sprites not included (weapon/effect/item/plant)

**Comment by vvs-** [comment]
Bear in mind that OpenTomb is intended for creating modifications. The original games are supported for compatibility reasons, so different editors or levels could be used. But the goal is to move everything as much as possible to Lua scripts and out of the engine. Also, most components are implemented differently than in original to improve engine capabilities and lift restrictions. For example all collisions and physics is totally different. At one point even triggers were compiled to Lua code on the fly, but after development split into several branches the present `master` took a different approach.

**Comment by TokyoSU** [comment]
Thanks for reply,

"but the goal is to move everything as mush as possible to lua script and out of the engine"
so accessible to everyone after release a game (OpenTomb Release not src),
is too problematic if everyone can change damage of weapon or downgrade hp of mobs ?

- For now is not possible to rewrite any object id (OpenTomb)
(error when load game (black screen or crash)).
- In TRLE/TRNG editor is impossible to place sprite (DxTRE3D too).
- Is a labyrinth with 3 files but just 1 or 2 files is:
1) Fast Loading.
2) More comment to description of item.
3) Fast to Search and Rewrite.
but 3 files with 2 files similar is labyrinth, is just what file do what or do if.

- TR1/4/5 use a stored sound (for old tr is problematic like TR1 because Editor (Sound FX is compiled with TR4 system and Wad is corrupted for it (Extracted for TR Games not TR4) .
if all game (TR1 -> TR5) can use main.sfx is a good thing ?
yes need more ram to load but just 1 files is more good to 500 level no (500 is an exemple) ?
and cdaudio is good too just 1 files (like archive to have less mb) can be a good advancement.
and 2 is crypted so no rewrite or mods than can crash it (no backup problem).
just idea :)

PS: sorry for bad english.

**Comment by vvs-** [comment]
OpenTomb was never intended to make a mod protected from modifications by end user. After all it's against a free software spirit (and probably its licenses too).

It's not enough to change just one constant in scripts, e.g. many things are contained in level files themselves. But in general OT is not even reached a beta stage, so many bugs exist of course.

**Comment by TokyoSU** [comment]
So if i want All TR weapon in TR1 is not possible ?

**Comment by vvs-** [comment]
Of course it's possible, but you need to place all corresponding animations in level files and add all needed data structures and related functions into scripts. The mere possibility doesn't mean that this could be done automatically. This is in contrast to TRLE where you can only change level files. In original Core engines all entities and their behavior were hardcoded. And in TRNG it depends on modified binaries which only one person is able to do. But even in OpenTomb it's not trivial and requires some knowledge of the engine internals.
