### ISSUE TITLE
Black display on Linux

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [opentomb/OpenTomb#484]
Hello,
I just compiled latest game version (447c7eb09fa20b285fa89929b76f3acb80bdd586) on Xubuntu 17.10 64 bits and I get a black screen when I start the game.

Here is what I get with my custom configuration Lua scripts (same than the official ones except key bindings and setgamef(1, 1); in autoexec to start TR1 first level) :
![capture d ecran_2017-12-17_23-32-45](https://user-images.githubusercontent.com/4292857/34084570-308ca764-e383-11e7-8634-6c7fceed1c2f.png)

Here what I get with official config.lua and autoexec.lua (the interesting part is that the door is visible) :
![capture d ecran_2017-12-17_23-33-25](https://user-images.githubusercontent.com/4292857/34084582-70e177ae-e383-11e7-8509-eaea695d7eb3.png)

**Comment by vvs-** [comment]
According to #481 OpenTomb doesn't work properly on Ubuntu 17. Probably because of some bugs/incompatibilities in that version.

**Comment by TokyoSU** [comment]
Move to 16.04 for work properly 👍

**Comment by TeslaRus** [comment]
looks like LUA version problem (I have black screen too if LUA scripts / saves was broken)... last sources requires LUA 5.3+ version (no more bitu32.xxx)
+ after some engine updates old saves does not work properly...

**Comment by RICCIARDI-Adrien** [comment]
I built the right "last version" this time (thank you @vvs- for pointing that), and it worked out of the box. Some commits between 447c7eb09fa20b285fa89929b76f3acb80bdd586 and 9a35d701dc8b9c60659144a9d72b99d29361deae seem to have fixed the issue.
![capture d ecran_2017-12-18_20-18-02](https://user-images.githubusercontent.com/4292857/34123780-0044e590-e431-11e7-877b-bb6b1b74ea39.png)

**Comment by RICCIARDI-Adrien** [comment]
No more black screen since this commit, this issue can be closed and reopened if needed.
