### ISSUE TITLE
Code::Block OpenAL

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#485]
when i add libz.a or zlib.lib in linked library
and compile the project i have an error:
zlib.h is missing.

i dont know, all file work fine but not zlib.
Image 1 with Error:
![error1](https://user-images.githubusercontent.com/27679699/34456479-7ffb215e-ed97-11e7-904a-389fccc61e21.png)
Image2 with File Left (updated last version):
![error2_withfile_left](https://user-images.githubusercontent.com/27679699/34456480-87e8eafe-ed97-11e7-8d87-e3dc956db2bf.png)

how to fix the zlib not found ?
PS: i download the zlib file here (developer): http://gnuwin32.sourceforge.net/packages/zlib.htm

**Comment by vvs-** [comment]
Hrm... You need to add zlib.h to headers path as well, of course.

**Comment by TokyoSU** [comment]
Fixed with this tutorial of adding SDL2: FRENCH: http://www.supinfo.com/articles/single/649-comment-installer-sdl-20-codeblocks-windows
TODO: Change this SDL2 to last version the version 2.0.3 is bugged !

**Comment by TokyoSU** [comment]
Sorry but now after fixed all import i get:
![error1](https://user-images.githubusercontent.com/27679699/34461662-813c5c60-ee30-11e7-80c4-fe9c87d4ec41.png)

**Comment by vvs-** [comment]
You should not compile headers, they must be included implicitly through their corresponding .c files.

**Comment by TokyoSU** [comment]
Need to compile lib manual ? Not already compiled ?
But this error is with FMV.
Need to include fmv to compile & linker ?

**Comment by vvs-** [comment]
You did include `bitstream.h` as a source file in your project, didn't you? You should include it only as a header, not as a source.

**Comment by TokyoSU** [comment]
I cant test it now, thanks for help, if i have other problem when compile i
reopen it.

**Comment by TokyoSU** [comment]
but look:
![source](https://user-images.githubusercontent.com/27679699/34462052-4de42edc-ee3b-11e7-9289-43d9a6e3d064.PNG)
i have bitstream.h in header but not source.

**Comment by TeslaRus** [comment]
src updated: added include to bytestream.h

**Comment by vvs-** [comment]
@TeslaRus Thanks.

@TokyoSU If that's the case then why it's in the tab for compiled sources in that screenshot with error message? First of all you might have it both as a source and a header and this isn't visible in the screenshot. And the source files which include `bitstream.h` compile just fine. There is no reason why it should be compiled separately.

**Comment by TokyoSU** [comment]
Thanks TeslaRus is fixed but now i have:
![fixed](https://user-images.githubusercontent.com/27679699/34462118-83f0241c-ee3c-11e7-980f-ab051edb435a.PNG)

**Comment by TeslaRus** [comment]
should be p->eof instead ->eof

**Comment by vvs-** [comment]
Yet again: you should not compile `bytestream.h`. TeslaRus just fixed some cosmetic issue which presently should not affect any real case. Your error seemingly stem from compiling `bytestream.h` separately. Please, check that it isn't included in sources section of the project. Better yet don't create Code::Blocks project file manually, try CMake instead, which is a preferred way.

**Comment by TeslaRus** [comment]
in file option uncheck "compilable" or something like that
P.S. I use Netbeans IDE

**Comment by vvs-** [comment]
@TokyoSU BTW, the code in the above screenshot doesn't match the code in repository. Are you sure that you didn't change it accidentally?

**Comment by TokyoSU** [comment]
@TeslaRus Netbeans is more compatible ?

@vvs- The folder of opentomb have already a code-block project, i just used it, but is terribly old.
i removed bytestream.h of headers, and fixed

**Comment by vvs-** [comment]
That explains it. This obsolete project file should be removed from repository, then.

**Comment by TokyoSU** [comment]
i have added basic lib with command:
![compiler](https://user-images.githubusercontent.com/27679699/34462221-2f977002-ee3f-11e7-8143-3ab22c76c0df.PNG)
and include & lib:
![library](https://user-images.githubusercontent.com/27679699/34462228-689e62ac-ee3f-11e7-84e2-530cf49500c7.PNG)
![include](https://user-images.githubusercontent.com/27679699/34462229-6a53524c-ee3f-11e7-9a6d-1a8cf3cdcd62.PNG)
i have missed a library ? now i have this error:
![error](https://user-images.githubusercontent.com/27679699/34462237-98e6f262-ee3f-11e7-834d-e2645589a2de.PNG)

**Comment by TeslaRus** [comment]
yep C::B project files should be deleted... they are very old

**Comment by TokyoSU** [comment]
need to have linux now or just use netbeans ?

**Comment by TokyoSU** [comment]
@TeslaRus You have C/C++ version or All ?

**Comment by vvs-** [comment]
@TokyoSU All your problems come from the missing SDL2. That'd explain everything above.

**Comment by TokyoSU** [comment]
but if you look:
![compiler](https://user-images.githubusercontent.com/27679699/34462221-2f977002-ee3f-11e7-8143-3ab22c76c0df.PNG)
SDL2 is here

**Comment by TeslaRus** [comment]
GCC uses only *.a libs;
*.lib for MS Visual Studio

**Comment by TokyoSU** [comment]
but after change a problem (now working) i can compile it now

**Comment by TokyoSU** [comment]
SDL2 is here but on compile have:
![error](https://user-images.githubusercontent.com/27679699/34462425-06c83e90-ee44-11e7-9164-d26fc68c5d6f.PNG)

**Comment by vvs-** [comment]
You should have all libraries compiled by a compatible compiler.

**Comment by TokyoSU** [comment]
SDL2: https://www.libsdl.org/download-2.0.php (have lib in)
ZLIB: http://gnuwin32.sourceforge.net/packages/zlib.htm
PNG: http://gnuwin32.sourceforge.net/packages/libpng.htm

and all other is included with Code::Blocks WinGW compiler

**Comment by TokyoSU** [comment]
windows is very problematic ...

**Comment by vvs-** [comment]
All libraries obtained separately from the compiler are not guaranteed to be built by the same compatible version.

And including all libraries in-tree will ruin its compilation and distribution under different OSes.

**Comment by TokyoSU** [comment]
i am an idiot, i not correctly spelled the directory of SDL2 XD
but now i not have SDL2_platform.h T.T

**Comment by TokyoSU** [comment]
Sorry but now after fixed SDL2,
i have problem with OpenAL but is only .lib and not .a
i just have include files in v1.16.

the error:
![openal_issue](https://user-images.githubusercontent.com/27679699/34487664-9e813182-efd5-11e7-8c10-fd227fc0c21b.PNG)
