### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by filfreire** [opentomb/OpenTomb#488]
**Purpose:** Follow Github's [guideline](https://github.com/blog/1184-contributing-guidelines) of having a separate contributing file, that helps potential contributors with guidelines for contribution.

/cc @TeslaRus

**Comment by TeslaRus** [comment]
thanks, hope I will found time to add CONTRIBUTING.md in 2 - 3 days

**Comment by TeslaRus** [comment]
Done in https://github.com/opentomb/OpenTomb/commit/d06c1fa721576e4dbfdaf052c536df33dfd51d7b
