### ISSUE TITLE
Overlapping rooms geometry produces visual artefacts

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#49]
This is visible over certain angles only, e.g. `setgamef(1,7)` `setEntityPos(player,38335,45407,4352,275,0,0)` or `setgamef(5,1)` `setEntityPos(player,52875,42308,3584,65,0,0)`. By rotating the camera the artifacts disappear. It may be related to #40.

Here's a [link](https://gist.github.com/vvs-/19fb0c37391794fdf051) to screen shots.

**Comment by TeslaRus** [comment]
It is overlapping rooms conflict... I though about these bugs too and I have one idea, how to fix it, but will it be enough good solution: to add stencil test to room rendering?

**Comment by vvs-** [comment]
You mean that it's caused by [Z-fighting](http://en.wikipedia.org/wiki/Z-fighting)? Although, I'm not a specialist in CG.

**Comment by TeslaRus** [comment]
In TR different rooms (not alternative) may have some shared space, it is not Z-fighting... In engine uses VBO and if room has only one active frustum, the whole room mesh will be rendered. If both overlapped rooms has active frustums than we can see described bugs.

**Comment by vvs-** [comment]
Thank you for your explanation. So, it wasn't the primary reason here. Though, the fix could be quite similar I suppose.

**Comment by TeslaRus** [comment]
I add stencil frustum test in commit 3be9b71f77f7db0da609b70decc547036c792861 + add some information to TR forum; TR3, map 13 (Area 51 map) looks better, but some glitches still exists (described in forum... but I found easy solution... heh...)

**Comment by vvs-** [comment]
It was also on *All Hallows* level. Now all these artifacts seems to be fixed. I don't see any bad side effects except it's slower.

**Comment by vvs-** [comment]
I was speaking too soon. Yes, there are problems in *Old Mill* level.

**Comment by TeslaRus** [comment]
I test new system - it is really slow (fps drops to 30 on my old PC). I think to add condition to use frustum test only with overlapped rooms.

**Comment by vvs-** [comment]
Much faster and better now. But still a problem remains. At `setgamef(5,10)` `setEntityPos(player,78222,46130,-5376,84,0,0)` rotating camera to the left makes a pillar disappear from view.

**Comment by TeslaRus** [comment]
I check setgamef(5, 10) and setEntityPos(player,78222,46130,-5376,84,0,0) and must say one: why pillar are located in room 18 (where other pillars located, in left of Lara) instead room 86 where is pillar's really position!? Engine can't correctly render things that are located pretty incorrectly... It can be fixed only by new scripts functions and some level scripting.

**Comment by vvs-** [comment]
Here's another: `setgamef(1,1)` `setEntityPos(player,33909,74149,-2048,0,0,0)`, then rotate to the left. This one appeared after @cochrane recent VAO code merged in.

**Comment by vvs-** [comment]
Seems that original bug is fixed now.

**Comment by vvs-** [comment]
@TeslaRus:
> must say one: why pillar are located in room 18

How did you check it? Because the debug marker in OpenTomb seems to completely ignore these statics and used whatever room geometry happened to be behind it.

**Comment by vvs-** [comment]
Related to #367. It's arguable that OT frustums should work like this in _Old Mill_. There are incompatibilities in portals code.
