### ISSUE TITLE
final compile error

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#493]
![final_compile](https://user-images.githubusercontent.com/27679699/34624394-6a8ec704-f255-11e7-8c73-b3099cbf2b60.PNG)

all library and include is working
error is related to OpenAL / SDL2 / zLib but all correctly linked with include !
i dont know why compile not working.

_more info:_

Linker Setting:
![linker](https://user-images.githubusercontent.com/27679699/34624491-c836a80e-f255-11e7-8e14-c19a82d4f38d.PNG)
INFO:
_Project / Debug / Release have this !_

search (include):
![compiler](https://user-images.githubusercontent.com/27679699/34624522-ee16bf32-f255-11e7-92ad-a8e3daf4f3ec.PNG)

search (library):
![library](https://user-images.githubusercontent.com/27679699/34624554-0d29eb10-f256-11e7-9217-f6f92b73dcd3.PNG)

what version your used @TeslaRus for: OpenAL and zlib (and if you have other files imported)
PS: i view this too: [moddb tutorial](http://www.moddb.com/games/opentomb/tutorials/how-to-compile-opentomb-in-windows-using-codeblocks-ide)

**Comment by vvs-** [comment]
That tutorial is almost five years old. Many things have changed since then. I'm afraid that nobody have built OT with C::B for years. The only somewhat widely tested way to automatically build OT is CMake on Linux. Everything else is either untested or assumed some non-obvious steps involved. There are no regular builds of OT except on Travis-CI which use CMake on Linux also.

**Comment by TokyoSU** [comment]
With Linux is too easy to build it but its not possible to use WADMerger or TRNG Editor :(

**Comment by TeslaRus** [comment]
old C::B project files was deleted from repo; use CMake to compile project;

**Comment by TeslaRus** [comment]
![ide](https://user-images.githubusercontent.com/11921962/34627866-4db32148-f273-11e7-8428-70817f2a07cd.png)
![c_options](https://user-images.githubusercontent.com/11921962/34627867-4dd2facc-f273-11e7-9b3e-f9884aff5ef2.png)
![cpp_options](https://user-images.githubusercontent.com/11921962/34627868-4df34750-f273-11e7-822f-af8aaa56dcf9.png)
![linker_options](https://user-images.githubusercontent.com/11921962/34627869-4e101588-f273-11e7-9a00-298d0c59dbc7.png)

**Comment by TokyoSU** [comment]
Thanks TeslaRus
