### ISSUE TITLE
Add Project for Windows

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#500]
OpenTomb not have projects on windows but the tutorial is old or dead,
Is easy to compile on linux but very hard on windows, so i have a request for opentomb:
___
- [REMOVE/REWORK] Windows Project Tutorial from README.md
> On Windows, you can also compile it from Code::Blocks IDE (project file is also provided). Alternatively, you can manually compile it in Code::Blocks by recursively adding all source files from /src directory, and adding these libraries in Linker Settings under Project Build options:
- [ADD] Windows Project to OpenTomb
___
You are free to close this issues but please some person need project for Windows (x86 or x64).

**Comment by vvs-** [comment]
The reason why it's harder on Windows than on Linux is that Linux has all required libraries bundled with a compiler. This can't be changed by documentation alone - the required build environment is severely lacking. This is beyond the scope of a single project and is a lot harder than someone might think.

There used to be Windows nightly builds, but sooner or later volunteers lose their interest in investing their time to support it.

**Comment by TokyoSU** [comment]
Possibility to have Editor (Tomb Editor or Official (not NGLE)) on Linux ?

**Comment by vvs-** [comment]
Did you try wine? It supports even some copy-protected games, so there is a good chance.

**Comment by TokyoSU** [comment]
I not have PC with Linux,
So i need to create a dual-boot.
Need to test it 👍  thanks.
