### ISSUE TITLE
Weapon Bug / Bar Bug

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#501]
Lara can hold weapon when climb wall (2/3/4 click and more)
And "Air Bar" is empty?
Like it:
![weapon_bug](https://user-images.githubusercontent.com/27679699/34938039-1d3da6de-f9e7-11e7-91c0-4dda484f0e51.png)

**Comment by vvs-** [comment]
She can even hold it underwater. There are still far too many incompatibilities and unimplemented features.

**Comment by TeslaRus** [comment]
heh... I know strings with condition... state->control should be replaced by clean_action (StateControl_Lara, climb conditions)

**Comment by TeslaRus** [comment]
partially fixed in https://github.com/opentomb/OpenTomb/commit/d199c8f3bef75bb50cd9443eb411b9c565053da3

**Comment by RICCIARDI-Adrien** [comment]
She can also grab items while holding guns (tested on commit d199c8f3bef75bb50cd9443eb411b9c565053da3).
![capture d ecran_2018-01-21_19-29-11](https://user-images.githubusercontent.com/4292857/35197578-9fc94be0-fee1-11e7-8c0a-471ce3d94422.png)

**Comment by TeslaRus** [comment]
+ auto hide weapon in water is not implemented

**Comment by TeslaRus** [comment]
should be better after, but something should be wrong... https://github.com/opentomb/OpenTomb/commit/8c4754161b46921c7f0fa6dbb8df38255263e910

**Comment by TokyoSU** [comment]
I dont have Linux anymore on my PC,
so i cant check it but @RICCIARDI-Adrien can check it for me.
now, i just show advancement of opentomb,
good luck for the future.

**Comment by RICCIARDI-Adrien** [comment]
I've done some testing on Linux :
* Lara can't climb a wall while holding guns
* Air bar is displayed only when Lara is in some water, it starts flashing when remaining air amount is critical
* Lara automatically hides guns when jumping into water (and can't extract them while being in water)
* Lara can't grab an item (like a medipack) while holding guns

**Comment by TeslaRus** [comment]
I can rarely out of level by jumping and trying action and draw / hide weapon near wall, but it is collision bug

**Comment by TokyoSU** [comment]
you can close it if completely fixed 👍

**Comment by TeslaRus** [comment]
ok, If I will not find weapon bugs in some days - issue will be closed
but there are TR2, TR3, TR4, TR5...

**Comment by TeslaRus** [comment]
fixed again after refactoring https://github.com/opentomb/OpenTomb/commit/74b7ca2b03d1f8c24881968132386cb97b56c6f1

**Comment by TeslaRus** [comment]
tested, fixed
