### ISSUE TITLE
Translation into Spanish language

### ISSUE THREAD

**Issue by michaelizer** [opentomb/OpenTomb#510]
Greetings, I would like to contribute to the project by translating it into Spanish. Spanish is my native language so don't panic, but a lot of Spanish speakers are still limited by the language so this is primarily to help them.

Thanks in advance and for your time. Keep up the great work.

**Comment by vvs-** [comment]
Thanks. But all you need is a GitHub pull request where your work could be reviewed and approved for merge.

**Comment by michaelizer** [comment]
Very well, I'll start right away then. Thanks
