### ISSUE TITLE
Type mismatch in adpcm_data

### ISSUE THREAD

**Issue by carlo-bramini** [opentomb/OpenTomb#534]
Hello,
I did a full c++ compilation, including the c sources and I noticed some things.
One of these is a type mismatch for ff_adpcm_afc_coeffs[][] into adpcm_data.
Here, it is declared as int16_t:

https://github.com/opentomb/OpenTomb/blob/1fe14f278b36f6bc3438453bfa4e9fd8ccddc1de/src/fmv/codecs/adpcm_data.h#L43

but here it is declared as uint16_t:

https://github.com/opentomb/OpenTomb/blob/1fe14f278b36f6bc3438453bfa4e9fd8ccddc1de/src/fmv/codecs/adpcm_data.c#L109

Perhaps it would be worth to fix this, by declaring the values in the table as signed integers, like:

```
{ 0, 2048, 0, 1024, 4096, 3584, 3072, 4608, 4200, 4800, 5120, 2048, 1024, -1024, -1024, -2048 }
{ 0, 0, 2048, 1024, -2048, -1536, -1024, -2560, -2248, -2300, -3072, -2048, -1024, 1024, 0, 0 }
```
I could provide this patch if you think that it would be useful.

**Comment by TeslaRus** [comment]
merged
