### ISSUE TITLE
Error in audio_stream.cpp

### ISSUE THREAD

**Issue by carlo-bramini** [opentomb/OpenTomb#536]
I'm wondering if you could give a look here:

https://github.com/opentomb/OpenTomb/blob/40f08a4a5d0ca53393a2d3ce939a25db480a9d51/src/audio/audio_stream.cpp#L182

There is a function StreamTrack_Pause(), returning "int", but it does not return any value.
Thank you.

**Comment by TeslaRus** [comment]
yep, VC compiler does not compile it =)
thanks, will be fixed

**Comment by carlo-bramini** [comment]
It compiles fine now. Thank you. This issue could be closed.
