### ISSUE TITLE
Crash on Introduction Level

### ISSUE THREAD

**Issue by Sur3** [opentomb/OpenTomb#538]
Hi I tried playing OpenTomb from master yesterday, setgamef(1,1) seems to work but when doing setgamef(1,0) it crashes after saying "Welcome to my home. I take you on a guided " *crash*

**Comment by vvs-** [comment]
I can't reproduce the crash itself. But all other speech is muted after that introduction.

**Comment by Sur3** [comment]
True I tested on an other machine there it had the same problems as vvs- described, so probably something is wrong with the audio playback and my first test machine isn't tolerant about that.. xD

**Comment by TeslaRus** [comment]
In my case I have engine stuck on start (but it is other bug)... debug does not help.
I use Al Soft (TeslsRus/OpenTomb build in Al library) - no audio problems

**Comment by vvs-** [comment]
Not only that. Now I've got lock-up in introduction video. The stack backtrace shows that OpenAL code is the culprit. Most music triggered inside levels is not playing too indeed.

**Comment by vvs-** [comment]
After last commit which removed threading from codec all issues still persist.

**Comment by RICCIARDI-Adrien** [comment]
It seems to me that the Lara speech (like "Welcome to my home. I take you on a guided tour.") is played from an OGG file (029.ogg), is that right ?
However, this same speech is present in the level file (it's the sound ID 174 in my french version). Moreover, the level-provided speech is localized. Why don't play the level-provided speech instead of the OGG one ?

**Comment by vvs-** [comment]
All speech in Lara Home level is played by their corresponding triggers and they use CD audio tracks.

BTW, trigger debug `r_triggers` doesn't show level triggers anymore after recent changes. Probably it using OpenGL API in some way which isn't compatible with every driver. May be black on black, or it assumed that background is pre-filled with some particular color, I don't know.

**Comment by RICCIARDI-Adrien** [comment]
Some bugs described here should be fixed by pull request #595 merge. Could someone confirm that fixes are working for English and non-English games versions ? They work for French version.

**Comment by vvs-** [comment]
I confirm - sound and video now work in English version.

**Comment by Sur3** [comment]
Confirmed, Audio works and crash is also fixed.
