### ISSUE TITLE
Wrong Lara models in TR1 "Lara's Home" level

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [opentomb/OpenTomb#539]
Lara's model from TR1 Lara's Home level seems not planned to carry weapons. When putting guns to holster some parts of the classic Lara model appear :
![capture d ecran_2018-03-13_17-34-29](https://user-images.githubusercontent.com/4292857/37356695-d9c213f4-26e6-11e8-9cb9-7dd6f85bcc9c.png)
![capture d ecran_2018-03-13_17-34-38](https://user-images.githubusercontent.com/4292857/37356915-5b8e80ac-26e7-11e8-83a1-86cfb287bde5.png)
![capture d ecran_2018-03-13_17-34-51](https://user-images.githubusercontent.com/4292857/37357029-a6205226-26e7-11e8-88b3-9f541713c314.png)
![capture d ecran_2018-03-13_17-35-01](https://user-images.githubusercontent.com/4292857/37357031-a6660884-26e7-11e8-8f58-cf79261d166d.png)

**Comment by carlo-bramini** [comment]
Perhaps, the selection of weapons in that level should be just forbidden...

**Comment by RICCIARDI-Adrien** [comment]
I agree, I don't remember if it was the case in TR1 but in TR2 there are no weapons in Lara's home level.

**Comment by TeslaRus** [comment]
it is good that no NULL meshed here instead legs, back....

**Comment by RICCIARDI-Adrien** [comment]
Fixed in commit e14b247083516693a2176947b2af96112df80233.
