### ISSUE TITLE
CMakeFiles/temp.dir/build.make:92: recipe for target 'CMakeFiles/temp.dir/home/ghadeer/Desktop/ifrit/ifrit-4.1.2/src/ifrit-4.1.2/configure/ishellnew.cpp.o' failed

### ISSUE THREAD

**Issue by ghadeeralsheshakly** [opentomb/OpenTomb#544]
Hello,
I have been trying to build a program called ifrit.
I have already downloaded, VTK and QT5 as required but still I am getting this error:
![screenshot from 2018-04-18 22-27-02](https://user-images.githubusercontent.com/28873310/39078440-5619a368-44d8-11e8-83c3-503dc93af1fa.png)

**Comment by stohrendorf** [comment]
Please talk to the appropriate people, we're OpenTomb, not ifrit ;)
