### ISSUE TITLE
flares (tr3)

### ISSUE THREAD

**Issue by fastrgv** [opentomb/OpenTomb#547]
Are flares not yet implemented yet? (I'm afraid to enter a dark cave)

I found this Q+A with no mention of flares:
Q: Which features are currently available and which are not?
A: Basic physics interaction – you can walk, run, jump, climb, swim, grab and shimmy ledges, slide on slopes and stumble into walls. In TR2+, you can climb walls. In TR3+ levels, you can also monkeyswing, crouch, crawl and sprint. Lately, triggers and switch/keyhole interaction has been also implemented. Also, you can pick up items, use them on keyholes/puzzleholes, as well as combine item pieces in TR4/5. However, there's still no proper menu. Also, no AI or NPC has been implemented yet.

In any case, OpenTomb has already reached a fun and playable stage for such an awesome undertaking.  Nice work!

**Comment by vvs-** [comment]
In TR2 you can shoot windows, grab ladders on the fly after direct jump and perform a mid-air roll as well. But flares and vehicles are not implemented yet.

**Comment by fastrgv** [comment]
thx
