### ISSUE TITLE
Can't draw guns in TR1

### ISSUE THREAD

**Issue by rsantellan** [opentomb/OpenTomb#548]
Hi, 
I have check out last commit dee5090c0636ef25138a1908ea4a817e2da66b5c and I can't draw guns. I press F or f and nothing happens.
I like the new menu interface but I can't make it work.
Thanks in advance!

**Comment by vvs-** [comment]
Open inventory menu (ESC by default) then select pistols by using look keys (arrows by default) and press action (left CTRL by default). After that you should be able to draw by pressing F key.

**Comment by TeslaRus** [comment]
commands names was totally renamed to one commands set for UI, config, console. control_constants.lua contains comments with actual commands names.

**Comment by rsantellan** [comment]
@vvs- Doing what you told make me draw the guns. Thanks a lot.
