### ISSUE TITLE
Need Constant Value

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#554]
https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/skeletal_model.c#L52 at model->mesh_count 
"skeletal_model_p model" need a constant value in windows visual studio 2017 !

**Comment by TokyoSU** [comment]
#FIXED

**Comment by Gh0stBlade** [comment]
That line is blatantly illegal. How does this compile properly. 

Should use malloc (c) or new (c++) to allocate dynamic sized arrays.

Just change it to 

uint16_t* parents = new uint16_t[model->mesh_count]; 

Then delete[] at the end.

Tesla Rus will probably use malloc in a patch.

**Comment by vvs-** [comment]
No, it's perfectly legal in C99: https://en.wikipedia.org/wiki/Variable-length_array

**Comment by TokyoSU** [comment]
@Gh0stBlade i already tested it but uint16_t return error and new is undefined.
@vvs- with c++17 no :x

it's just model->mesh_count error and game launch correctly in windows :x

**Comment by vvs-** [comment]
@TokyoSU You shouldn't compile this file as C++ because it's just plain C. It's set as C99 in OT project file and should be set accordingly in any other project file, including VS.

**Comment by TokyoSU** [comment]
#FIXED with malloc function thanks @Gh0stBlade 
Image:
![winopentomb](https://user-images.githubusercontent.com/27679699/44139250-cb096114-a076-11e8-83bb-3eee4c884186.PNG)
but for launch it, i need the WinXP SP3 Compatibility ! any idea how to fix it ?

**Comment by TokyoSU** [comment]
fixed in [skeletal_model.c](https://github.com/opentomb/OpenTomb/blob/14574b5fb6c903add706b76fc4bbae73097b866a/src/skeletal_model.c#L52) maybe :x

**Comment by TokyoSU** [comment]
#FIXED
