### ISSUE TITLE
Uninitialized Variable

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#555]
Variable x0, y0 are uninitialized !

TEXT:
https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/core/gl_text.c#L152
https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/core/gl_text.c#L153
GUI:
https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/gui/gui_obj.c#L279
https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/gui/gui_obj.c#L280
- Is really a error ?

**Comment by Gh0stBlade** [comment]
What compiler?

**Comment by TokyoSU** [comment]
the same, C/C++17 visual studio with C++14 flag

**Comment by Gh0stBlade** [comment]
Try initialise them to 0

**Comment by TokyoSU** [comment]
#FIXED
thanks but variable like int are already initialized at 0, so compiler is crazy :x
