### ISSUE TITLE
Can't turn off FPS counter

### ISSUE THREAD

**Issue by PGunnii** [opentomb/OpenTomb#556]
I've tried the console commands (which apparently aren't recognized), even editing the autoexec and the config lua files - nothing. "show_fps(0)" doesn't work, neither do any similar commands ("showfps", "fps", "hidefps", etc.)

**Comment by TokyoSU** [comment]
you have it in autoexec at "cvars.show_fps = 1;" turn it to 0 but for me it's not working the fps command ignore it !, not implemented ?

**Comment by vvs-** [comment]
This variable isn't used anywhere in the code.

**Comment by PGunnii** [comment]
Strange. Using the "help" command lists "show_fps". Is there any other way to turn off the FPS counter in that case?

**Comment by TokyoSU** [comment]
i tested show_fps but used 1 or 0 have no effect.

**Comment by vvs-** [comment]
The help command contains obsolete information. It might have been implemented in the past or was planned for the future. I'm not sure.

**Comment by Gh0stBlade** [comment]
Closing since PR is merged.
