### ISSUE TITLE
MeshTree. How to build a Model?

### ISSUE THREAD

**Issue by neo-expert** [opentomb/OpenTomb#562]
I am trying to render a tr4 Level properly withhin an Android APP. Everything works except the Entities.
Here is the Renderer:
https://gitlab.com/neoexpert/android-tr4
and here is the Level Parser:
https://gitlab.com/neoexpert/tr4
you can test the APP here:
https://play.google.com/store/apps/details?id=com.neoexpert.tr4

I have some problems by understanding the MeshTree... How does it work? 
I tried to render all the meshes from model.startingMesh to model.startingMesh+model.numMeshes,
but it shows only laras torso...

**Comment by Gh0stBlade** [comment]
Unfortunately, we cannot provide support for third party applications. As the source code for OpenTomb is available you should be able to read it and adapt it to your needs.
