### ISSUE TITLE
[BUG] medipack quit problem

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#572]
when i use a small / large medipack, and it is the last, the inventory freeze and not quit !
image:
![medi_bug](https://user-images.githubusercontent.com/27679699/49301495-05edb800-f4c5-11e8-8043-b91fb1e88bdd.PNG)

**Comment by TeslaRus** [comment]
fixed in commit 14574b5fb6c903add706b76fc4bbae73097b866a

**Comment by TokyoSU** [comment]
thanks :)
