### ISSUE TITLE
attribute problem

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#575]
i have tested 2 or 3 time to found a solution about this problem but no attribute exist in visual studio :x 
i can use alignas to align it to 16bits :x i not very tested about it.
after tested i dont view any change :x

**Comment by TokyoSU** [comment]
reference of #573
and for alignas -> [link](https://en.cppreference.com/w/cpp/language/alignas)

**Comment by TeslaRus** [comment]
without alignas(16) in some cases engine crashes every run (GCC 4.8 may be)
it is Bullet library requirement...

**Comment by TokyoSU** [comment]
i play without alignas(16) and engine not crash for me ! already aligned in windows ?

**Comment by TeslaRus** [comment]
compiler depended behavior ;-)

**Comment by TokyoSU** [comment]
#FIXED
