### ISSUE TITLE
Weapons mismatch in TR1 UB

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [opentomb/OpenTomb#576]
Lara does not always equip the right weapon in UB :
* when selecting shotgun, magnums are equipped
* when selecting Uzis, shotgun is equipped

Other weapons seem to work.

**Comment by TokyoSU** [comment]
sure that id in items.lua script is not good, i will check it now and fix it tomorrow.
- sound is good when firing ?

**Comment by TokyoSU** [comment]
you can download the fix (items.lua in scripts->inventory) and replace the old file, and check if is fixed, if you have this bug after this fix, its sure that is animation refactoring than cause the bug.

**Comment by TokyoSU** [comment]
i have updated the src to lastest release by @TeslaRus and the bug is fixed with the items.lua !

**Comment by RICCIARDI-Adrien** [comment]
I confirm the bug is fixed by your items.lua modification.
I will close the issue when the fix will be merged to this repo.
Thank you !

**Comment by TokyoSU** [comment]
Fixed by @TeslaRus in update 2a930fe

**Comment by RICCIARDI-Adrien** [comment]
Uzis are not working in UB in commit 2a930fe3379441467b0c8a1cb082002c943ca4db, but they were working in the TokyoSU modified items.lua.

**Comment by TokyoSU** [comment]
@TeslaRus you have missing < in certain items_funcs[] :x sorry for it.

**Comment by TokyoSU** [comment]
#FIXED (cf87583)
