### ISSUE TITLE
level tr1_gold loading extension wrong ?

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#577]
- when i want to load the tr1_gold egypt level, and warning throw and i need to load a .TUB level but i have .PHD level, need the console version ?

**Comment by TokyoSU** [comment]
- after changed .TUB to .PHD, all working fine.

**Comment by TokyoSU** [comment]
but if i rename phd to tub the game crash :x

**Comment by vvs-** [comment]
Then there is something wrong either with those files or with Windows support. Try original TR gold from here: https://www.tombraiderchronicles.com/tr1/gold/demo.html

**Comment by TokyoSU** [comment]
thanks :)
