### ISSUE TITLE
Frustums are broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#59]
Happens in many places, e.g. *Caves* (see #49), *Area 51*, *Old Mill*, *Streets of Rome*. That's after VAO changes.

**Comment by cochrane** [comment]
I'm 90% certain that this has nothing to do with VAOs. Will check when I have more time

**Comment by vvs-** [comment]
I didn't say it's *because* of VAO, but it was definitely triggered by that changes. It worked just before VAO was committed.

**Comment by TeslaRus** [comment]
Hmmm: I test last frustum manager on renderer without VAO and no missed rooms; +In latest commit I can see missed rooms and correct frustums: http://cs622325.vk.me/v622325521/353e9/9QFXotdmH-E.jpg

**Comment by vvs-** [comment]
I think that VAO changes broke some invariant in the code. As a consequence it caused missed frustums.

**Comment by cochrane** [comment]
Hm, weird. No obvious reason for this bug springs to mind, so the investigation may take longer.

**Comment by cochrane** [comment]
Ah, I see, the problem is caused by the stencil code not using VAOs but using a shader that requires VAOs, so I gotta make that stencil test use VAOs as well. To work around until I'm done, you can disable the whole stencil test business.

**Comment by TeslaRus** [comment]
Thanks for fixing! Missing room bug was very annoyed; And how r_coll working without VAO?
