### ISSUE TITLE
Bug report [missing audio]

### ISSUE THREAD

**Issue by donno2048** [opentomb/OpenTomb#602]
Using the last release I get this error:
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
cannot open scripts/level/tr1/TRIGGERS.lua: No such file or directory
OGG: Couldn't open file: data/tr1/audio/060.ogg.
```

**Comment by vvs-** [comment]
What do you mean by "last release"? And on which platform? Can you present your directory tree for OpenTomb files, e.g. by `tree`, `ls -lR` or `find`?

The last (semi-)official release happened two years ago on Windows. I can't say anything about it. But if you meant `master` branch on Linux then I'd guess that you have a broken/outdated OpenTomb installation. There is no such file as `TRIGGERS.lua` and you should install ogg audio tracks before running the executable. Did you follow the `README` instructions?

**Comment by donno2048** [comment]
Oops missed it, thanks...
