### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by MikeOxLongLOL** [opentomb/OpenTomb#606]
Can someone build this for linux, i am currently too much of a bingus to compile this

**Comment by RICCIARDI-Adrien** [comment]
I built and ran master branch on Xubuntu 21.10, it's working. What problems are you facing ?

**Comment by MikeOxLongLOL** [comment]
> I built and ran master branch on Xubuntu 21.10, it's working. What problems are you facing ?

I have no problems, i am too lazy ass to compile it and i have no idea what i am doing
