### ISSUE TITLE
Package replacement?

### ISSUE THREAD

**Issue by RahRah80** [opentomb/OpenTomb#611]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate
Linux Mint Debian Edition 5

**Comment by RICCIARDI-Adrien** [comment]
Linux Mint Debian Edition 5 seems to be based on Debian 11.
Try `libpng-dev` instead, but I don't know if you will be able to compile.

**Comment by RahRah80** [comment]
Hello.

Ok.
Don't know if i can, but i will try.
I have linux full time since 2019, if don't know i'll find a way to
resolved. If i can't i ask you.

Thank you.

**Comment by RahRah80** [comment]
Hello.

It have already installed the libpng-dev

***@***.***:~/git/CroftEngine/build/src$ sudo apt-get install
libpng-dev
[sudo] password for rah-rah:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpng-dev is already the newest version (1.6.37-3).
The following packages were automatically installed and are no longer
required:
  libbrotli-dev:i386 libexpat1-dev:i386 libfreetype-dev:i386
libpng-dev:i386 libqt5location5 libqt5multimedia5 libqt5multimediawidgets5
libqt5positioningquick5 libqt5websockets5 libqt5xmlpatterns5 python3-mock
python3-pbr
  python3-pyqt5.qtmultimedia python3-pyqt5.qtopengl
python3-pyqt5.qtpositioning python3-pyqt5.qtquick python3-pyqt5.qtsql
python3-pyqt5.qtsvg python3-pyqt5.qtwebchannel python3-pyqt5.qtwebkit
python3-pyqt5.qtwebsockets
  python3-pyqt5.qtxmlpatterns
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by RICCIARDI-Adrien** [comment]
Hi,
OK, are you able to compile then ?

**Comment by RahRah80** [comment]
Hello.

I can compile the game, just can't run because i get this:

***@***.***:~/git/CroftEngine/build/src$ ./croftengine
[2022-12-20 15:21:40.987222] [0x00007f2293178340] [info]    Check user data
dir: "/home/rah-rah/git/CroftEngine/build/src"
[2022-12-20 15:21:40.988409] [0x00007f2293178340] [info]    User data dir:
"/home/rah-rah/git/CroftEngine/build/src"
[2022-12-20 15:21:40.988747] [0x00007f2293178340] [info]    Check user data
dir: "/home/rah-rah/git/CroftEngine/build/src"
[2022-12-20 15:21:40.988801] [0x00007f2293178340] [info]    User data dir:
"/home/rah-rah/git/CroftEngine/build/src"
failed to load translations for QLocale(English, Latin, United States) /
"en_US"
terminate called after throwing an instance of
'boost::wrapexcept<std::runtime_error>'
  what():  Missing required game file(s)

**Comment by stohrendorf** [comment]
@RahRah80 this is the wrong project.

**Comment by RICCIARDI-Adrien** [comment]
Thanks @stohrendorf, I didn't notice ! Indeed it was strange to me to see Qt-related errors in OpenTomb.

**Comment by RahRah80** [comment]
Hello.

Sorry about that, trying many games.

Compiled OpenTomb, for Tomb Raider 1 "OpenTomb/data/tr1/data" and the games
files DATA, EXTRAS and FMV

I ran the game, new game, press Ctrl but i can't select Tomb Raider 1 to
star.

Something missing or i'm not doing something right?

Thank you.

**Comment by RICCIARDI-Adrien** [comment]
Hi,
Do you have any log message in the console, like some files were not found because of the file name case sensitivity ?

**Comment by RahRah80** [comment]
Hello.

There is no output error, the game engine seems to run fine, just can't
select a game to play if is Tomb Raider 1 or other.
Can scroll up and down and nothing more.

I  used gdb with game and got this:

***@***.***:~/GAMES/Linux/OpenTomb$ gdb ./OpenTomb
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./OpenTomb...
(No debugging symbols found in ./OpenTomb)
(gdb) r
Starting program: /home/rah-rah/GAMES/Linux/OpenTomb/OpenTomb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed00c700 (LWP 3325)]
[New Thread 0x7fffe7fff700 (LWP 3326)]
[New Thread 0x7fffdffff700 (LWP 3327)]
[New Thread 0x7fffe77fe700 (LWP 3328)]
[New Thread 0x7fffe6ffd700 (LWP 3329)]
[New Thread 0x7fffe67fc700 (LWP 3330)]
[New Thread 0x7fffe5ffb700 (LWP 3331)]
[New Thread 0x7fffe57fa700 (LWP 3332)]
[New Thread 0x7fffe4ff9700 (LWP 3333)]
[New Thread 0x7fffdf7fe700 (LWP 3334)]
[New Thread 0x7fffdeffd700 (LWP 3335)]
[New Thread 0x7fffde7fc700 (LWP 3336)]
[New Thread 0x7fffddffb700 (LWP 3337)]
[New Thread 0x7fffdd7fa700 (LWP 3338)]
[New Thread 0x7fffdcff9700 (LWP 3339)]
[New Thread 0x7fffa7fff700 (LWP 3340)]
[Thread 0x7fffa7fff700 (LWP 3340) exited]
[New Thread 0x7fffa7fff700 (LWP 3341)]
[Thread 0x7fffa7fff700 (LWP 3341) exited]
[New Thread 0x7fffa7fff700 (LWP 3342)]
[Thread 0x7fffa7fff700 (LWP 3342) exited]
[New Thread 0x7fffa7fff700 (LWP 3343)]
[New Thread 0x7fffe47f8700 (LWP 3344)]
[Thread 0x7fffe47f8700 (LWP 3344) exited]
[New Thread 0x7fffa77fe700 (LWP 3345)]
[Thread 0x7fffa77fe700 (LWP 3345) exited]
[New Thread 0x7fffa77fe700 (LWP 3346)]
[New Thread 0x7fffe4777700 (LWP 3347)]
[New Thread 0x7fffdc7f8700 (LWP 3348)]
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 153

Warning: Can not read file "save/qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 153

Warning: Can not read file "save/qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 153

Warning: Can not read file "save/qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 153

Warning: Can not read file "save/qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 153

Warning: Can not read file "save/qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 153

Warning: Can not read file "save/qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367

Warning: Can not create file "qsave.lua"
[Thread 0x7fffa7fff700 (LWP 3343) exited]
[Thread 0x7fffdc7f8700 (LWP 3348) exited]
[Thread 0x7fffe4777700 (LWP 3347) exited]
[Thread 0x7fffa77fe700 (LWP 3346) exited]
[Thread 0x7fffdeffd700 (LWP 3335) exited]
[Thread 0x7fffdf7fe700 (LWP 3334) exited]
[Thread 0x7fffe4ff9700 (LWP 3333) exited]
[Thread 0x7fffe5ffb700 (LWP 3331) exited]
[Thread 0x7fffe67fc700 (LWP 3330) exited]
[Thread 0x7fffe57fa700 (LWP 3332) exited]
[Thread 0x7fffdcff9700 (LWP 3339) exited]
[Thread 0x7fffddffb700 (LWP 3337) exited]
[Thread 0x7fffdd7fa700 (LWP 3338) exited]
[Thread 0x7fffde7fc700 (LWP 3336) exited]
[Thread 0x7fffe6ffd700 (LWP 3329) exited]
[Thread 0x7fffe77fe700 (LWP 3328) exited]
[Thread 0x7fffe7fff700 (LWP 3326) exited]
[Thread 0x7fffdffff700 (LWP 3327) exited]
[Thread 0x7fffed00c700 (LWP 3325) exited]
[Inferior 1 (process 3321) exited normally]
(gdb) bt
No stack.
(gdb)
No stack.
(gdb) q
***@***.***:~/GAMES/Linux/OpenTomb$

The error of (Warning: Can not create file "qsave.lua"
"/home/rah-rah/git/OpenTomb/src/game.cpp" str = 367) and (Warning: Can not
create file "qsave.lua" "/home/rah-rah/git/OpenTomb/src/game.cpp" str = 153)
is when pressed F5 and F6

Thank you.

**Comment by RICCIARDI-Adrien** [comment]
Default menu controls are a bit strange because this is TeslaRus mapping, not the original games one.
Use A or S to navigate between menu tabs, then press Left Ctrl to enter a menu tab (the focus rectangle will change on screen). Use W and S to navigate up and down and Left Ctrl to select. There is also Escape to go up.

**Comment by RahRah80** [comment]
Hello

The Escape doesn't go back and  left control enters the menu, but won't
lauch the game tr1

**Comment by RICCIARDI-Adrien** [comment]
You can make sure that all TR1 files are named well and at the correct location, the game is expecting these files : https://github.com/opentomb/OpenTomb/blob/master/scripts/gameflow/TR1.lua.

**Comment by RahRah80** [comment]
Hello.

I had too many data directories.

Can select the game with left control, escape key doesn't work and can't
skip fmv sequences.

During game the enter key keeps jumping level... console opens after fmv
ends not during.

Can't crouch with V, F5 and F6 doesn't.

mlook 1 or 0 not working

**Comment by RICCIARDI-Adrien** [comment]
Hi,
Great if you are able to play !
If I recall well, you can't crouch in TR1 or TR2, this feature has been introduced in TR3, so this is normal.
FMV skipping was working before, maybe it is broken now. I don't have a playbable installation to test now.

**Comment by RahRah80** [comment]
Hello.
It's working, thanks.

Merry Christmas and Happy New Year!
