### ISSUE TITLE
Crash when leaving level with hair

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#63]
When leaving a level with hair (for example by ending the program), an assertion gets triggered because bodies are destroyed while there are still constraints between them.

**Comment by Lwmte** [comment]
Whoops, how could it automatically close from Windows GitHub client? I didn't do that! :D

**Comment by vvs-** [comment]
It's a GitHub [feature](https://help.github.com/articles/closing-issues-via-commit-messages)
