### ISSUE TITLE
Blended objects drawn too bright when in same room with them

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#67]
Blended objects are drawn brighter when the camera is in the same room as them. Easily observable in TR4,1: Just start running and look at the rays of light. I think these things are getting drawn twice.

Obviously related to all the VAO stuff.

**Comment by vvs-** [comment]
The same effect as with fountain in room 76. In that case the fountain is obviously incomplete but that changes as camera approaches its' room.

**Comment by vvs-** [comment]
I think it could be related to #65.

**Comment by cochrane** [comment]
I think these are two separate issues that happen to affect the same object in that particular case. Though I may be wrong here, of course.

**Comment by vvs-** [comment]
Both issues are fixed in 3fdd24ebd42b467fde63f865a48ff5238a41c137.

**Comment by cochrane** [comment]
Fascinating, that's completely different from what I thought was the issue.
