### ISSUE TITLE
Animated water surfaces don't show up from below

### ISSUE THREAD

**Issue by cochrane** [opentomb/OpenTomb#68]
Visible in TR≥3: From underneath, the water surface isn't there.

The problem is that the frustum rendering code rejects the polygon for facing the wrong way, even though it's double-sided. Fixing it is easy; just change Frustum_IsPolyVisible so that it doesn't do the "distance < 0" check if the polygon is double-sided. I'm just scared doing that may break something else because I don't understand the frustum code well, so I'd like some feedback on whether this would work first.

**Comment by vvs-** [comment]
Why not to make it in a branch then? Anyone could test it and `master` would be left intact.
