### ISSUE TITLE
Version specific labels for GitHub issues

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#69]
I propose to mark every issue with labels of TR versions which it affects. That way it will be easy to see at a glance how much attention it deserves in the current development cycle.

**Comment by cochrane** [comment]
Hm, just saw I completely forgot about this. Good idea, but I would only do it for things that are actually version-specific. An awful lot of things aren't, and labeling them with all versions will become tedious soon.

**Comment by vvs-** [comment]
I meant those bug which are known to happen only in specific versions. Right now, if someone would try to find bugs which prevent specific game version from being completed, they will be lost in details.

**Comment by vvs-** [comment]
I think it's done now. Thanks.

**Comment by stohrendorf** [comment]
You're welcome :smile:
