### ISSUE TITLE
Ladder climbing is broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#70]
Since dc254068e3067c738975fa86e32834c152546e83 it's almost impossible to grab a crossbar.

**Comment by Gh0stblade** [comment]
What do you mean by cross bar? Do you have an example?

**Comment by Gh0stblade** [comment]
Also this particular change was made to prevent Lara from teleporting in the grabbing state when up and action is pressed.

**Comment by vvs-** [comment]
I mean that decorative crossbar sections on ladders. Just try to climb any ladder, e.g. in TR3 gym. Lara is just jumping up without grabbing it to climb. It's possible but you need to try many times before successfully grabbing it.

**Comment by Gh0stblade** [comment]
Thanks for the info. Will take a look when I get home :)

**Comment by vvs-** [comment]
After experimenting more I found out that it depends on the distance between Lara and the ladder. If she is tightly close to it then she won't grab a crossbar. That happens when she walks to the ladder using shift. If she runs instead then usually she grabs it on the first attempt. Previous version was less picky about that.

**Comment by vvs-** [comment]
I guess it might be actually the same collision bug which prevents Lara from grabbing movable blocks and using levers.

**Comment by vvs-** [comment]
Fixed in 097184f7cec95c1760cda19243cc9e262dc71c09.
