### ISSUE TITLE
Monkey bars

### ISSUE THREAD

**Issue by Gh0stblade** [opentomb/OpenTomb#71]
Lara teleports to monkey bars if you jump and grab underneath them.

**Comment by vvs-** [comment]
Yes, I saw that too. And she often teleports to either side of a movable block when pushing or pulling it. This can cause penetration of room geometry. Collision code is still not quite ready yet.

**Comment by Gh0stblade** [comment]
Fixed in https://github.com/opentomb/OpenTomb/commit/19660543ab1df348f3f14055b49a2b0e6ea05715
