### ISSUE TITLE
Wrong move type in shallow water

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#80]
Try `setgamef(1.5,1)` `setEntityPos(player,36278,13468,3304,348,0,0)`. Happens after free fall or jump up in certain orientation.

**Comment by Joey79100** [comment]
Also, she's able to jump in every direction while she should be able only to jump up. At least, for TR2+...
Also, whenever she lands in shallow water (in TR2+), she must play animation 192 (swim to shallow water). This is not the case, she lands normally.

**Comment by vvs-** [comment]
I suspect that it might be related to #40, it's very similar.

**Comment by Gh0stblade** [comment]
Woops sorry for the close, there is some button on the keyboard which closes issues and I don't know what combination keeps doing it when i press it... Anyway...

1. It looks like there was a bug with using Lara's position to calculate whether she's in the water or not so I've made it utilise the direct floor value instead.

2. Lara's predefined height was actually incorrect and it has been changed.

3. Directional jumping whilst in wade depth is not possible.

See latest commits and let me know if it solves anything. Hopefully it shouldn't break anything, it also fixes swim issues in TR2 i encountered ages ago.

**Comment by vvs-** [comment]
It's not a button - it's a GitHub [feature](https://help.github.com/articles/closing-issues-via-commit-messages), e.g. cochrane used it all the way :smile:

It's working but incomplete. Try `setEntityPos(player,39327,16765,2959,175,0,0)` and run forward.

**Comment by Gh0stblade** [comment]
Should be fine now, i forgot Lara can't wade in TR1 so she must always be forced into swimming when she touches any form of water.

**Comment by vvs-** [comment]
Just what the doctor ordered. Thanks.
