### ISSUE TITLE
Boulders are stuck in some levels

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#81]
Again. They stuck in _Tomb of Qualopec_ and _Colosseum_, but not in _St. Francis' Folly_ and _Jungle_.

**Comment by Lwmte** [comment]
Yes, it's temporary, until we have entity-room callback functionality. They stuck generally in narrow places, where they have no place to go.

**Comment by vvs-** [comment]
They also have a low mass it seems. They easily get stuck at a tiny obstacles and Lara can push them like a balls.

**Comment by Lwmte** [comment]
Lara can kick them just because she's kinematic, while boulders themselves are dynamic. The solution here is to make boulder ghost collision and send Lara to ragdoll state just when she touches them. In this case, there will be no such situation.

However, boulder must be made static as long as it's stopped, so nothing (including Lara) may move it.

**Comment by vvs-** [comment]
Right now a boulders have a very low inertia, so they can't pass beyond any tiny obstacle.

**Comment by T4Larson** [comment]
It appears currently Lara or any other entity hasn't kinematic properties: The corresponding line where this is set for the body part is disabled, and I see no other code where this is set - or maybe I'm just overlooking something...
in entity.cpp:
```
//bt.bt_body[i]->setCollisionFlags(bt.bt_body[i]->getCollisionFlags() | btCollisionObject::CF_KINEMATIC_OBJECT);
```

**Comment by Lwmte** [comment]
Sincerely, I never got the meaning of CF_KINEMATIC_OBJECT flag. This commented line is probably remnant of my attempts to get hair or ragdolls working properly. I think it won't help solving issues with boulders.

**Comment by T4Larson** [comment]
>Lara can kick them just because she's kinematic, while boulders themselves are dynamic.

Well, if boulders were kinematic - as is indicated in entity_properties.lua - at least they wouldn't be moved around by the bullet solver.
Right now it seems everything is a dynamic body, where unwanted or unexpected movement via bullet's dynamic solver is then later is clamped back to engine calculated behaviour somehwere in code... and if you miss something, then you may get bullet's idea of how things should fly as a result.

**Comment by T4Larson** [comment]
I see now that most entities are even initalised with 0-mass, and hence are flagged static - I'm not sure if that makes it any better in regards of side effects (i.e. bullet's manual advises against moving static bodies at all, and I find it easy to imagine why, as it seems reasonable that they wouldn't apply dynamics to the whole system like a dymanic body would...)

**Comment by vvs-** [comment]
Also, collision problems here related to a more general #99.

**Comment by vvs-** [comment]
Looks like it's fixed.

**Comment by TeslaRus** [comment]
I use "heavy boulder" in TR1 only (but it can be easily enabled by LUA in TR2+); solution is not complete, and this time it is "hardcoded"; first I have to fix physics module interface, introduce new scripts function, fix physics initialization filter flags and... bingo! I can rewrite boulder script and write very powerful entity scripts;

**Comment by vvs-** [comment]
There are still stuck boulders left at least in _Atlantis_.

**Comment by TeslaRus** [comment]
stuck after https://github.com/opentomb/OpenTomb/commit/d7abd7366ae4650911718e03bc789450496526df too?

**Comment by vvs-** [comment]
Yep, e.g. in room 34 in _Atlantis_ and a few other places.

**Comment by TeslaRus** [comment]
heh - thanks... + I have found another collision bug: joined overlapped rooms...

**Comment by vvs-** [comment]
You mean this one?
![screen_00000](https://cloud.githubusercontent.com/assets/5171934/20867989/fa55c9be-ba61-11e6-9dbc-50909b2aabfa.png)

**Comment by TeslaRus** [comment]
yes, it is

**Comment by vvs-** [comment]
Oh, no. It happened again in a very specific circumstances.
![screen_00000](https://cloud.githubusercontent.com/assets/5171934/20868923/ba9701a0-ba78-11e6-95c6-9b4abbe829cf.png)

**Comment by TeslaRus** [comment]
fixed again =) https://github.com/opentomb/OpenTomb/commit/a20d856bc1150a47a46c9ddebe97363bdf470f58

**Comment by vvs-** [comment]
Wow! That looks like just what the doctor ordered 👍

We need to test it more before closing it for good, to make sure that there are no more corner cases. 😉

**Comment by vvs-** [comment]
Seems that the speed is too high. There is not enough time to complete the move in Atlas puzzle.

**Comment by TeslaRus** [comment]
I though about it: I write in notepad solution to fix it (speed = 2048, +ghost z only fixing), hope I will fix it today;

**Comment by TeslaRus** [comment]
entity_functions_common.lua, str 405 - magic 64 - tune that to allow / disallow boulders go over gaps
+fixed pushables on the air =)

**Comment by vvs-** [comment]
In _Return to Egypt_ all boulders are activated at once. In fact, only three of them should be activated behind the door. Others should activate much later.

**Comment by vvs-** [comment]
In _Atlantean Stronghold_ this boulder is stuck temporarily and thus could be activated twice.
![screen_00000](https://cloud.githubusercontent.com/assets/5171934/21012054/40ee6510-bd65-11e6-9a5d-b4b623970924.png)

**Comment by vvs-** [comment]
Just as a reminder that there is now a stuck boulder in _City of Khamoon_ after its collision shape changed to sphere.

**Comment by TeslaRus** [comment]
it was early true response from entityDrop function =)
