### ISSUE TITLE
Wrong falling ceiling behavior

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#85]
The trigger is certainly doing something wrong in *Tomb of Qualopec*. There are five ceiling entities in two rooms. Entities in room 5 are not visible but they are visible in room 20. Entity 25 actually never fall and remains on the ceiling. Entities in room 20 sometimes fall even when they are not triggered.

**Comment by vvs-** [comment]
Entities in room 20 now invisible. But falling ceiling is activated now by just approaching scion instead of taking it.

**Comment by vvs-** [comment]
Activation of a ceiling is now correct.

**Comment by vvs-** [comment]
BTW, what's with entity 25? It's initial position is above room geometry, so it can't penetrate it.

**Comment by Lwmte** [comment]
I guess that in original, falling ceiling only checks its collision with floor geometry, so it's no problem for it to penetrate ceiling. Presumably designer did it purposefully, so different debris fall at different time.

I have to modify its entity function, so it begins to check collision only when it arrives between ceiling and floor levels of the room.

**Comment by vvs-** [comment]
Regression to previous state. I guess it's related to old scripts too.

**Comment by vvs-** [comment]
It's a duplicate of #94.
