### ISSUE TITLE
Incorrect detection of DEATH trigger

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#9]
Currently, no additional collision checks are performed on DEATH sectors, only Lara move type is checked. This results in false DEATH triggers, for ex., when Lara is stepping onto trapdoor above lava. This should be fixable by checking if Lara has hit room collisional mesh OR static/entity mesh. Then we ignore DEATH trigger in latter case.

**Comment by vvs-** [comment]
While this is definitely an improvement, Lara still can't jump over the lava in *The Hive*. Shouldn't we keep that issue open?

**Comment by vvs-** [comment]
Regression. This fix need to be backported.
