### ISSUE TITLE
Bridges not working

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#95]
In _Obelisk of Khamoon_ bridges can't be activated by switches. But they can be successfully activated by `setEntityState` function.

**Comment by vvs-** [comment]
Looking at `entity_properties.lua` it's clear that model 41 has no activation function. Defining its' function as `door` did the trick. BTW it's described as a lifting door and not a bridge.

**Comment by vvs-** [comment]
The same, scripts need back porting.

**Comment by TeslaRus** [comment]
fixed in https://github.com/opentomb/OpenTomb/commit/e9888046a9ac0a296d536945105bdef7b2d3a0bb
